-- =====================================================================
-- Migración Supabase: Sección 02 - Cálculo Diferencial (183 preguntas)
-- Total preguntas en este script: 183
-- Fecha de generación: 2026-10-06T15:41:00.157Z
-- =====================================================================

-- Tabla e índices base
CREATE TABLE IF NOT EXISTS public.questions (
  id          TEXT PRIMARY KEY,
  section_id  TEXT NOT NULL,
  subtema_id  TEXT NOT NULL,
  law_id      TEXT NOT NULL,
  difficulty  TEXT NOT NULL CHECK (difficulty IN ('easy', 'medium', 'hard')),
  prompt      TEXT NOT NULL,
  options     JSONB NOT NULL,
  explanation TEXT NOT NULL DEFAULT '',
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS questions_law_idx ON public.questions (section_id, subtema_id, law_id);

ALTER TABLE public.questions ENABLE ROW LEVEL SECURITY;

-- Políticas RLS:
-- 1. Lectura pública (permite alumnos anónimos y autenticados)
DROP POLICY IF EXISTS "questions read auth" ON public.questions;
DROP POLICY IF EXISTS "questions read all" ON public.questions;
CREATE POLICY "questions read all" ON public.questions
  FOR SELECT TO anon, authenticated USING (true);

-- 2. Escritura restringida a administradores
DROP POLICY IF EXISTS "questions admin write" ON public.questions;
CREATE POLICY "questions admin write" ON public.questions
  FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM public.profiles p WHERE p.user_id = auth.uid() AND p.is_admin))
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles p WHERE p.user_id = auth.uid() AND p.is_admin));

-- Lote 1 (50 preguntas)
INSERT INTO public.questions (id, section_id, subtema_id, law_id, difficulty, prompt, options, explanation)
VALUES
  ($id$limsus-f-01$id$, $sec$calculo-diferencial$sec$, $sub$limites$sub$, $law$lim-sustitucion$law$, $diff$easy$diff$, $prompt$¿Cómo evalúas $\lim_{x \to 2} (3x + 1)$?$prompt$, $json$[{"latex":"\\text{Sustitución directa}","correct":true},{"latex":"\\text{Factorización}","correct":false},{"latex":"\\text{Racionalización}","correct":false},{"latex":"\\text{Regla de L'Hôpital}","correct":false}]$json$::jsonb, $exp$$3x + 1$ es un polinomio, continuo en todo $\mathbb{R}$: basta sustituir $x = 2$.$exp$),
  ($id$limsus-f-02$id$, $sec$calculo-diferencial$sec$, $sub$limites$sub$, $law$lim-sustitucion$law$, $diff$easy$diff$, $prompt$Calcula: $\lim_{x \to 2} (3x + 1)$$prompt$, $json$[{"latex":"7","correct":true},{"latex":"6","correct":false},{"latex":"5","correct":false},{"latex":"1","correct":false}]$json$::jsonb, $exp$Sustituye directamente: $3(2) + 1 = 7$.$exp$),
  ($id$limsus-f-03$id$, $sec$calculo-diferencial$sec$, $sub$limites$sub$, $law$lim-sustitucion$law$, $diff$easy$diff$, $prompt$Calcula: $\lim_{x \to 5} 8$$prompt$, $json$[{"latex":"8","correct":true},{"latex":"0","correct":false},{"latex":"5","correct":false},{"latex":"\\text{No existe}","correct":false}]$json$::jsonb, $exp$La función constante vale 8 para toda $x$; su límite es 8.$exp$),
  ($id$limsus-f-04$id$, $sec$calculo-diferencial$sec$, $sub$limites$sub$, $law$lim-sustitucion$law$, $diff$easy$diff$, $prompt$Calcula: $\lim_{x \to 1} (x^2 + 4x - 2)$$prompt$, $json$[{"latex":"3","correct":true},{"latex":"5","correct":false},{"latex":"1","correct":false},{"latex":"-2","correct":false}]$json$::jsonb, $exp$Sustituye: $1^2 + 4(1) - 2 = 3$.$exp$),
  ($id$limsus-f-05$id$, $sec$calculo-diferencial$sec$, $sub$limites$sub$, $law$lim-sustitucion$law$, $diff$easy$diff$, $prompt$¿Cuándo se puede usar la sustitución directa para calcular $\lim_{x \to a} f(x)$?$prompt$, $json$[{"latex":"\\text{Cuando } f \\text{ es continua en } a","correct":true},{"latex":"\\text{Siempre, en cualquier función}","correct":false},{"latex":"\\text{Solo cuando el resultado es } \\frac{0}{0}","correct":false},{"latex":"\\text{Solo si } f \\text{ es una constante}","correct":false}]$json$::jsonb, $exp$La sustitución directa es válida cuando $f$ es continua en $a$: el límite coincide con $f(a)$.$exp$),
  ($id$limsus-m-01$id$, $sec$calculo-diferencial$sec$, $sub$limites$sub$, $law$lim-sustitucion$law$, $diff$medium$diff$, $prompt$Calcula: $\lim_{x \to 3} \frac{x^2 - 1}{x + 1}$$prompt$, $json$[{"latex":"2","correct":true},{"latex":"\\frac{8}{3}","correct":false},{"latex":"4","correct":false},{"latex":"\\frac{0}{0}","correct":false}]$json$::jsonb, $exp$El denominador no se anula: sustituye $\frac{9 - 1}{3 + 1} = \frac{8}{4} = 2$.$exp$),
  ($id$limsus-m-02$id$, $sec$calculo-diferencial$sec$, $sub$limites$sub$, $law$lim-sustitucion$law$, $diff$medium$diff$, $prompt$¿Qué pasa si intentas evaluar $\lim_{x \to 0} \frac{\sin x}{x}$ por sustitución directa?$prompt$, $json$[{"latex":"\\text{Obtienes } \\frac{0}{0} \\text{ y no aplica}","correct":true},{"latex":"\\text{Obtienes } 1 \\text{ directamente}","correct":false},{"latex":"\\text{Obtienes } 0","correct":false},{"latex":"\\text{El límite no existe}","correct":false}]$json$::jsonb, $exp$Sustituir da $\frac{\sin 0}{0} = \frac{0}{0}$, una indeterminación: se necesita otro método (el límite es 1).$exp$),
  ($id$limsus-m-03$id$, $sec$calculo-diferencial$sec$, $sub$limites$sub$, $law$lim-sustitucion$law$, $diff$medium$diff$, $prompt$Calcula: $\lim_{x \to 2} (x^3 - 2x + 5)$$prompt$, $json$[{"latex":"9","correct":true},{"latex":"7","correct":false},{"latex":"5","correct":false},{"latex":"13","correct":false}]$json$::jsonb, $exp$Sustituye: $8 - 4 + 5 = 9$.$exp$),
  ($id$limsus-m-04$id$, $sec$calculo-diferencial$sec$, $sub$limites$sub$, $law$lim-sustitucion$law$, $diff$medium$diff$, $prompt$¿Qué método conviene para $\lim_{x \to 4} \frac{x - 4}{x^2 - 16}$?$prompt$, $json$[{"latex":"\\text{Factorizar y simplificar}","correct":true},{"latex":"\\text{Sustitución directa}","correct":false},{"latex":"\\text{Derivar numerador y denominador}","correct":false},{"latex":"\\text{Dividir entre la mayor potencia de } x","correct":false}]$json$::jsonb, $exp$Sustituir da $\frac{0}{0}$: se factoriza $x^2 - 16 = (x-4)(x+4)$ y se simplifica.$exp$),
  ($id$limsus-m-05$id$, $sec$calculo-diferencial$sec$, $sub$limites$sub$, $law$lim-sustitucion$law$, $diff$medium$diff$, $prompt$Calcula: $\lim_{x \to -1} (2x^2 - 3x + 1)$$prompt$, $json$[{"latex":"6","correct":true},{"latex":"0","correct":false},{"latex":"2","correct":false},{"latex":"-4","correct":false}]$json$::jsonb, $exp$Sustituye: $2(1) - 3(-1) + 1 = 2 + 3 + 1 = 6$.$exp$),
  ($id$limsus-h-01$id$, $sec$calculo-diferencial$sec$, $sub$limites$sub$, $law$lim-sustitucion$law$, $diff$hard$diff$, $prompt$Calcula: $\lim_{x \to 2} \frac{x^2 + 3x}{x - 1}$$prompt$, $json$[{"latex":"10","correct":true},{"latex":"4","correct":false},{"latex":"\\frac{10}{3}","correct":false},{"latex":"\\frac{0}{0}","correct":false}]$json$::jsonb, $exp$El denominador vale $1 \neq 0$: sustituye $\frac{4 + 6}{1} = 10$.$exp$),
  ($id$limsus-h-02$id$, $sec$calculo-diferencial$sec$, $sub$limites$sub$, $law$lim-sustitucion$law$, $diff$hard$diff$, $prompt$¿Cómo analizas $\lim_{x \to 0} \frac{|x|}{x}$?$prompt$, $json$[{"latex":"\\text{Con límites laterales: no existe}","correct":true},{"latex":"\\text{Sustitución directa: da } 1","correct":false},{"latex":"\\text{Factorización}","correct":false},{"latex":"\\text{Sustitución directa: da } 0","correct":false}]$json$::jsonb, $exp$En $x = 0$ no está definida; por la izquierda da $-1$ y por la derecha $1$: el límite no existe.$exp$),
  ($id$limsus-h-03$id$, $sec$calculo-diferencial$sec$, $sub$limites$sub$, $law$lim-sustitucion$law$, $diff$hard$diff$, $prompt$Calcula: $\lim_{x \to 3} \sqrt{x + 6}$$prompt$, $json$[{"latex":"3","correct":true},{"latex":"9","correct":false},{"latex":"\\sqrt{3}","correct":false},{"latex":"\\text{No existe}","correct":false}]$json$::jsonb, $exp$La raíz es continua donde está definida: sustituye $\sqrt{3 + 6} = \sqrt{9} = 3$.$exp$),
  ($id$limsus-h-04$id$, $sec$calculo-diferencial$sec$, $sub$limites$sub$, $law$lim-sustitucion$law$, $diff$hard$diff$, $prompt$¿Cuál de estos límites se resuelve por sustitución directa?$prompt$, $json$[{"latex":"\\lim_{x \\to 1} \\frac{x^3 + 1}{x + 1}","correct":true},{"latex":"\\lim_{x \\to 2} \\frac{x^2 - 4}{x - 2}","correct":false},{"latex":"\\lim_{x \\to 0} \\frac{\\sin x}{x}","correct":false},{"latex":"\\lim_{x \\to 3} \\frac{x - 3}{x^2 - 9}","correct":false}]$json$::jsonb, $exp$Solo $\frac{x^3 + 1}{x + 1}$ no se indetermina en el punto: da $\frac{2}{2} = 1$. Los demás producen $\frac{0}{0}$.$exp$),
  ($id$limsus-h-05$id$, $sec$calculo-diferencial$sec$, $sub$limites$sub$, $law$lim-sustitucion$law$, $diff$hard$diff$, $prompt$Calcula: $\lim_{x \to 1} \frac{x^4 + x^2 + 1}{x^2 + x + 1}$$prompt$, $json$[{"latex":"1","correct":true},{"latex":"3","correct":false},{"latex":"\\frac{1}{3}","correct":false},{"latex":"\\frac{0}{0}","correct":false}]$json$::jsonb, $exp$El denominador vale $3 \neq 0$: sustituye $\frac{1 + 1 + 1}{1 + 1 + 1} = 1$.$exp$),
  ($id$limind-f-01$id$, $sec$calculo-diferencial$sec$, $sub$limites$sub$, $law$lim-indeterminacion$law$, $diff$easy$diff$, $prompt$Calcula: $\lim_{x \to 3} \frac{x^2 - 9}{x - 3}$$prompt$, $json$[{"latex":"6","correct":true},{"latex":"0","correct":false},{"latex":"3","correct":false},{"latex":"\\text{No existe}","correct":false}]$json$::jsonb, $exp$Da $\frac{0}{0}$: factoriza $\frac{(x-3)(x+3)}{x-3} = x + 3 \to 6$.$exp$),
  ($id$limind-f-02$id$, $sec$calculo-diferencial$sec$, $sub$limites$sub$, $law$lim-indeterminacion$law$, $diff$easy$diff$, $prompt$¿Qué forma tiene $\lim_{x \to 3} \frac{x^2 - 9}{x - 3}$ al sustituir?$prompt$, $json$[{"latex":"\\frac{0}{0}","correct":true},{"latex":"\\frac{\\infty}{\\infty}","correct":false},{"latex":"\\frac{6}{0}","correct":false},{"latex":"\\text{Un número real}","correct":false}]$json$::jsonb, $exp$Numerador: $9 - 9 = 0$. Denominador: $3 - 3 = 0$. Forma indeterminada $\frac{0}{0}$.$exp$),
  ($id$limind-f-03$id$, $sec$calculo-diferencial$sec$, $sub$limites$sub$, $law$lim-indeterminacion$law$, $diff$easy$diff$, $prompt$Calcula: $\lim_{x \to 2} \frac{x^2 - 4}{x - 2}$$prompt$, $json$[{"latex":"4","correct":true},{"latex":"0","correct":false},{"latex":"2","correct":false},{"latex":"\\text{No existe}","correct":false}]$json$::jsonb, $exp$Factoriza: $\frac{(x-2)(x+2)}{x-2} = x + 2 \to 4$.$exp$),
  ($id$limind-f-04$id$, $sec$calculo-diferencial$sec$, $sub$limites$sub$, $law$lim-indeterminacion$law$, $diff$easy$diff$, $prompt$¿Qué método se usa ante una forma $\frac{0}{0}$ en un cociente de polinomios?$prompt$, $json$[{"latex":"\\text{Factorizar y simplificar}","correct":true},{"latex":"\\text{Sustitución directa}","correct":false},{"latex":"\\text{Dividir entre la mayor potencia}","correct":false},{"latex":"\\text{Evaluar en el infinito}","correct":false}]$json$::jsonb, $exp$Con $\frac{0}{0}$, el factor que se anula está presente en ambos polinomios: se factoriza y se simplifica.$exp$),
  ($id$limind-f-05$id$, $sec$calculo-diferencial$sec$, $sub$limites$sub$, $law$lim-indeterminacion$law$, $diff$easy$diff$, $prompt$Calcula: $\lim_{x \to 1} \frac{x^2 - 1}{x - 1}$$prompt$, $json$[{"latex":"2","correct":true},{"latex":"0","correct":false},{"latex":"1","correct":false},{"latex":"\\text{No existe}","correct":false}]$json$::jsonb, $exp$Factoriza: $\frac{(x-1)(x+1)}{x-1} = x + 1 \to 2$.$exp$),
  ($id$limind-m-01$id$, $sec$calculo-diferencial$sec$, $sub$limites$sub$, $law$lim-indeterminacion$law$, $diff$medium$diff$, $prompt$Calcula: $\lim_{x \to 0} \frac{\sqrt{x + 4} - 2}{x}$$prompt$, $json$[{"latex":"\\frac{1}{4}","correct":true},{"latex":"0","correct":false},{"latex":"4","correct":false},{"latex":"\\text{No existe}","correct":false}]$json$::jsonb, $exp$Racionaliza con el conjugado: $\frac{(\sqrt{x+4}-2)(\sqrt{x+4}+2)}{x(\sqrt{x+4}+2)} = \frac{x}{x(\sqrt{x+4}+2)} \to \frac{1}{4}$.$exp$),
  ($id$limind-m-02$id$, $sec$calculo-diferencial$sec$, $sub$limites$sub$, $law$lim-indeterminacion$law$, $diff$medium$diff$, $prompt$Calcula: $\lim_{x \to -2} \frac{x^2 + x - 2}{x + 2}$$prompt$, $json$[{"latex":"-3","correct":true},{"latex":"3","correct":false},{"latex":"0","correct":false},{"latex":"\\text{No existe}","correct":false}]$json$::jsonb, $exp$Factoriza: $\frac{(x+2)(x-1)}{x+2} = x - 1 \to -3$.$exp$),
  ($id$limind-m-03$id$, $sec$calculo-diferencial$sec$, $sub$limites$sub$, $law$lim-indeterminacion$law$, $diff$medium$diff$, $prompt$¿Cuándo conviene racionalizar para resolver un límite $\frac{0}{0}$?$prompt$, $json$[{"latex":"\\text{Cuando aparecen raíces en el numerador o denominador}","correct":true},{"latex":"\\text{Cuando hay solo polinomios}","correct":false},{"latex":"\\text{Cuando el límite es en el infinito}","correct":false},{"latex":"\\text{Nunca: siempre se factoriza}","correct":false}]$json$::jsonb, $exp$Multiplicar por el conjugado elimina la raíz y revela el factor común que produce el cero.$exp$),
  ($id$limind-m-04$id$, $sec$calculo-diferencial$sec$, $sub$limites$sub$, $law$lim-indeterminacion$law$, $diff$medium$diff$, $prompt$Calcula: $\lim_{x \to 4} \frac{x - 4}{\sqrt{x} - 2}$$prompt$, $json$[{"latex":"4","correct":true},{"latex":"2","correct":false},{"latex":"0","correct":false},{"latex":"\\text{No existe}","correct":false}]$json$::jsonb, $exp$Nota que $x - 4 = (\sqrt{x} - 2)(\sqrt{x} + 2)$: el cociente es $\sqrt{x} + 2 \to 4$.$exp$),
  ($id$limind-m-05$id$, $sec$calculo-diferencial$sec$, $sub$limites$sub$, $law$lim-indeterminacion$law$, $diff$medium$diff$, $prompt$¿Qué forma indeterminada produce $\lim_{x \to 2} \frac{x^3 - 8}{x - 2}$?$prompt$, $json$[{"latex":"\\frac{0}{0}","correct":true},{"latex":"\\frac{\\infty}{\\infty}","correct":false},{"latex":"0 \\cdot \\infty","correct":false},{"latex":"\\text{No hay indeterminación}","correct":false}]$json$::jsonb, $exp$$8 - 8 = 0$ arriba y $2 - 2 = 0$ abajo: forma $\frac{0}{0}$. Se usa diferencia de cubos.$exp$),
  ($id$limind-h-01$id$, $sec$calculo-diferencial$sec$, $sub$limites$sub$, $law$lim-indeterminacion$law$, $diff$hard$diff$, $prompt$Calcula: $\lim_{x \to 1} \frac{x^3 - 1}{x - 1}$$prompt$, $json$[{"latex":"3","correct":true},{"latex":"1","correct":false},{"latex":"0","correct":false},{"latex":"\\text{No existe}","correct":false}]$json$::jsonb, $exp$Diferencia de cubos: $\frac{(x-1)(x^2+x+1)}{x-1} = x^2 + x + 1 \to 3$.$exp$),
  ($id$limind-h-02$id$, $sec$calculo-diferencial$sec$, $sub$limites$sub$, $law$lim-indeterminacion$law$, $diff$hard$diff$, $prompt$Calcula: $\lim_{x \to 0} \frac{\sqrt{1 + x} - 1}{x}$$prompt$, $json$[{"latex":"\\frac{1}{2}","correct":true},{"latex":"1","correct":false},{"latex":"0","correct":false},{"latex":"2","correct":false}]$json$::jsonb, $exp$Racionaliza: $\frac{x}{x(\sqrt{1+x}+1)} = \frac{1}{\sqrt{1+x}+1} \to \frac{1}{2}$.$exp$),
  ($id$limind-h-03$id$, $sec$calculo-diferencial$sec$, $sub$limites$sub$, $law$lim-indeterminacion$law$, $diff$hard$diff$, $prompt$Calcula: $\lim_{x \to 2} \frac{x^2 - 4}{x^2 - 3x + 2}$$prompt$, $json$[{"latex":"4","correct":true},{"latex":"0","correct":false},{"latex":"2","correct":false},{"latex":"\\text{No existe}","correct":false}]$json$::jsonb, $exp$Factoriza ambos: $\frac{(x-2)(x+2)}{(x-1)(x-2)} = \frac{x+2}{x-1} \to \frac{4}{1} = 4$.$exp$),
  ($id$limind-h-04$id$, $sec$calculo-diferencial$sec$, $sub$limites$sub$, $law$lim-indeterminacion$law$, $diff$hard$diff$, $prompt$El patrón $\lim_{x \to a} \frac{x^n - a^n}{x - a}$ es igual a...$prompt$, $json$[{"latex":"n a^{n-1}","correct":true},{"latex":"a^n","correct":false},{"latex":"n a^n","correct":false},{"latex":"0","correct":false}]$json$::jsonb, $exp$Al factorizar y simplificar queda $x^{n-1} + a x^{n-2} + \cdots + a^{n-1}$, que en $x = a$ suma $n a^{n-1}$.$exp$),
  ($id$limind-h-05$id$, $sec$calculo-diferencial$sec$, $sub$limites$sub$, $law$lim-indeterminacion$law$, $diff$hard$diff$, $prompt$Calcula: $\lim_{x \to 9} \frac{x - 9}{\sqrt{x} - 3}$$prompt$, $json$[{"latex":"6","correct":true},{"latex":"3","correct":false},{"latex":"9","correct":false},{"latex":"\\text{No existe}","correct":false}]$json$::jsonb, $exp$$x - 9 = (\sqrt{x} - 3)(\sqrt{x} + 3)$: el cociente es $\sqrt{x} + 3 \to 6$.$exp$),
  ($id$liminf-f-01$id$, $sec$calculo-diferencial$sec$, $sub$limites$sub$, $law$lim-infinito$law$, $diff$easy$diff$, $prompt$Calcula: $\lim_{x \to \infty} \frac{2x + 1}{x - 3}$$prompt$, $json$[{"latex":"2","correct":true},{"latex":"0","correct":false},{"latex":"\\infty","correct":false},{"latex":"-3","correct":false}]$json$::jsonb, $exp$Mismo grado: el límite es el cociente de coeficientes principales, $\frac{2}{1} = 2$.$exp$),
  ($id$liminf-f-02$id$, $sec$calculo-diferencial$sec$, $sub$limites$sub$, $law$lim-infinito$law$, $diff$easy$diff$, $prompt$¿Qué método se usa para $\lim_{x \to \infty} \frac{2x + 1}{x - 3}$?$prompt$, $json$[{"latex":"\\text{Dividir todo entre la mayor potencia de } x","correct":true},{"latex":"\\text{Sustitución directa}","correct":false},{"latex":"\\text{Factorización}","correct":false},{"latex":"\\text{Racionalización}","correct":false}]$json$::jsonb, $exp$Dividir entre $x$ deja $\frac{2 + 1/x}{1 - 3/x}$; los términos con $1/x$ tienden a 0.$exp$),
  ($id$liminf-f-03$id$, $sec$calculo-diferencial$sec$, $sub$limites$sub$, $law$lim-infinito$law$, $diff$easy$diff$, $prompt$Calcula: $\lim_{x \to \infty} \frac{1}{x}$$prompt$, $json$[{"latex":"0","correct":true},{"latex":"1","correct":false},{"latex":"\\infty","correct":false},{"latex":"\\text{No existe}","correct":false}]$json$::jsonb, $exp$Cuando $x$ crece sin límite, $\frac{1}{x}$ se hace arbitrariamente pequeño: tiende a 0.$exp$),
  ($id$liminf-f-04$id$, $sec$calculo-diferencial$sec$, $sub$limites$sub$, $law$lim-infinito$law$, $diff$easy$diff$, $prompt$Calcula: $\lim_{x \to \infty} 5$$prompt$, $json$[{"latex":"5","correct":true},{"latex":"0","correct":false},{"latex":"\\infty","correct":false},{"latex":"\\text{No existe}","correct":false}]$json$::jsonb, $exp$Una constante no depende de $x$: su límite es la misma constante.$exp$),
  ($id$liminf-f-05$id$, $sec$calculo-diferencial$sec$, $sub$limites$sub$, $law$lim-infinito$law$, $diff$easy$diff$, $prompt$Si el grado del numerador es menor que el del denominador, $\lim_{x \to \infty} \frac{P(x)}{Q(x)}$ es...$prompt$, $json$[{"latex":"0","correct":true},{"latex":"\\infty","correct":false},{"latex":"\\text{El cociente de coeficientes principales}","correct":false},{"latex":"1","correct":false}]$json$::jsonb, $exp$El denominador crece más rápido que el numerador: el cociente tiende a 0.$exp$),
  ($id$liminf-m-01$id$, $sec$calculo-diferencial$sec$, $sub$limites$sub$, $law$lim-infinito$law$, $diff$medium$diff$, $prompt$Calcula: $\lim_{x \to \infty} \frac{3x^2 + 1}{5x^2 - 2}$$prompt$, $json$[{"latex":"\\frac{3}{5}","correct":true},{"latex":"0","correct":false},{"latex":"\\infty","correct":false},{"latex":"\\frac{5}{3}","correct":false}]$json$::jsonb, $exp$Grados iguales: cociente de coeficientes principales, $\frac{3}{5}$.$exp$),
  ($id$liminf-m-02$id$, $sec$calculo-diferencial$sec$, $sub$limites$sub$, $law$lim-infinito$law$, $diff$medium$diff$, $prompt$Calcula: $\lim_{x \to \infty} \frac{x^2}{x + 1}$$prompt$, $json$[{"latex":"\\infty","correct":true},{"latex":"0","correct":false},{"latex":"1","correct":false},{"latex":"\\frac{1}{2}","correct":false}]$json$::jsonb, $exp$El numerador tiene mayor grado: crece más rápido y el cociente diverge a $\infty$.$exp$),
  ($id$liminf-m-03$id$, $sec$calculo-diferencial$sec$, $sub$limites$sub$, $law$lim-infinito$law$, $diff$medium$diff$, $prompt$¿Qué regla aplica para decidir $\lim_{x \to \infty} \frac{4x^3 + 2x}{x^3 + 7}$?$prompt$, $json$[{"latex":"\\text{Comparar grados y usar coeficientes principales}","correct":true},{"latex":"\\text{Factorizar y simplificar}","correct":false},{"latex":"\\text{Racionalizar con el conjugado}","correct":false},{"latex":"\\text{Sustituir } x = 0","correct":false}]$json$::jsonb, $exp$Ambos polinomios tienen grado 3: el límite es $\frac{4}{1} = 4$.$exp$),
  ($id$liminf-m-04$id$, $sec$calculo-diferencial$sec$, $sub$limites$sub$, $law$lim-infinito$law$, $diff$medium$diff$, $prompt$Calcula: $\lim_{x \to \infty} \frac{4x^3 + 2x}{x^3 + 7}$$prompt$, $json$[{"latex":"4","correct":true},{"latex":"0","correct":false},{"latex":"\\frac{2}{7}","correct":false},{"latex":"\\infty","correct":false}]$json$::jsonb, $exp$Divide entre $x^3$: $\frac{4 + 2/x^2}{1 + 7/x^3} \to 4$.$exp$),
  ($id$liminf-m-05$id$, $sec$calculo-diferencial$sec$, $sub$limites$sub$, $law$lim-infinito$law$, $diff$medium$diff$, $prompt$Calcula: $\lim_{x \to \infty} \frac{2x}{x^2 + 1}$$prompt$, $json$[{"latex":"0","correct":true},{"latex":"2","correct":false},{"latex":"\\infty","correct":false},{"latex":"\\frac{1}{2}","correct":false}]$json$::jsonb, $exp$Grado del denominador (2) mayor que el del numerador (1): el límite es 0.$exp$),
  ($id$liminf-h-01$id$, $sec$calculo-diferencial$sec$, $sub$limites$sub$, $law$lim-infinito$law$, $diff$hard$diff$, $prompt$Calcula: $\lim_{x \to \infty} \frac{\sqrt{4x^2 + 1}}{x}$ (con $x > 0$)$prompt$, $json$[{"latex":"2","correct":true},{"latex":"4","correct":false},{"latex":"0","correct":false},{"latex":"\\infty","correct":false}]$json$::jsonb, $exp$Mete $x$ a la raíz: $\sqrt{\frac{4x^2+1}{x^2}} = \sqrt{4 + \frac{1}{x^2}} \to 2$.$exp$),
  ($id$liminf-h-02$id$, $sec$calculo-diferencial$sec$, $sub$limites$sub$, $law$lim-infinito$law$, $diff$hard$diff$, $prompt$Calcula: $\lim_{x \to \infty} \frac{5x^2 - 3}{2x^2 + x}$$prompt$, $json$[{"latex":"\\frac{5}{2}","correct":true},{"latex":"0","correct":false},{"latex":"\\infty","correct":false},{"latex":"\\frac{5}{3}","correct":false}]$json$::jsonb, $exp$Grados iguales: divide entre $x^2$ y queda $\frac{5 - 3/x^2}{2 + 1/x} \to \frac{5}{2}$.$exp$),
  ($id$liminf-h-03$id$, $sec$calculo-diferencial$sec$, $sub$limites$sub$, $law$lim-infinito$law$, $diff$hard$diff$, $prompt$Si $\lim_{x \to \infty} f(x) = L$ con $L$ finito, la recta $y = L$ es...$prompt$, $json$[{"latex":"\\text{Una asíntota horizontal}","correct":true},{"latex":"\\text{Una asíntota vertical}","correct":false},{"latex":"\\text{Una tangente en } x = 0","correct":false},{"latex":"\\text{Un eje de simetría}","correct":false}]$json$::jsonb, $exp$Cuando la función se acerca a un valor finito en el infinito, su gráfica se aproxima a la recta $y = L$.$exp$),
  ($id$liminf-h-04$id$, $sec$calculo-diferencial$sec$, $sub$limites$sub$, $law$lim-infinito$law$, $diff$hard$diff$, $prompt$Calcula: $\lim_{x \to \infty} \frac{x + 1}{x^2 + 1}$$prompt$, $json$[{"latex":"0","correct":true},{"latex":"1","correct":false},{"latex":"\\infty","correct":false},{"latex":"\\frac{1}{2}","correct":false}]$json$::jsonb, $exp$Divide entre $x^2$: $\frac{1/x + 1/x^2}{1 + 1/x^2} \to 0$.$exp$),
  ($id$liminf-h-05$id$, $sec$calculo-diferencial$sec$, $sub$limites$sub$, $law$lim-infinito$law$, $diff$hard$diff$, $prompt$Calcula: $\lim_{x \to \infty} (\sqrt{x^2 + x} - x)$$prompt$, $json$[{"latex":"\\frac{1}{2}","correct":true},{"latex":"0","correct":false},{"latex":"\\infty","correct":false},{"latex":"1","correct":false}]$json$::jsonb, $exp$Racionaliza: $\frac{x}{\sqrt{x^2+x}+x} = \frac{1}{\sqrt{1+1/x}+1} \to \frac{1}{2}$.$exp$),
  ($id$derb-f-01$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$easy$diff$, $prompt$Deriva: $f(x) = 9$$prompt$, $json$[{"latex":"0","correct":true},{"latex":"9","correct":false},{"latex":"1","correct":false},{"latex":"9x","correct":false}]$json$::jsonb, $exp$La derivada de toda constante es 0: $f'(x) = 0$.$exp$),
  ($id$derb-f-02$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$easy$diff$, $prompt$Deriva: $f(x) = -5$$prompt$, $json$[{"latex":"0","correct":true},{"latex":"-5","correct":false},{"latex":"-1","correct":false},{"latex":"5","correct":false}]$json$::jsonb, $exp$El signo no importa: $-5$ es constante y su derivada es 0.$exp$),
  ($id$derb-m-01$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$medium$diff$, $prompt$Deriva: $f(x) = \sqrt{2}$$prompt$, $json$[{"latex":"0","correct":true},{"latex":"\\frac{1}{2\\sqrt{2}}","correct":false},{"latex":"\\sqrt{2}","correct":false},{"latex":"\\frac{1}{\\sqrt{2}}","correct":false}]$json$::jsonb, $exp$$\sqrt{2}$ es un número fijo: es constante, no una función de $x$. Derivada: 0.$exp$),
  ($id$derb-m-02$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$medium$diff$, $prompt$Si $f(x) = 100$, ¿cuánto vale $f'(x)$?$prompt$, $json$[{"latex":"0","correct":true},{"latex":"100","correct":false},{"latex":"10","correct":false},{"latex":"1","correct":false}]$json$::jsonb, $exp$Fórmula I: la derivada de la constante 100 es 0.$exp$),
  ($id$derb-h-01$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$hard$diff$, $prompt$¿Cuál de estas funciones tiene derivada igual a 0?$prompt$, $json$[{"latex":"f(x) = -12","correct":true},{"latex":"f(x) = e^x","correct":false},{"latex":"f(x) = x","correct":false},{"latex":"f(x) = \\ln x","correct":false}]$json$::jsonb, $exp$Solo $-12$ es constante. $e^x$ deriva $e^x$, $x$ deriva 1 y $\ln x$ deriva $\frac{1}{x}$.$exp$)
ON CONFLICT (id) DO UPDATE SET
  section_id  = EXCLUDED.section_id,
  subtema_id  = EXCLUDED.subtema_id,
  law_id      = EXCLUDED.law_id,
  difficulty  = EXCLUDED.difficulty,
  prompt      = EXCLUDED.prompt,
  options     = EXCLUDED.options,
  explanation = EXCLUDED.explanation,
  updated_at  = now();

-- Lote 2 (50 preguntas)
INSERT INTO public.questions (id, section_id, subtema_id, law_id, difficulty, prompt, options, explanation)
VALUES
  ($id$derb-h-02$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$hard$diff$, $prompt$Una recta horizontal $y = c$ tiene pendiente...$prompt$, $json$[{"latex":"0, \\text{ por eso } \\frac{d}{dx}(c) = 0","correct":true},{"latex":"1, \\text{ por eso } \\frac{d}{dx}(c) = 1","correct":false},{"latex":"c","correct":false},{"latex":"\\text{Infinita}","correct":false}]$json$::jsonb, $exp$La derivada es la pendiente de la recta tangente: una recta horizontal tiene pendiente 0.$exp$),
  ($id$derb-f-03$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$easy$diff$, $prompt$Deriva: $f(x) = x$$prompt$, $json$[{"latex":"1","correct":true},{"latex":"0","correct":false},{"latex":"x","correct":false},{"latex":"x^2","correct":false}]$json$::jsonb, $exp$Fórmula II: $\frac{d}{dx}(x) = 1$.$exp$),
  ($id$derb-f-04$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$easy$diff$, $prompt$Si $f(x) = x$, ¿cuánto vale $f'(5)$?$prompt$, $json$[{"latex":"1","correct":true},{"latex":"5","correct":false},{"latex":"0","correct":false},{"latex":"\\frac{1}{5}","correct":false}]$json$::jsonb, $exp$$f'(x) = 1$ en todo punto, incluido $x = 5$.$exp$),
  ($id$derb-m-03$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$medium$diff$, $prompt$Deriva: $f(x) = -x$$prompt$, $json$[{"latex":"-1","correct":true},{"latex":"1","correct":false},{"latex":"-x","correct":false},{"latex":"0","correct":false}]$json$::jsonb, $exp$$-x = (-1) \cdot x$: sale la constante $-1$ y queda $(-1)(1) = -1$.$exp$),
  ($id$derb-m-04$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$medium$diff$, $prompt$Si $f(x) = x + 7$, ¿cuánto vale $f'(x)$?$prompt$, $json$[{"latex":"1","correct":true},{"latex":"8","correct":false},{"latex":"x","correct":false},{"latex":"0","correct":false}]$json$::jsonb, $exp$Suma (III): la identidad deriva 1 y la constante 7 deriva 0. Queda $1$.$exp$),
  ($id$derb-h-03$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$hard$diff$, $prompt$¿Cuál par de fórmulas es correcto?$prompt$, $json$[{"latex":"\\frac{d}{dx}(c) = 0 \\text{ y } \\frac{d}{dx}(x) = 1","correct":true},{"latex":"\\frac{d}{dx}(c) = 1 \\text{ y } \\frac{d}{dx}(x) = 0","correct":false},{"latex":"\\frac{d}{dx}(c) = c \\text{ y } \\frac{d}{dx}(x) = x","correct":false},{"latex":"\\frac{d}{dx}(c) = 0 \\text{ y } \\frac{d}{dx}(x) = 0","correct":false}]$json$::jsonb, $exp$Fórmulas I y II: las constantes derivan 0 y la identidad deriva 1.$exp$),
  ($id$derb-h-04$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$hard$diff$, $prompt$Deriva: $f(x) = x - 4$$prompt$, $json$[{"latex":"1","correct":true},{"latex":"-4","correct":false},{"latex":"x","correct":false},{"latex":"-3","correct":false}]$json$::jsonb, $exp$Resta (III): $x$ deriva 1 y $-4$ deriva 0. Queda $1$.$exp$),
  ($id$derb-f-05$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$easy$diff$, $prompt$Deriva: $f(x) = x + 3$$prompt$, $json$[{"latex":"1","correct":true},{"latex":"x","correct":false},{"latex":"3","correct":false},{"latex":"4","correct":false}]$json$::jsonb, $exp$Suma (III): $x$ deriva 1 y la constante 3 deriva 0. Queda $1$.$exp$),
  ($id$derb-f-06$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$easy$diff$, $prompt$Deriva: $f(x) = x^2 - x$$prompt$, $json$[{"latex":"2x - 1","correct":true},{"latex":"2x + 1","correct":false},{"latex":"x^2 - 1","correct":false},{"latex":"2x","correct":false}]$json$::jsonb, $exp$Término a término: $(x^2)' = 2x$ y $(x)' = 1$, conservando el signo: $2x - 1$.$exp$),
  ($id$derb-f-07$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$easy$diff$, $prompt$La derivada de una suma de funciones es...$prompt$, $json$[{"latex":"\\text{La suma de las derivadas}","correct":true},{"latex":"\\text{El producto de las derivadas}","correct":false},{"latex":"\\text{La derivada del primer término solamente}","correct":false},{"latex":"\\text{Siempre una constante}","correct":false}]$json$::jsonb, $exp$Fórmula III: $\frac{d}{dx}(u + v) = \frac{du}{dx} + \frac{dv}{dx}$.$exp$),
  ($id$derb-m-05$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$medium$diff$, $prompt$Deriva: $f(x) = 3x^2 - 2x$$prompt$, $json$[{"latex":"6x - 2","correct":true},{"latex":"6x + 2","correct":false},{"latex":"3x - 2","correct":false},{"latex":"6x^2 - 2","correct":false}]$json$::jsonb, $exp$Término a término con (III), (IV) y (VIa): $6x - 2$.$exp$),
  ($id$derb-m-06$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$medium$diff$, $prompt$Deriva: $f(x) = x^3 - x$$prompt$, $json$[{"latex":"3x^2 - 1","correct":true},{"latex":"3x^2 + 1","correct":false},{"latex":"x^2 - 1","correct":false},{"latex":"3x - 1","correct":false}]$json$::jsonb, $exp$Potencia (VIa) en cada término: $3x^2 - 1$.$exp$),
  ($id$derb-m-07$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$medium$diff$, $prompt$Deriva: $f(x) = 2x - 5$$prompt$, $json$[{"latex":"2","correct":true},{"latex":"-5","correct":false},{"latex":"2x","correct":false},{"latex":"-3","correct":false}]$json$::jsonb, $exp$La resta (III) separa los términos: $(2x)' = 2$ y $(-5)' = 0$.$exp$),
  ($id$derb-h-05$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$hard$diff$, $prompt$Deriva: $f(x) = x^4 - 3x^2 + x - 8$$prompt$, $json$[{"latex":"4x^3 - 6x + 1","correct":true},{"latex":"4x^3 - 6x - 8","correct":false},{"latex":"4x^3 - 3x + 1","correct":false},{"latex":"x^3 - 6x + 1","correct":false}]$json$::jsonb, $exp$Término a término: $4x^3 - 6x + 1 - 0$. El $-8$ deriva 0.$exp$),
  ($id$derb-h-06$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$hard$diff$, $prompt$Si $f(x) = x^2 - 4x$, ¿cuánto vale $f'(2)$?$prompt$, $json$[{"latex":"0","correct":true},{"latex":"4","correct":false},{"latex":"-4","correct":false},{"latex":"2","correct":false}]$json$::jsonb, $exp$$f'(x) = 2x - 4$; evaluando: $2(2) - 4 = 0$.$exp$),
  ($id$derb-h-07$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$hard$diff$, $prompt$Deriva: $f(x) = \sqrt{x} - \frac{1}{x}$$prompt$, $json$[{"latex":"\\frac{1}{2\\sqrt{x}} + \\frac{1}{x^2}","correct":true},{"latex":"\\frac{1}{2\\sqrt{x}} - \\frac{1}{x^2}","correct":false},{"latex":"\\frac{1}{\\sqrt{x}} + \\frac{1}{x^2}","correct":false},{"latex":"\\frac{1}{2\\sqrt{x}} + \\ln x","correct":false}]$json$::jsonb, $exp$$\sqrt{x} = x^{1/2}$ deriva $\frac{1}{2\sqrt{x}}$ y $\frac{1}{x} = x^{-1}$ deriva $-\frac{1}{x^2}$; con el signo menos queda $+\frac{1}{x^2}$.$exp$),
  ($id$derb-f-08$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$easy$diff$, $prompt$Deriva: $f(x) = 3x$$prompt$, $json$[{"latex":"3","correct":true},{"latex":"3x","correct":false},{"latex":"x","correct":false},{"latex":"0","correct":false}]$json$::jsonb, $exp$Fórmula IV: $3 \cdot \frac{d}{dx}(x) = 3 \cdot 1 = 3$.$exp$),
  ($id$derb-f-09$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$easy$diff$, $prompt$Deriva: $f(x) = 7x^3$$prompt$, $json$[{"latex":"21x^2","correct":true},{"latex":"7x^2","correct":false},{"latex":"21x^3","correct":false},{"latex":"3x^2","correct":false}]$json$::jsonb, $exp$La constante sale: $7 \cdot 3x^2 = 21x^2$.$exp$),
  ($id$derb-f-10$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$easy$diff$, $prompt$Deriva: $f(x) = 2x$$prompt$, $json$[{"latex":"2","correct":true},{"latex":"2x","correct":false},{"latex":"1","correct":false},{"latex":"0","correct":false}]$json$::jsonb, $exp$$2 \cdot \frac{d}{dx}(x) = 2 \cdot 1 = 2$.$exp$),
  ($id$derb-m-08$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$medium$diff$, $prompt$Deriva: $f(x) = 4x^3$$prompt$, $json$[{"latex":"12x^2","correct":true},{"latex":"4x^2","correct":false},{"latex":"12x^3","correct":false},{"latex":"3x^2","correct":false}]$json$::jsonb, $exp$Constante fuera (IV) y potencia (VIa): $4 \cdot 3x^2 = 12x^2$.$exp$),
  ($id$derb-m-09$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$medium$diff$, $prompt$Deriva: $f(x) = \frac{x}{3}$$prompt$, $json$[{"latex":"\\frac{1}{3}","correct":true},{"latex":"\\frac{1}{9}","correct":false},{"latex":"3","correct":false},{"latex":"\\frac{x}{3}","correct":false}]$json$::jsonb, $exp$Dividir entre 3 es multiplicar por $\frac{1}{3}$ (fórmula VIIa/IV): queda $\frac{1}{3}$.$exp$),
  ($id$derb-m-10$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$medium$diff$, $prompt$Deriva: $f(x) = -5x^2$$prompt$, $json$[{"latex":"-10x","correct":true},{"latex":"10x","correct":false},{"latex":"-5x","correct":false},{"latex":"-10x^2","correct":false}]$json$::jsonb, $exp$El $-5$ sale: $-5 \cdot 2x = -10x$. El signo se conserva.$exp$),
  ($id$derb-h-08$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$hard$diff$, $prompt$Deriva: $f(x) = 6\sqrt{x}$$prompt$, $json$[{"latex":"\\frac{3}{\\sqrt{x}}","correct":true},{"latex":"\\frac{6}{\\sqrt{x}}","correct":false},{"latex":"3\\sqrt{x}","correct":false},{"latex":"\\frac{1}{2\\sqrt{x}}","correct":false}]$json$::jsonb, $exp$$6 \cdot \frac{1}{2\sqrt{x}} = \frac{3}{\sqrt{x}}$.$exp$),
  ($id$derb-h-09$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$hard$diff$, $prompt$Deriva: $f(x) = \pi x^2$$prompt$, $json$[{"latex":"2\\pi x","correct":true},{"latex":"\\pi x","correct":false},{"latex":"2x","correct":false},{"latex":"0","correct":false}]$json$::jsonb, $exp$$\pi$ es una constante y sale de la derivada: $\pi \cdot 2x = 2\pi x$.$exp$),
  ($id$derb-h-10$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$hard$diff$, $prompt$Si $f'(x)$ existe, ¿cuánto vale $\frac{d}{dx}(3f(x))$?$prompt$, $json$[{"latex":"3 f'(x)","correct":true},{"latex":"f'(x)","correct":false},{"latex":"3 f(x)","correct":false},{"latex":"0","correct":false}]$json$::jsonb, $exp$Fórmula IV en forma general: la constante sale y se deriva la función.$exp$),
  ($id$derb-f-11$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$easy$diff$, $prompt$Deriva $f(x) = x \cdot x$ usando la regla del producto.$prompt$, $json$[{"latex":"2x","correct":true},{"latex":"x","correct":false},{"latex":"x^2","correct":false},{"latex":"1","correct":false}]$json$::jsonb, $exp$$u = v = x$: $x(1) + x(1) = 2x$. Coincide con derivar $x^2$ por potencia.$exp$),
  ($id$derb-f-12$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$easy$diff$, $prompt$Deriva: $f(x) = x e^x$$prompt$, $json$[{"latex":"e^x + x e^x","correct":true},{"latex":"e^x","correct":false},{"latex":"x e^x","correct":false},{"latex":"1 + e^x","correct":false}]$json$::jsonb, $exp$Producto (V) con $u = x$, $v = e^x$: $x e^x + e^x \cdot 1 = e^x + x e^x$.$exp$),
  ($id$derb-f-13$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$easy$diff$, $prompt$¿Cuál es la fórmula del producto (V)?$prompt$, $json$[{"latex":"\\frac{d}{dx}(uv) = u \\frac{dv}{dx} + v \\frac{du}{dx}","correct":true},{"latex":"\\frac{d}{dx}(uv) = \\frac{du}{dx} \\cdot \\frac{dv}{dx}","correct":false},{"latex":"\\frac{d}{dx}(uv) = u \\frac{du}{dx} + v \\frac{dv}{dx}","correct":false},{"latex":"\\frac{d}{dx}(uv) = u \\frac{dv}{dx} - v \\frac{du}{dx}","correct":false}]$json$::jsonb, $exp$La derivada de un producto NO es el producto de las derivadas: es $u v' + v u'$.$exp$),
  ($id$derb-m-11$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$medium$diff$, $prompt$Deriva: $f(x) = x^2 e^x$$prompt$, $json$[{"latex":"2x e^x + x^2 e^x","correct":true},{"latex":"2x e^x","correct":false},{"latex":"x^2 e^x","correct":false},{"latex":"2x + e^x","correct":false}]$json$::jsonb, $exp$Producto (V): $x^2 e^x + e^x (2x) = 2x e^x + x^2 e^x$.$exp$),
  ($id$derb-m-12$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$medium$diff$, $prompt$Deriva: $f(x) = x \ln x$$prompt$, $json$[{"latex":"\\ln x + 1","correct":true},{"latex":"\\frac{1}{x}","correct":false},{"latex":"\\ln x","correct":false},{"latex":"x \\ln x + 1","correct":false}]$json$::jsonb, $exp$Producto (V): $x \cdot \frac{1}{x} + \ln x \cdot 1 = 1 + \ln x$.$exp$),
  ($id$derb-m-13$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$medium$diff$, $prompt$Deriva: $f(x) = x \cos x$$prompt$, $json$[{"latex":"\\cos x - x \\sin x","correct":true},{"latex":"\\cos x + x \\sin x","correct":false},{"latex":"-\\sin x","correct":false},{"latex":"-x \\sin x","correct":false}]$json$::jsonb, $exp$Producto (V): $x(-\sin x) + \cos x(1) = \cos x - x \sin x$.$exp$),
  ($id$derb-h-11$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$hard$diff$, $prompt$Deriva: $f(x) = x^2 \ln x$$prompt$, $json$[{"latex":"2x \\ln x + x","correct":true},{"latex":"2x \\ln x","correct":false},{"latex":"2x + \\frac{1}{x}","correct":false},{"latex":"x \\ln x + x^2","correct":false}]$json$::jsonb, $exp$Producto (V): $x^2 \cdot \frac{1}{x} + \ln x \cdot 2x = x + 2x \ln x$.$exp$),
  ($id$derb-h-12$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$hard$diff$, $prompt$Si $f(x) = x e^x$, ¿cuánto vale $f'(0)$?$prompt$, $json$[{"latex":"1","correct":true},{"latex":"0","correct":false},{"latex":"e","correct":false},{"latex":"-1","correct":false}]$json$::jsonb, $exp$$f'(x) = e^x + x e^x$; en $x = 0$: $1 + 0 = 1$.$exp$),
  ($id$derb-h-13$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$hard$diff$, $prompt$Deriva: $f(x) = (2x + 1)(x^2 - 3)$$prompt$, $json$[{"latex":"6x^2 + 2x - 6","correct":true},{"latex":"2x^2 - 3","correct":false},{"latex":"4x(2x+1)","correct":false},{"latex":"6x^2 - 6","correct":false}]$json$::jsonb, $exp$Producto (V): $(2x+1)(2x) + (x^2-3)(2) = 4x^2 + 2x + 2x^2 - 6 = 6x^2 + 2x - 6$.$exp$),
  ($id$derb-f-14$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$easy$diff$, $prompt$Deriva: $f(x) = x^3$$prompt$, $json$[{"latex":"3x^2","correct":true},{"latex":"x^2","correct":false},{"latex":"3x^3","correct":false},{"latex":"2x^3","correct":false}]$json$::jsonb, $exp$Fórmula VIa: baja el exponente y réstale 1: $3x^{3-1} = 3x^2$.$exp$),
  ($id$derb-f-15$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$easy$diff$, $prompt$Deriva: $f(x) = x^5$$prompt$, $json$[{"latex":"5x^4","correct":true},{"latex":"x^4","correct":false},{"latex":"5x^5","correct":false},{"latex":"4x^5","correct":false}]$json$::jsonb, $exp$$5x^{5-1} = 5x^4$.$exp$),
  ($id$derb-f-16$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$easy$diff$, $prompt$Deriva: $f(x) = x^2$$prompt$, $json$[{"latex":"2x","correct":true},{"latex":"x","correct":false},{"latex":"2","correct":false},{"latex":"x^2","correct":false}]$json$::jsonb, $exp$$2x^{2-1} = 2x$.$exp$),
  ($id$derb-m-14$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$medium$diff$, $prompt$Deriva: $f(x) = x^{-2}$$prompt$, $json$[{"latex":"-2x^{-3}","correct":true},{"latex":"2x^{-3}","correct":false},{"latex":"-2x^{-1}","correct":false},{"latex":"-\\frac{2}{x}","correct":false}]$json$::jsonb, $exp$La fórmula vale para exponentes negativos: $-2x^{-2-1} = -2x^{-3}$.$exp$),
  ($id$derb-m-15$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$medium$diff$, $prompt$Deriva: $f(x) = \sqrt{x}$$prompt$, $json$[{"latex":"\\frac{1}{2\\sqrt{x}}","correct":true},{"latex":"\\frac{1}{\\sqrt{x}}","correct":false},{"latex":"2\\sqrt{x}","correct":false},{"latex":"\\frac{\\sqrt{x}}{2}","correct":false}]$json$::jsonb, $exp$Escribe $\sqrt{x} = x^{1/2}$: $\frac{1}{2}x^{-1/2} = \frac{1}{2\sqrt{x}}$.$exp$),
  ($id$derb-m-16$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$medium$diff$, $prompt$Deriva: $f(x) = x^{3/2}$$prompt$, $json$[{"latex":"\\frac{3}{2} x^{1/2}","correct":true},{"latex":"\\frac{3}{2} x^{3/2}","correct":false},{"latex":"\\frac{1}{2} x^{1/2}","correct":false},{"latex":"3 x^{1/2}","correct":false}]$json$::jsonb, $exp$$\frac{3}{2} x^{3/2 - 1} = \frac{3}{2} x^{1/2}$.$exp$),
  ($id$derb-h-14$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$hard$diff$, $prompt$Deriva: $f(x) = \frac{1}{x^3}$$prompt$, $json$[{"latex":"-\\frac{3}{x^4}","correct":true},{"latex":"\\frac{3}{x^4}","correct":false},{"latex":"-\\frac{3}{x^2}","correct":false},{"latex":"-\\frac{1}{x^4}","correct":false}]$json$::jsonb, $exp$$x^{-3}$ deriva $-3x^{-4} = -\frac{3}{x^4}$.$exp$),
  ($id$derb-h-15$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$hard$diff$, $prompt$Deriva: $f(x) = x^{\pi}$$prompt$, $json$[{"latex":"\\pi x^{\\pi - 1}","correct":true},{"latex":"x^{\\pi - 1}","correct":false},{"latex":"\\pi x^{\\pi}","correct":false},{"latex":"e^{\\pi} x^{\\pi - 1}","correct":false}]$json$::jsonb, $exp$La fórmula VIa vale para cualquier exponente real constante, incluido $\pi$.$exp$),
  ($id$derb-h-16$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$hard$diff$, $prompt$Deriva: $f(x) = x^{-1/2}$$prompt$, $json$[{"latex":"-\\frac{1}{2 x^{3/2}}","correct":true},{"latex":"\\frac{1}{2 x^{3/2}}","correct":false},{"latex":"-\\frac{1}{2 x^{1/2}}","correct":false},{"latex":"-\\frac{1}{2} x^{1/2}","correct":false}]$json$::jsonb, $exp$$-\frac{1}{2} x^{-1/2 - 1} = -\frac{1}{2} x^{-3/2} = -\frac{1}{2 x^{3/2}}$.$exp$),
  ($id$derb-f-17$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$easy$diff$, $prompt$Deriva: $f(x) = \frac{x}{x}$$prompt$, $json$[{"latex":"0","correct":true},{"latex":"1","correct":false},{"latex":"\\frac{1}{x}","correct":false},{"latex":"x","correct":false}]$json$::jsonb, $exp$$\frac{x}{x} = 1$ (para $x \neq 0$), una constante: deriva 0. La fórmula VII da $\frac{x - x}{x^2} = 0$.$exp$),
  ($id$derb-f-18$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$easy$diff$, $prompt$Deriva: $f(x) = \frac{1}{x}$$prompt$, $json$[{"latex":"-\\frac{1}{x^2}","correct":true},{"latex":"\\frac{1}{x^2}","correct":false},{"latex":"\\ln x","correct":false},{"latex":"-\\frac{1}{x}","correct":false}]$json$::jsonb, $exp$Con VII: $\frac{x \cdot 0 - 1 \cdot 1}{x^2} = -\frac{1}{x^2}$. También es potencia: $(x^{-1})' = -x^{-2}$.$exp$),
  ($id$derb-f-19$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$easy$diff$, $prompt$¿Cuál es la fórmula del cociente (VII)?$prompt$, $json$[{"latex":"\\frac{v \\frac{du}{dx} - u \\frac{dv}{dx}}{v^2}","correct":true},{"latex":"\\frac{u \\frac{dv}{dx} - v \\frac{du}{dx}}{v^2}","correct":false},{"latex":"\\frac{\\frac{du}{dx}}{\\frac{dv}{dx}}","correct":false},{"latex":"\\frac{v \\frac{du}{dx} + u \\frac{dv}{dx}}{v^2}","correct":false}]$json$::jsonb, $exp$El orden importa: es (denominador)(derivada del numerador) − (numerador)(derivada del denominador), entre $v^2$.$exp$),
  ($id$derb-m-17$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$medium$diff$, $prompt$Deriva: $f(x) = \frac{x}{x^2 + 1}$$prompt$, $json$[{"latex":"\\frac{1 - x^2}{(x^2 + 1)^2}","correct":true},{"latex":"\\frac{1 + x^2}{(x^2 + 1)^2}","correct":false},{"latex":"\\frac{1}{2x}","correct":false},{"latex":"\\frac{x^2 - 1}{(x^2 + 1)^2}","correct":false}]$json$::jsonb, $exp$Fórmula VII: $\frac{(x^2+1)(1) - x(2x)}{(x^2+1)^2} = \frac{1 - x^2}{(x^2+1)^2}$.$exp$),
  ($id$derb-m-18$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$medium$diff$, $prompt$Deriva: $f(x) = \frac{x^2}{x + 1}$$prompt$, $json$[{"latex":"\\frac{x^2 + 2x}{(x + 1)^2}","correct":true},{"latex":"\\frac{2x}{(x + 1)^2}","correct":false},{"latex":"\\frac{x^2 - 2x}{(x + 1)^2}","correct":false},{"latex":"2x","correct":false}]$json$::jsonb, $exp$Fórmula VII: $\frac{(x+1)(2x) - x^2(1)}{(x+1)^2} = \frac{x^2 + 2x}{(x+1)^2}$.$exp$),
  ($id$derb-m-19$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$medium$diff$, $prompt$¿Qué regla usas para derivar $f(x) = \frac{\sin x}{x}$?$prompt$, $json$[{"latex":"\\text{Regla del cociente (VII)}","correct":true},{"latex":"\\text{Regla de la cadena (VIII)}","correct":false},{"latex":"\\text{Solo derivada del seno (XIII)}","correct":false},{"latex":"\\text{Constante por función (IV)}","correct":false}]$json$::jsonb, $exp$Ambos, $\sin x$ y $x$, dependen de $x$: cociente (VII).$exp$),
  ($id$derb-h-17$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$hard$diff$, $prompt$Deriva: $f(x) = \frac{e^x}{x}$$prompt$, $json$[{"latex":"\\frac{x e^x - e^x}{x^2}","correct":true},{"latex":"\\frac{e^x}{x^2}","correct":false},{"latex":"\\frac{x e^x + e^x}{x^2}","correct":false},{"latex":"\\frac{e^x - x e^x}{x^2}","correct":false}]$json$::jsonb, $exp$Fórmula VII: $\frac{x e^x - e^x}{x^2} = \frac{e^x(x - 1)}{x^2}$.$exp$)
ON CONFLICT (id) DO UPDATE SET
  section_id  = EXCLUDED.section_id,
  subtema_id  = EXCLUDED.subtema_id,
  law_id      = EXCLUDED.law_id,
  difficulty  = EXCLUDED.difficulty,
  prompt      = EXCLUDED.prompt,
  options     = EXCLUDED.options,
  explanation = EXCLUDED.explanation,
  updated_at  = now();

-- Lote 3 (50 preguntas)
INSERT INTO public.questions (id, section_id, subtema_id, law_id, difficulty, prompt, options, explanation)
VALUES
  ($id$derb-h-18$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$hard$diff$, $prompt$Deriva: $f(x) = \frac{\ln x}{x}$$prompt$, $json$[{"latex":"\\frac{1 - \\ln x}{x^2}","correct":true},{"latex":"\\frac{1 + \\ln x}{x^2}","correct":false},{"latex":"\\frac{1}{x^2}","correct":false},{"latex":"\\frac{\\ln x - 1}{x^2}","correct":false}]$json$::jsonb, $exp$Fórmula VII: $\frac{x \cdot \frac{1}{x} - \ln x}{x^2} = \frac{1 - \ln x}{x^2}$.$exp$),
  ($id$derb-h-19$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$hard$diff$, $prompt$Si $f(x) = \frac{x}{x + 1}$, ¿cuánto vale $f'(1)$?$prompt$, $json$[{"latex":"\\frac{1}{4}","correct":true},{"latex":"\\frac{1}{2}","correct":false},{"latex":"1","correct":false},{"latex":"\\frac{3}{4}","correct":false}]$json$::jsonb, $exp$$f'(x) = \frac{(x+1) - x}{(x+1)^2} = \frac{1}{(x+1)^2}$; en $x = 1$: $\frac{1}{4}$.$exp$),
  ($id$derb-f-20$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$easy$diff$, $prompt$Deriva: $f(x) = (3x)^2$$prompt$, $json$[{"latex":"18x","correct":true},{"latex":"9x","correct":false},{"latex":"6x^2","correct":false},{"latex":"3x^2","correct":false}]$json$::jsonb, $exp$Cadena: $2(3x) \cdot 3 = 18x$. (También: $(3x)^2 = 9x^2$ y su derivada es $18x$.)$exp$),
  ($id$derb-f-21$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$easy$diff$, $prompt$Deriva: $f(x) = (x + 1)^3$$prompt$, $json$[{"latex":"3(x + 1)^2","correct":true},{"latex":"(x + 1)^2","correct":false},{"latex":"3x^2","correct":false},{"latex":"3(x + 1)^3","correct":false}]$json$::jsonb, $exp$Cadena con $v = x + 1$: $3(x+1)^2 \cdot 1 = 3(x+1)^2$.$exp$),
  ($id$derb-f-22$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$easy$diff$, $prompt$Deriva: $f(x) = \sin(2x)$$prompt$, $json$[{"latex":"2\\cos(2x)","correct":true},{"latex":"\\cos(2x)","correct":false},{"latex":"2\\sin(2x)","correct":false},{"latex":"-2\\cos(2x)","correct":false}]$json$::jsonb, $exp$Cadena con XIII: $\cos(2x) \cdot 2 = 2\cos(2x)$.$exp$),
  ($id$derb-f-23$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$easy$diff$, $prompt$Deriva: $f(x) = \cos(5x)$$prompt$, $json$[{"latex":"-5\\sin(5x)","correct":true},{"latex":"5\\sin(5x)","correct":false},{"latex":"-\\sin(5x)","correct":false},{"latex":"-5\\cos(5x)","correct":false}]$json$::jsonb, $exp$Cadena con XIV: $-\sin(5x) \cdot 5 = -5\sin(5x)$.$exp$),
  ($id$derb-m-20$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$medium$diff$, $prompt$Deriva: $f(x) = (x^2 + 1)^4$$prompt$, $json$[{"latex":"8x(x^2 + 1)^3","correct":true},{"latex":"4(x^2 + 1)^3","correct":false},{"latex":"8x(x^2 + 1)^4","correct":false},{"latex":"4x(x^2 + 1)^3","correct":false}]$json$::jsonb, $exp$Cadena: $4(x^2+1)^3 \cdot 2x = 8x(x^2+1)^3$.$exp$),
  ($id$derb-m-21$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$medium$diff$, $prompt$Deriva: $f(x) = \sqrt{2x + 1}$$prompt$, $json$[{"latex":"\\frac{1}{\\sqrt{2x + 1}}","correct":true},{"latex":"\\frac{2}{\\sqrt{2x + 1}}","correct":false},{"latex":"\\frac{1}{2\\sqrt{2x + 1}}","correct":false},{"latex":"\\frac{1}{2x + 1}","correct":false}]$json$::jsonb, $exp$Cadena con potencia $\frac{1}{2}$: $\frac{1}{2}(2x+1)^{-1/2} \cdot 2 = \frac{1}{\sqrt{2x+1}}$.$exp$),
  ($id$derb-m-22$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$medium$diff$, $prompt$Deriva: $f(x) = \sin(x^2)$$prompt$, $json$[{"latex":"2x \\cos(x^2)","correct":true},{"latex":"\\cos(x^2)","correct":false},{"latex":"2x \\sin(x^2)","correct":false},{"latex":"\\cos(2x)","correct":false}]$json$::jsonb, $exp$Cadena con XIII: $\cos(x^2) \cdot 2x = 2x \cos(x^2)$.$exp$),
  ($id$derb-m-23$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$medium$diff$, $prompt$Deriva: $f(x) = e^{-x^2}$$prompt$, $json$[{"latex":"-2x e^{-x^2}","correct":true},{"latex":"2x e^{-x^2}","correct":false},{"latex":"-e^{-x^2}","correct":false},{"latex":"-x^2 e^{-x^2 - 1}","correct":false}]$json$::jsonb, $exp$Cadena con XIa: $e^{-x^2} \cdot (-2x) = -2x e^{-x^2}$.$exp$),
  ($id$derb-h-20$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$hard$diff$, $prompt$Deriva: $f(x) = \sqrt[3]{x^2 + 1}$$prompt$, $json$[{"latex":"\\frac{2x}{3(x^2 + 1)^{2/3}}","correct":true},{"latex":"\\frac{1}{3(x^2 + 1)^{2/3}}","correct":false},{"latex":"\\frac{2}{3}(x^2 + 1)^{1/3}","correct":false},{"latex":"\\frac{2x}{(x^2 + 1)^{2/3}}","correct":false}]$json$::jsonb, $exp$Potencia $\frac{1}{3}$ con cadena: $\frac{1}{3}(x^2+1)^{-2/3} \cdot 2x = \frac{2x}{3(x^2+1)^{2/3}}$.$exp$),
  ($id$derb-h-21$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$hard$diff$, $prompt$Si $y = v^3$ y $v = 2x$, ¿cuánto vale $\frac{dy}{dx}$ según la fórmula VIII?$prompt$, $json$[{"latex":"24x^2","correct":true},{"latex":"12x^2","correct":false},{"latex":"3v^2","correct":false},{"latex":"6x^2","correct":false}]$json$::jsonb, $exp$$\frac{dy}{dv} = 3v^2$ y $\frac{dv}{dx} = 2$: producto $6v^2 = 6(2x)^2 = 24x^2$.$exp$),
  ($id$derb-h-22$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$hard$diff$, $prompt$Deriva: $f(x) = \sin^3 x$$prompt$, $json$[{"latex":"3 \\sin^2 x \\cos x","correct":true},{"latex":"3 \\sin^2 x","correct":false},{"latex":"\\sin^2 x \\cos x","correct":false},{"latex":"3 \\cos^2 x \\sin x","correct":false}]$json$::jsonb, $exp$Doble cadena: potencia del seno. $3(\sin x)^2 \cdot \cos x$.$exp$),
  ($id$derb-h-23$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$hard$diff$, $prompt$Deriva: $f(x) = \ln(\cos x)$$prompt$, $json$[{"latex":"-\\tan x","correct":true},{"latex":"\\frac{1}{\\cos x}","correct":false},{"latex":"\\tan x","correct":false},{"latex":"-\\frac{1}{\\cos x}","correct":false}]$json$::jsonb, $exp$Cadena con X: $\frac{-\sin x}{\cos x} = -\tan x$.$exp$),
  ($id$derb-f-24$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$easy$diff$, $prompt$Si $\frac{dx}{dy} = 2$, ¿cuánto vale $\frac{dy}{dx}$?$prompt$, $json$[{"latex":"\\frac{1}{2}","correct":true},{"latex":"2","correct":false},{"latex":"-2","correct":false},{"latex":"0","correct":false}]$json$::jsonb, $exp$Fórmula IX: $\frac{dy}{dx} = \frac{1}{2}$.$exp$),
  ($id$derb-f-25$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$easy$diff$, $prompt$Si $x = y^3$, ¿cuánto vale $\frac{dy}{dx}$?$prompt$, $json$[{"latex":"\\frac{1}{3y^2}","correct":true},{"latex":"3y^2","correct":false},{"latex":"\\frac{1}{y^2}","correct":false},{"latex":"y^2","correct":false}]$json$::jsonb, $exp$$\frac{dx}{dy} = 3y^2$; por la fórmula IX: $\frac{dy}{dx} = \frac{1}{3y^2}$.$exp$),
  ($id$derb-f-26$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$easy$diff$, $prompt$¿Cuál es la fórmula IX (derivación de la función inversa)?$prompt$, $json$[{"latex":"\\frac{dy}{dx} = \\frac{1}{\\frac{dx}{dy}}","correct":true},{"latex":"\\frac{dy}{dx} = \\frac{dx}{dy}","correct":false},{"latex":"\\frac{dy}{dx} = -\\frac{dx}{dy}","correct":false},{"latex":"\\frac{dy}{dx} = \\frac{dx}{dy} \\cdot \\frac{dy}{dx}","correct":false}]$json$::jsonb, $exp$La derivada de la función inversa es el recíproco de la derivada directa.$exp$),
  ($id$derb-m-24$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$medium$diff$, $prompt$Si $x = 2y + 1$, ¿cuánto vale $\frac{dy}{dx}$?$prompt$, $json$[{"latex":"\\frac{1}{2}","correct":true},{"latex":"2","correct":false},{"latex":"1","correct":false},{"latex":"\\frac{1}{2y + 1}","correct":false}]$json$::jsonb, $exp$$\frac{dx}{dy} = 2$; recíproco: $\frac{1}{2}$.$exp$),
  ($id$derb-m-25$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$medium$diff$, $prompt$Si $x = y^2$ con $y > 0$, ¿cuánto vale $\frac{dy}{dx}$?$prompt$, $json$[{"latex":"\\frac{1}{2y}","correct":true},{"latex":"2y","correct":false},{"latex":"\\frac{1}{y}","correct":false},{"latex":"\\frac{1}{2x}","correct":false}]$json$::jsonb, $exp$$\frac{dx}{dy} = 2y$; por IX: $\frac{dy}{dx} = \frac{1}{2y}$. (Coincide con derivar $y = \sqrt{x}$.)$exp$),
  ($id$derb-m-26$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$medium$diff$, $prompt$Si $x = \sin y$, ¿cuánto vale $\frac{dy}{dx}$?$prompt$, $json$[{"latex":"\\frac{1}{\\cos y}","correct":true},{"latex":"\\cos y","correct":false},{"latex":"-\\frac{1}{\\cos y}","correct":false},{"latex":"\\frac{1}{\\sin y}","correct":false}]$json$::jsonb, $exp$$\frac{dx}{dy} = \cos y$; por IX: $\frac{dy}{dx} = \frac{1}{\cos y} = \sec y$. Así se deriva $\arcsin x$.$exp$),
  ($id$derb-h-24$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$hard$diff$, $prompt$Si $x = e^y$, ¿cuánto vale $\frac{dy}{dx}$?$prompt$, $json$[{"latex":"e^{-y}","correct":true},{"latex":"e^y","correct":false},{"latex":"\\frac{1}{y}","correct":false},{"latex":"-e^y","correct":false}]$json$::jsonb, $exp$$\frac{dx}{dy} = e^y$; por IX: $\frac{dy}{dx} = \frac{1}{e^y} = e^{-y}$. Así se deriva $\ln x$.$exp$),
  ($id$derb-h-25$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$hard$diff$, $prompt$Si $x = y^3 + y$ y $y = 1$, ¿cuánto vale $\frac{dy}{dx}$?$prompt$, $json$[{"latex":"\\frac{1}{4}","correct":true},{"latex":"4","correct":false},{"latex":"\\frac{1}{3}","correct":false},{"latex":"\\frac{1}{2}","correct":false}]$json$::jsonb, $exp$$\frac{dx}{dy} = 3y^2 + 1 = 4$ en $y = 1$; por IX: $\frac{dy}{dx} = \frac{1}{4}$.$exp$),
  ($id$derb-h-26$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$hard$diff$, $prompt$Si $x = y + e^y$ y $y = 0$, ¿cuánto vale $\frac{dy}{dx}$?$prompt$, $json$[{"latex":"\\frac{1}{2}","correct":true},{"latex":"2","correct":false},{"latex":"1","correct":false},{"latex":"\\frac{1}{e}","correct":false}]$json$::jsonb, $exp$$\frac{dx}{dy} = 1 + e^y = 2$ en $y = 0$; por IX: $\frac{dy}{dx} = \frac{1}{2}$.$exp$),
  ($id$derl-f-01$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$easy$diff$, $prompt$Deriva: $f(x) = e^x$$prompt$, $json$[{"latex":"e^x","correct":true},{"latex":"x e^{x-1}","correct":false},{"latex":"\\ln x","correct":false},{"latex":"e","correct":false}]$json$::jsonb, $exp$Fórmula XIa con $v = x$: $e^x$ es la única función igual a su propia derivada.$exp$),
  ($id$derl-f-02$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$easy$diff$, $prompt$Deriva: $f(x) = 2^x$$prompt$, $json$[{"latex":"2^x \\ln 2","correct":true},{"latex":"x \\cdot 2^{x-1}","correct":false},{"latex":"2^x","correct":false},{"latex":"\\frac{2^x}{x}","correct":false}]$json$::jsonb, $exp$Fórmula XI con base $a = 2$: aparece el factor $\ln 2$.$exp$),
  ($id$derl-f-03$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$easy$diff$, $prompt$¿Qué función es igual a su propia derivada?$prompt$, $json$[{"latex":"f(x) = e^x","correct":true},{"latex":"f(x) = x^e","correct":false},{"latex":"f(x) = \\ln x","correct":false},{"latex":"f(x) = x^x","correct":false}]$json$::jsonb, $exp$$\frac{d}{dx}(e^x) = e^x$: por eso $e$ es la base natural. $x^e$ es una potencia y $\ln x$ deriva $\frac{1}{x}$.$exp$),
  ($id$derl-f-04$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$easy$diff$, $prompt$¿Cuál es la fórmula XI para $\frac{d}{dx}(a^v)$?$prompt$, $json$[{"latex":"a^v \\ln a \\cdot \\frac{dv}{dx}","correct":true},{"latex":"v a^{v-1} \\frac{da}{dx}","correct":false},{"latex":"a^v \\cdot \\frac{dv}{dx}","correct":false},{"latex":"\\frac{a^v}{\\ln a} \\cdot \\frac{dv}{dx}","correct":false}]$json$::jsonb, $exp$La exponencial se queda y se multiplica por $\ln a$ y por la derivada del exponente.$exp$),
  ($id$derl-m-01$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$medium$diff$, $prompt$Deriva: $f(x) = 3^x$$prompt$, $json$[{"latex":"3^x \\ln 3","correct":true},{"latex":"x \\cdot 3^{x-1}","correct":false},{"latex":"3^x","correct":false},{"latex":"\\frac{3^x}{\\ln 3}","correct":false}]$json$::jsonb, $exp$Fórmula XI: $a^v \ln a \cdot \frac{dv}{dx} = 3^x \ln 3 \cdot 1$.$exp$),
  ($id$derl-m-02$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$medium$diff$, $prompt$Deriva: $f(x) = 2e^x$$prompt$, $json$[{"latex":"2e^x","correct":true},{"latex":"2x e^x","correct":false},{"latex":"e^x","correct":false},{"latex":"2e","correct":false}]$json$::jsonb, $exp$Constante por función (IV) + XIa: $2 \cdot e^x = 2e^x$.$exp$),
  ($id$derl-m-03$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$medium$diff$, $prompt$¿Cuál es la diferencia entre derivar $x^2$ y $2^x$?$prompt$, $json$[{"latex":"x^2 \\text{ usa potencia (VIa); } 2^x \\text{ usa exponencial (XI)}","correct":true},{"latex":"\\text{Ambas usan la regla de la potencia}","correct":false},{"latex":"\\text{Ambas usan la fórmula XI}","correct":false},{"latex":"x^2 \\text{ usa exponencial; } 2^x \\text{ usa potencia}","correct":false}]$json$::jsonb, $exp$En $x^2$ la base es variable (potencia): $2x$. En $2^x$ el exponente es variable (exponencial): $2^x \ln 2$.$exp$),
  ($id$derl-h-01$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$hard$diff$, $prompt$Deriva: $f(x) = e^{x^2}$$prompt$, $json$[{"latex":"2x e^{x^2}","correct":true},{"latex":"e^{x^2}","correct":false},{"latex":"x^2 e^{x^2 - 1}","correct":false},{"latex":"2 e^{x^2}","correct":false}]$json$::jsonb, $exp$XIa con cadena: $e^{x^2} \cdot (x^2)' = 2x e^{x^2}$.$exp$),
  ($id$derl-h-02$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$hard$diff$, $prompt$Deriva: $f(x) = e^{-x}$$prompt$, $json$[{"latex":"-e^{-x}","correct":true},{"latex":"e^{-x}","correct":false},{"latex":"-x e^{-x-1}","correct":false},{"latex":"\\frac{1}{e^x} \\ln(-x)","correct":false}]$json$::jsonb, $exp$XIa con cadena: $e^{-x} \cdot (-1) = -e^{-x}$.$exp$),
  ($id$derl-h-03$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$hard$diff$, $prompt$Deriva: $f(x) = e^x + x^e$$prompt$, $json$[{"latex":"e^x + e x^{e-1}","correct":true},{"latex":"e^x + x^e \\ln x","correct":false},{"latex":"e^x + e x^e","correct":false},{"latex":"e^x + e^x","correct":false}]$json$::jsonb, $exp$$e^x$ es exponencial (XIa): deriva $e^x$. $x^e$ es potencia de $x$ con exponente constante (VIa): $e x^{e-1}$.$exp$),
  ($id$derl-f-05$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$easy$diff$, $prompt$Deriva: $f(x) = \ln x$$prompt$, $json$[{"latex":"\\frac{1}{x}","correct":true},{"latex":"\\ln x","correct":false},{"latex":"\\frac{1}{x^2}","correct":false},{"latex":"e^x","correct":false}]$json$::jsonb, $exp$Fórmula X con $v = x$: $\frac{1}{x}$.$exp$),
  ($id$derl-f-06$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$easy$diff$, $prompt$Deriva: $f(x) = \ln 5$$prompt$, $json$[{"latex":"0","correct":true},{"latex":"\\frac{1}{5}","correct":false},{"latex":"\\ln 5","correct":false},{"latex":"\\frac{1}{x}","correct":false}]$json$::jsonb, $exp$$\ln 5$ es una constante: se usa la fórmula I, no la X. Deriva 0.$exp$),
  ($id$derl-f-07$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$easy$diff$, $prompt$¿Cuál es la fórmula X para $\frac{d}{dx}(\ln v)$?$prompt$, $json$[{"latex":"\\frac{\\frac{dv}{dx}}{v}","correct":true},{"latex":"v \\cdot \\frac{dv}{dx}","correct":false},{"latex":"\\frac{v}{\\frac{dv}{dx}}","correct":false},{"latex":"\\ln v \\cdot \\frac{dv}{dx}","correct":false}]$json$::jsonb, $exp$La derivada del argumento va en el numerador y el argumento en el denominador.$exp$),
  ($id$derl-m-04$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$medium$diff$, $prompt$Deriva: $f(x) = \ln(3x)$$prompt$, $json$[{"latex":"\\frac{1}{x}","correct":true},{"latex":"\\frac{1}{3x}","correct":false},{"latex":"\\frac{3}{x}","correct":false},{"latex":"\\frac{1}{3}","correct":false}]$json$::jsonb, $exp$Fórmula X con cadena: $\frac{(3x)'}{3x} = \frac{3}{3x} = \frac{1}{x}$.$exp$),
  ($id$derl-m-05$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$medium$diff$, $prompt$Deriva: $f(x) = \ln(x^2)$$prompt$, $json$[{"latex":"\\frac{2}{x}","correct":true},{"latex":"\\frac{1}{x^2}","correct":false},{"latex":"\\frac{2x}{x}","correct":false},{"latex":"\\frac{1}{2x}","correct":false}]$json$::jsonb, $exp$Fórmula X con cadena: $\frac{2x}{x^2} = \frac{2}{x}$.$exp$),
  ($id$derl-m-06$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$medium$diff$, $prompt$Deriva: $f(x) = \log x$$prompt$, $json$[{"latex":"\\frac{1}{x \\ln 10}","correct":true},{"latex":"\\frac{1}{x}","correct":false},{"latex":"\\frac{\\ln 10}{x}","correct":false},{"latex":"\\frac{1}{10x}","correct":false}]$json$::jsonb, $exp$Fórmula Xa: $\frac{\log e}{x}$, y como $\log e = \frac{1}{\ln 10}$, queda $\frac{1}{x \ln 10}$.$exp$),
  ($id$derl-m-07$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$medium$diff$, $prompt$¿Qué regla usas para derivar $f(x) = \log x$ (logaritmo decimal)?$prompt$, $json$[{"latex":"\\text{Logaritmo decimal (Xa)}","correct":true},{"latex":"\\text{Logaritmo natural (X), sin más}","correct":false},{"latex":"\\text{Regla de la potencia (VIa)}","correct":false},{"latex":"\\text{Exponencial base } a \\text{ (XI)}","correct":false}]$json$::jsonb, $exp$Para base 10 aplica la fórmula Xa: $\frac{d}{dx}(\log x) = \frac{\log e}{x} = \frac{1}{x \ln 10}$.$exp$),
  ($id$derl-h-04$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$hard$diff$, $prompt$Deriva: $f(x) = \ln(x^2 + 1)$$prompt$, $json$[{"latex":"\\frac{2x}{x^2 + 1}","correct":true},{"latex":"\\frac{1}{x^2 + 1}","correct":false},{"latex":"\\frac{x}{x^2 + 1}","correct":false},{"latex":"2x \\ln(x^2 + 1)","correct":false}]$json$::jsonb, $exp$Fórmula X con cadena: $\frac{(x^2+1)'}{x^2+1} = \frac{2x}{x^2+1}$.$exp$),
  ($id$derl-h-05$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$hard$diff$, $prompt$Deriva: $f(x) = \ln(\sin x)$$prompt$, $json$[{"latex":"\\cot x","correct":true},{"latex":"\\frac{1}{\\sin x}","correct":false},{"latex":"\\tan x","correct":false},{"latex":"\\cos x","correct":false}]$json$::jsonb, $exp$Fórmula X con cadena: $\frac{\cos x}{\sin x} = \cot x$.$exp$),
  ($id$derl-h-06$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$hard$diff$, $prompt$Deriva: $f(x) = \log_2 x$$prompt$, $json$[{"latex":"\\frac{1}{x \\ln 2}","correct":true},{"latex":"\\frac{1}{x}","correct":false},{"latex":"\\frac{\\ln 2}{x}","correct":false},{"latex":"\\frac{1}{2x}","correct":false}]$json$::jsonb, $exp$Fórmula Xa generalizada: $\frac{d}{dx}(\log_a x) = \frac{1}{x \ln a}$. Con $a = 2$: $\frac{1}{x \ln 2}$.$exp$),
  ($id$derl-f-08$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$easy$diff$, $prompt$¿Qué regla usas para derivar $f(x) = x^x$?$prompt$, $json$[{"latex":"\\text{Derivación logarítmica (XII)}","correct":true},{"latex":"\\text{Regla de la potencia (VIa)}","correct":false},{"latex":"\\text{Exponencial natural (XIa)}","correct":false},{"latex":"\\text{Regla del producto (V)}","correct":false}]$json$::jsonb, $exp$Base $x$ y exponente $x$: ambos dependen de $x$. No es potencia ni exponencial pura.$exp$),
  ($id$derl-f-09$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$easy$diff$, $prompt$En la fórmula XII, si $v$ es constante, ¿en qué se reduce?$prompt$, $json$[{"latex":"v u^{v-1} \\frac{du}{dx} \\text{ (regla de la potencia general, VI)}","correct":true},{"latex":"\\ln u \\cdot u^v \\frac{dv}{dx}","correct":false},{"latex":"0","correct":false},{"latex":"u^v","correct":false}]$json$::jsonb, $exp$Si $v$ es constante, $\frac{dv}{dx} = 0$ y el segundo término desaparece: queda la potencia.$exp$),
  ($id$derl-f-10$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$easy$diff$, $prompt$¿Cuándo se usa la derivación logarítmica (fórmula XII)?$prompt$, $json$[{"latex":"\\text{Cuando la base y el exponente son funciones de } x","correct":true},{"latex":"\\text{Siempre que aparezca un logaritmo}","correct":false},{"latex":"\\text{Cuando la base es constante}","correct":false},{"latex":"\\text{Cuando el exponente es constante}","correct":false}]$json$::jsonb, $exp$Si el exponente es constante basta la potencia (VI); si la base es constante, la exponencial (XI). La XII es para $u(x)^{v(x)}$.$exp$),
  ($id$derl-m-08$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$medium$diff$, $prompt$Deriva: $f(x) = x^x$$prompt$, $json$[{"latex":"x^x (\\ln x + 1)","correct":true},{"latex":"x \\cdot x^{x-1}","correct":false},{"latex":"x^x \\ln x","correct":false},{"latex":"x^x","correct":false}]$json$::jsonb, $exp$Con $u = v = x$: $x \cdot x^{x-1} + \ln x \cdot x^x = x^x + x^x \ln x = x^x(1 + \ln x)$.$exp$),
  ($id$derl-m-09$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$medium$diff$, $prompt$¿Qué regla usas para derivar $f(x) = (x + 1)^{\sin x}$?$prompt$, $json$[{"latex":"\\text{Derivación logarítmica (XII)}","correct":true},{"latex":"\\text{Solo potencia general (VI)}","correct":false},{"latex":"\\text{Solo exponencial (XI)}","correct":false},{"latex":"\\text{Regla del cociente (VII)}","correct":false}]$json$::jsonb, $exp$Base $(x+1)$ y exponente $\sin x$: ambos dependen de $x$, así que aplica la fórmula XII.$exp$),
  ($id$derl-m-10$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$medium$diff$, $prompt$Deriva $f(x) = 2^x$ usando la fórmula XII.$prompt$, $json$[{"latex":"2^x \\ln 2","correct":true},{"latex":"x \\cdot 2^{x-1}","correct":false},{"latex":"2^x","correct":false},{"latex":"2^x \\ln x","correct":false}]$json$::jsonb, $exp$Con $u = 2$ (constante) el primer término es 0: queda $\ln 2 \cdot 2^x \cdot 1 = 2^x \ln 2$ (fórmula XI).$exp$),
  ($id$derl-h-07$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$hard$diff$, $prompt$Aplica la XII con $u = x^2$ y $v = 3$ (constante). ¿Qué resulta?$prompt$, $json$[{"latex":"6x^5","correct":true},{"latex":"3x^5 \\ln(x^2)","correct":false},{"latex":"2x^3","correct":false},{"latex":"6x^5 + \\ln(x^2) x^6","correct":false}]$json$::jsonb, $exp$Como $v' = 0$ solo queda el primer término: $3(x^2)^2 \cdot 2x = 6x^5$. Coincide con la potencia: $(x^2)^3 = x^6$.$exp$)
ON CONFLICT (id) DO UPDATE SET
  section_id  = EXCLUDED.section_id,
  subtema_id  = EXCLUDED.subtema_id,
  law_id      = EXCLUDED.law_id,
  difficulty  = EXCLUDED.difficulty,
  prompt      = EXCLUDED.prompt,
  options     = EXCLUDED.options,
  explanation = EXCLUDED.explanation,
  updated_at  = now();

-- Lote 4 (33 preguntas)
INSERT INTO public.questions (id, section_id, subtema_id, law_id, difficulty, prompt, options, explanation)
VALUES
  ($id$derl-h-08$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$hard$diff$, $prompt$¿Por qué $f(x) = x^{\sin x}$ no se deriva con la regla de la potencia?$prompt$, $json$[{"latex":"\\text{Porque el exponente } \\sin x \\text{ no es constante}","correct":true},{"latex":"\\text{Porque la base es } x","correct":false},{"latex":"\\text{Porque } \\sin x \\text{ no tiene derivada}","correct":false},{"latex":"\\text{Sí se puede: } (\\sin x) x^{\\sin x - 1}","correct":false}]$json$::jsonb, $exp$La potencia (VI) exige exponente constante. Aquí ambos varían: se necesita la fórmula XII.$exp$),
  ($id$derl-h-09$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$hard$diff$, $prompt$Deriva: $f(x) = x^e$$prompt$, $json$[{"latex":"e x^{e-1}","correct":true},{"latex":"x^e \\ln x","correct":false},{"latex":"e x^e","correct":false},{"latex":"x^e(\\ln x + e)","correct":false}]$json$::jsonb, $exp$El exponente $e$ es constante: es potencia (VIa), no derivación logarítmica. Queda $e x^{e-1}$.$exp$),
  ($id$derl-h-10$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$hard$diff$, $prompt$Deriva $f(x) = 3^{2x}$ usando la fórmula XII.$prompt$, $json$[{"latex":"3^{2x} \\ln 3 \\cdot 2","correct":true},{"latex":"2x \\cdot 3^{2x-1}","correct":false},{"latex":"3^{2x} \\ln(2x)","correct":false},{"latex":"3^{2x} \\cdot 2","correct":false}]$json$::jsonb, $exp$Con $u = 3$ constante, solo queda el segundo término: $\ln 3 \cdot 3^{2x} \cdot 2$.$exp$),
  ($id$dert-f-01$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$easy$diff$, $prompt$Deriva: $f(x) = \sin x$$prompt$, $json$[{"latex":"\\cos x","correct":true},{"latex":"-\\cos x","correct":false},{"latex":"\\sin x","correct":false},{"latex":"-\\sin x","correct":false}]$json$::jsonb, $exp$Fórmula XIII con $v = x$: la derivada del seno es el coseno.$exp$),
  ($id$dert-f-02$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$easy$diff$, $prompt$Deriva: $f(x) = \cos x$$prompt$, $json$[{"latex":"-\\sin x","correct":true},{"latex":"\\sin x","correct":false},{"latex":"\\cos x","correct":false},{"latex":"-\\cos x","correct":false}]$json$::jsonb, $exp$Fórmula XIV: la derivada del coseno es menos seno. El signo negativo es clave.$exp$),
  ($id$dert-f-03$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$easy$diff$, $prompt$Deriva: $f(x) = \tan x$$prompt$, $json$[{"latex":"\\sec^2 x","correct":true},{"latex":"\\tan^2 x","correct":false},{"latex":"\\cot x","correct":false},{"latex":"\\frac{1}{\\cos x}","correct":false}]$json$::jsonb, $exp$Fórmula XV: la derivada de la tangente es secante al cuadrado.$exp$),
  ($id$dert-f-04$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$easy$diff$, $prompt$¿Qué regla usas para derivar $f(x) = \tan x$?$prompt$, $json$[{"latex":"\\text{Derivada de la tangente (XV)}","correct":true},{"latex":"\\text{Regla del cociente (VII) obligatoriamente}","correct":false},{"latex":"\\text{Regla de la potencia (VIa)}","correct":false},{"latex":"\\text{Derivada del seno (XIII)}","correct":false}]$json$::jsonb, $exp$Fórmula directa XV: $\frac{d}{dx}(\tan x) = \sec^2 x$.$exp$),
  ($id$dert-f-05$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$easy$diff$, $prompt$¿Cuál es la fórmula XVI para $\frac{d}{dx}(\cot v)$?$prompt$, $json$[{"latex":"-\\csc^2 v \\cdot \\frac{dv}{dx}","correct":true},{"latex":"\\csc^2 v \\cdot \\frac{dv}{dx}","correct":false},{"latex":"-\\sec^2 v \\cdot \\frac{dv}{dx}","correct":false},{"latex":"\\cot^2 v \\cdot \\frac{dv}{dx}","correct":false}]$json$::jsonb, $exp$La cotangente deriva menos cosecante al cuadrado.$exp$),
  ($id$dert-m-01$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$medium$diff$, $prompt$Deriva: $f(x) = \sec x$$prompt$, $json$[{"latex":"\\sec x \\tan x","correct":true},{"latex":"\\sec^2 x","correct":false},{"latex":"\\sec x \\cot x","correct":false},{"latex":"-\\sec x \\tan x","correct":false}]$json$::jsonb, $exp$Fórmula XVII: la secante deriva secante por tangente.$exp$),
  ($id$dert-m-02$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$medium$diff$, $prompt$Deriva: $f(x) = \csc x$$prompt$, $json$[{"latex":"-\\csc x \\cot x","correct":true},{"latex":"\\csc x \\cot x","correct":false},{"latex":"-\\csc^2 x","correct":false},{"latex":"\\csc x \\tan x","correct":false}]$json$::jsonb, $exp$Fórmula XVIII: menos cosecante por cotangente.$exp$),
  ($id$dert-m-03$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$medium$diff$, $prompt$Deriva: $f(x) = \operatorname{vers} x$$prompt$, $json$[{"latex":"\\sin x","correct":true},{"latex":"-\\sin x","correct":false},{"latex":"\\cos x","correct":false},{"latex":"1 - \\cos x","correct":false}]$json$::jsonb, $exp$Fórmula XIX con $v = x$: $(1 - \cos x)' = 0 + \sin x = \sin x$.$exp$),
  ($id$dert-m-04$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$medium$diff$, $prompt$¿Cuál derivada lleva signo negativo?$prompt$, $json$[{"latex":"\\frac{d}{dx}(\\cos x)","correct":true},{"latex":"\\frac{d}{dx}(\\sin x)","correct":false},{"latex":"\\frac{d}{dx}(\\tan x)","correct":false},{"latex":"\\frac{d}{dx}(\\sec x)","correct":false}]$json$::jsonb, $exp$Fórmula XIV: $(\cos x)' = -\sin x$. Las derivadas de $\sin$, $\tan$ y $\sec$ son positivas en esa forma.$exp$),
  ($id$dert-m-05$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$medium$diff$, $prompt$¿Qué reglas usas para derivar $f(x) = \operatorname{vers} x$ (seno verso)?$prompt$, $json$[{"latex":"\\text{Derivada del verso (XIX), o escribir } 1 - \\cos x \\text{ y derivar}","correct":true},{"latex":"\\text{Solo regla de la potencia (VIa)}","correct":false},{"latex":"\\text{Regla del producto (V)}","correct":false},{"latex":"\\text{No se puede derivar}","correct":false}]$json$::jsonb, $exp$$\operatorname{vers} x = 1 - \cos x$: derivando queda $\sin x$ (fórmula XIX).$exp$),
  ($id$dert-h-01$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$hard$diff$, $prompt$Deriva: $f(x) = \sin x + \cos x$$prompt$, $json$[{"latex":"\\cos x - \\sin x","correct":true},{"latex":"\\cos x + \\sin x","correct":false},{"latex":"-\\cos x - \\sin x","correct":false},{"latex":"\\sin x - \\cos x","correct":false}]$json$::jsonb, $exp$Suma (III) con XIII y XIV: $\cos x + (-\sin x) = \cos x - \sin x$.$exp$),
  ($id$dert-h-02$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$hard$diff$, $prompt$Deriva: $f(x) = \tan x + \cot x$$prompt$, $json$[{"latex":"\\sec^2 x - \\csc^2 x","correct":true},{"latex":"\\sec^2 x + \\csc^2 x","correct":false},{"latex":"\\csc^2 x - \\sec^2 x","correct":false},{"latex":"\\sec^2 x \\cdot \\csc^2 x","correct":false}]$json$::jsonb, $exp$Fórmulas XV y XVI: $\sec^2 x + (-\csc^2 x) = \sec^2 x - \csc^2 x$.$exp$),
  ($id$dert-h-03$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$hard$diff$, $prompt$Deriva: $f(x) = 2 \sec x$$prompt$, $json$[{"latex":"2 \\sec x \\tan x","correct":true},{"latex":"2 \\sec^2 x","correct":false},{"latex":"\\sec x \\tan x","correct":false},{"latex":"2 \\tan x","correct":false}]$json$::jsonb, $exp$Constante por función (IV) + fórmula XVII: $2 \sec x \tan x$.$exp$),
  ($id$dert-h-04$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$hard$diff$, $prompt$¿Cuál es la fórmula XVII para $\frac{d}{dx}(\sec v)$?$prompt$, $json$[{"latex":"\\sec v \\tan v \\cdot \\frac{dv}{dx}","correct":true},{"latex":"\\sec^2 v \\cdot \\frac{dv}{dx}","correct":false},{"latex":"\\sec v \\cot v \\cdot \\frac{dv}{dx}","correct":false},{"latex":"-\\sec v \\tan v \\cdot \\frac{dv}{dx}","correct":false}]$json$::jsonb, $exp$La secante deriva secante por tangente, por la derivada del argumento.$exp$),
  ($id$dert-h-05$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$hard$diff$, $prompt$¿Qué fórmula del formulario corresponde a $\frac{d}{dx}(\operatorname{vers} v)$?$prompt$, $json$[{"latex":"\\sin v \\cdot \\frac{dv}{dx} \\text{ (XIX)}","correct":true},{"latex":"\\cos v \\cdot \\frac{dv}{dx} \\text{ (XIII)}","correct":false},{"latex":"-\\sin v \\cdot \\frac{dv}{dx} \\text{ (XIV)}","correct":false},{"latex":"\\sec^2 v \\cdot \\frac{dv}{dx} \\text{ (XV)}","correct":false}]$json$::jsonb, $exp$Como $\operatorname{vers} v = 1 - \cos v$, su derivada es $\sin v \cdot \frac{dv}{dx}$: fórmula XIX.$exp$),
  ($id$derti-f-01$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$easy$diff$, $prompt$Deriva: $f(x) = \arcsin x$$prompt$, $json$[{"latex":"\\frac{1}{\\sqrt{1 - x^2}}","correct":true},{"latex":"-\\frac{1}{\\sqrt{1 - x^2}}","correct":false},{"latex":"\\frac{1}{1 + x^2}","correct":false},{"latex":"\\cos x","correct":false}]$json$::jsonb, $exp$Fórmula XX con $v = x$. No es $\cos x$: la derivada no es la función inversa del coseno.$exp$),
  ($id$derti-f-02$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$easy$diff$, $prompt$Deriva: $f(x) = \arccos x$$prompt$, $json$[{"latex":"-\\frac{1}{\\sqrt{1 - x^2}}","correct":true},{"latex":"\\frac{1}{\\sqrt{1 - x^2}}","correct":false},{"latex":"-\\frac{1}{\\sqrt{1 + x^2}}","correct":false},{"latex":"\\frac{1}{1 + x^2}","correct":false}]$json$::jsonb, $exp$Fórmula XXI: igual que el arcoseno pero con signo negativo.$exp$),
  ($id$derti-f-03$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$easy$diff$, $prompt$Deriva: $f(x) = \arctan x$$prompt$, $json$[{"latex":"\\frac{1}{1 + x^2}","correct":true},{"latex":"\\frac{1}{\\sqrt{1 + x^2}}","correct":false},{"latex":"-\\frac{1}{1 + x^2}","correct":false},{"latex":"\\frac{1}{1 - x^2}","correct":false}]$json$::jsonb, $exp$Fórmula XXII con $v = x$.$exp$),
  ($id$derti-f-04$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$easy$diff$, $prompt$¿Cuál es la fórmula XXII para $\frac{d}{dx}(\arctan v)$?$prompt$, $json$[{"latex":"\\frac{\\frac{dv}{dx}}{1 + v^2}","correct":true},{"latex":"\\frac{\\frac{dv}{dx}}{\\sqrt{1 - v^2}}","correct":false},{"latex":"\\frac{\\frac{dv}{dx}}{1 - v^2}","correct":false},{"latex":"\\frac{\\frac{dv}{dx}}{v^2 + v}","correct":false}]$json$::jsonb, $exp$La arcotangente deriva $\frac{1}{1 + v^2}$ por la derivada del argumento.$exp$),
  ($id$derti-f-05$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$easy$diff$, $prompt$¿Qué regla usas para derivar $f(x) = \arcsin x$?$prompt$, $json$[{"latex":"\\text{Derivada del arcoseno (XX)}","correct":true},{"latex":"\\text{Derivada del seno (XIII)}","correct":false},{"latex":"\\text{Derivación de la función inversa (IX) directamente}","correct":false},{"latex":"\\text{Regla de la potencia (VIa)}","correct":false}]$json$::jsonb, $exp$Es una función trigonométrica inversa: se usa su fórmula directa (XX).$exp$),
  ($id$derti-m-01$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$medium$diff$, $prompt$Deriva: $f(x) = \operatorname{arccot} x$$prompt$, $json$[{"latex":"-\\frac{1}{1 + x^2}","correct":true},{"latex":"\\frac{1}{1 + x^2}","correct":false},{"latex":"-\\frac{1}{\\sqrt{1 - x^2}}","correct":false},{"latex":"\\frac{1}{x^2}","correct":false}]$json$::jsonb, $exp$Fórmula XXIII: igual que la arcotangente pero con signo negativo.$exp$),
  ($id$derti-m-02$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$medium$diff$, $prompt$Deriva: $f(x) = \operatorname{arcsec} x$ (con $x > 1$)$prompt$, $json$[{"latex":"\\frac{1}{x \\sqrt{x^2 - 1}}","correct":true},{"latex":"\\frac{1}{x \\sqrt{1 - x^2}}","correct":false},{"latex":"\\frac{1}{\\sqrt{x^2 - 1}}","correct":false},{"latex":"-\\frac{1}{x \\sqrt{x^2 - 1}}","correct":false}]$json$::jsonb, $exp$Fórmula XXIV con $v = x$: denominador $x \sqrt{x^2 - 1}$.$exp$),
  ($id$derti-m-03$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$medium$diff$, $prompt$Deriva: $f(x) = \operatorname{arccsc} x$ (con $x > 1$)$prompt$, $json$[{"latex":"-\\frac{1}{x \\sqrt{x^2 - 1}}","correct":true},{"latex":"\\frac{1}{x \\sqrt{x^2 - 1}}","correct":false},{"latex":"-\\frac{1}{\\sqrt{x^2 - 1}}","correct":false},{"latex":"\\frac{1}{x \\sqrt{1 + x^2}}","correct":false}]$json$::jsonb, $exp$Fórmula XXV con $v = x$.$exp$),
  ($id$derti-m-04$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$medium$diff$, $prompt$¿Cuál es la fórmula XXV para $\frac{d}{dx}(\operatorname{arccsc} v)$?$prompt$, $json$[{"latex":"-\\frac{\\frac{dv}{dx}}{v \\sqrt{v^2 - 1}}","correct":true},{"latex":"\\frac{\\frac{dv}{dx}}{v \\sqrt{v^2 - 1}}","correct":false},{"latex":"-\\frac{\\frac{dv}{dx}}{v \\sqrt{1 - v^2}}","correct":false},{"latex":"\\frac{\\frac{dv}{dx}}{1 + v^2}","correct":false}]$json$::jsonb, $exp$La arcocosecante deriva la expresión de la arcosecante con signo negativo.$exp$),
  ($id$derti-m-05$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$medium$diff$, $prompt$¿Qué par de derivadas difiere solo en el signo?$prompt$, $json$[{"latex":"\\arctan x \\text{ y } \\operatorname{arccot} x","correct":true},{"latex":"\\arcsin x \\text{ y } \\arctan x","correct":false},{"latex":"\\arctan x \\text{ y } \\operatorname{arcsec} x","correct":false},{"latex":"\\arcsin x \\text{ y } \\operatorname{arccsc} x","correct":false}]$json$::jsonb, $exp$$\frac{1}{1+x^2}$ contra $-\frac{1}{1+x^2}$. Lo mismo pasa con arcsen/arccos y arcsec/arccsc.$exp$),
  ($id$derti-h-01$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$hard$diff$, $prompt$Deriva: $f(x) = \arctan(x^2)$$prompt$, $json$[{"latex":"\\frac{2x}{1 + x^4}","correct":true},{"latex":"\\frac{1}{1 + x^4}","correct":false},{"latex":"\\frac{2x}{1 + 2x}","correct":false},{"latex":"\\frac{2x}{\\sqrt{1 - x^4}}","correct":false}]$json$::jsonb, $exp$Fórmula XXII con cadena: $\frac{(x^2)'}{1 + (x^2)^2} = \frac{2x}{1 + x^4}$.$exp$),
  ($id$derti-h-02$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$hard$diff$, $prompt$Deriva: $f(x) = \arcsin(2x)$$prompt$, $json$[{"latex":"\\frac{2}{\\sqrt{1 - 4x^2}}","correct":true},{"latex":"\\frac{1}{\\sqrt{1 - 4x^2}}","correct":false},{"latex":"\\frac{2}{\\sqrt{1 - 2x^2}}","correct":false},{"latex":"\\frac{2}{1 + 4x^2}","correct":false}]$json$::jsonb, $exp$Fórmula XX con cadena: $\frac{(2x)'}{\sqrt{1 - (2x)^2}} = \frac{2}{\sqrt{1 - 4x^2}}$.$exp$),
  ($id$derti-h-03$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$hard$diff$, $prompt$Deriva: $f(x) = \operatorname{arcsec}(e^x)$$prompt$, $json$[{"latex":"\\frac{1}{\\sqrt{e^{2x} - 1}}","correct":true},{"latex":"\\frac{e^x}{\\sqrt{e^{2x} - 1}}","correct":false},{"latex":"\\frac{1}{e^x \\sqrt{1 - e^{2x}}}","correct":false},{"latex":"\\frac{e^x}{e^{2x} - 1}","correct":false}]$json$::jsonb, $exp$Fórmula XXIV con cadena: $\frac{e^x}{e^x \sqrt{e^{2x} - 1}} = \frac{1}{\sqrt{e^{2x} - 1}}$.$exp$),
  ($id$derti-h-04$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$hard$diff$, $prompt$¿Cuál es la fórmula XXVI para $\frac{d}{dx}(\operatorname{arcvers} v)$?$prompt$, $json$[{"latex":"\\frac{\\frac{dv}{dx}}{\\sqrt{2v - v^2}}","correct":true},{"latex":"\\frac{\\frac{dv}{dx}}{\\sqrt{1 - v^2}}","correct":false},{"latex":"\\frac{\\frac{dv}{dx}}{\\sqrt{2v + v^2}}","correct":false},{"latex":"\\frac{\\frac{dv}{dx}}{2v - v^2}","correct":false}]$json$::jsonb, $exp$El arco verso deriva $\frac{1}{\sqrt{2v - v^2}}$ por la derivada del argumento.$exp$),
  ($id$derti-h-05$id$, $sec$calculo-diferencial$sec$, $sub$derivacion$sub$, $law$derivacion$law$, $diff$hard$diff$, $prompt$¿Qué reglas usas para derivar $f(x) = \arctan(3x + 1)$?$prompt$, $json$[{"latex":"\\text{Arcotangente (XXII) + cadena (VIII)}","correct":true},{"latex":"\\text{Solo arcotangente (XXII)}","correct":false},{"latex":"\\text{Tangente (XV) + cadena (VIII)}","correct":false},{"latex":"\\text{Cociente (VII)}","correct":false}]$json$::jsonb, $exp$El argumento no es $x$: fórmula XXII multiplicada por $(3x + 1)' = 3$. Queda $\frac{3}{1 + (3x+1)^2}$.$exp$)
ON CONFLICT (id) DO UPDATE SET
  section_id  = EXCLUDED.section_id,
  subtema_id  = EXCLUDED.subtema_id,
  law_id      = EXCLUDED.law_id,
  difficulty  = EXCLUDED.difficulty,
  prompt      = EXCLUDED.prompt,
  options     = EXCLUDED.options,
  explanation = EXCLUDED.explanation,
  updated_at  = now();
