-- =====================================================================
-- Migración Supabase: Sección 03 - Cálculo Integral (155 preguntas)
-- Total preguntas en este script: 155
-- Fecha de generación: 2026-10-08T16:01:15.347Z
-- =====================================================================

-- Tabla e índices base
CREATE TABLE IF NOT EXISTS public.questions (
  id          TEXT PRIMARY KEY,
  section_id  TEXT NOT NULL,
  subtema_id  TEXT NOT NULL,
  law_id      TEXT NOT NULL,
  difficulty  TEXT NOT NULL CHECK (difficulty IN ('easy', 'medium', 'hard')),
  prompt      TEXT NOT NULL,
  options     JSONB NOT NULL,
  explanation TEXT NOT NULL DEFAULT '',
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS questions_law_idx ON public.questions (section_id, subtema_id, law_id);

ALTER TABLE public.questions ENABLE ROW LEVEL SECURITY;

-- Políticas RLS:
-- 1. Lectura pública (permite alumnos anónimos y autenticados)
DROP POLICY IF EXISTS "questions read auth" ON public.questions;
DROP POLICY IF EXISTS "questions read all" ON public.questions;
CREATE POLICY "questions read all" ON public.questions
  FOR SELECT TO anon, authenticated USING (true);

-- 2. Escritura restringida a administradores
DROP POLICY IF EXISTS "questions admin write" ON public.questions;
CREATE POLICY "questions admin write" ON public.questions
  FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM public.profiles p WHERE p.user_id = auth.uid() AND p.is_admin))
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles p WHERE p.user_id = auth.uid() AND p.is_admin));

-- Lote 1 (50 preguntas)
INSERT INTO public.questions (id, section_id, subtema_id, law_id, difficulty, prompt, options, explanation)
VALUES
  ($id$int-f-01$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$easy$diff$, $prompt$Calcula: $\int x^2\,dx$$prompt$, $json$[{"latex":"\\frac{x^3}{3} + C","correct":true},{"latex":"\\frac{x^3}{2} + C","correct":false},{"latex":"2x + C","correct":false},{"latex":"\\frac{x^2}{2} + C","correct":false}]$json$::jsonb, $exp$Fórmula (4): $\int v^n\,dv = \frac{v^{n+1}}{n+1} + C$. Aquí $n = 2$.$exp$),
  ($id$int-f-02$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$easy$diff$, $prompt$Calcula: $\int x^3\,dx$$prompt$, $json$[{"latex":"\\frac{x^4}{4} + C","correct":true},{"latex":"3x^2 + C","correct":false},{"latex":"\\frac{x^3}{3} + C","correct":false},{"latex":"x^4 + C","correct":false}]$json$::jsonb, $exp$Fórmula (4) con $n = 3$: $\frac{x^{3+1}}{3+1} = \frac{x^4}{4} + C$.$exp$),
  ($id$int-f-03$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$easy$diff$, $prompt$Calcula: $\int x\,dx$$prompt$, $json$[{"latex":"\\frac{x^2}{2} + C","correct":true},{"latex":"x + C","correct":false},{"latex":"1 + C","correct":false},{"latex":"x^2 + C","correct":false}]$json$::jsonb, $exp$Fórmula (4) con $n = 1$: $\frac{x^{2}}{2} + C$.$exp$),
  ($id$int-f-04$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$easy$diff$, $prompt$Calcula: $\int 5\,dx$$prompt$, $json$[{"latex":"5x + C","correct":true},{"latex":"5 + C","correct":false},{"latex":"x + C","correct":false},{"latex":"\\frac{5x^2}{2} + C","correct":false}]$json$::jsonb, $exp$Fórmulas (2) y (3): $\int 5\,dx = 5 \int dx = 5x + C$.$exp$),
  ($id$int-f-05$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$easy$diff$, $prompt$Calcula: $\int 3x^2\,dx$$prompt$, $json$[{"latex":"x^3 + C","correct":true},{"latex":"3x^3 + C","correct":false},{"latex":"6x + C","correct":false},{"latex":"\\frac{3x^3}{2} + C","correct":false}]$json$::jsonb, $exp$Fórmula (2) y (4): $3 \cdot \frac{x^3}{3} = x^3 + C$.$exp$),
  ($id$int-f-06$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$easy$diff$, $prompt$Calcula: $\int \frac{1}{x}\,dx$$prompt$, $json$[{"latex":"\\ln|x| + C","correct":true},{"latex":"\\frac{1}{x^2} + C","correct":false},{"latex":"x + C","correct":false},{"latex":"-\\frac{1}{x^2} + C","correct":false}]$json$::jsonb, $exp$Fórmula (5): $\int \frac{dv}{v} = \ln|v| + C$.$exp$),
  ($id$int-f-07$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$easy$diff$, $prompt$Calcula: $\int e^x\,dx$$prompt$, $json$[{"latex":"e^x + C","correct":true},{"latex":"x e^{x-1} + C","correct":false},{"latex":"\\frac{e^x}{x} + C","correct":false},{"latex":"e + C","correct":false}]$json$::jsonb, $exp$Fórmula (7): $\int e^v\,dv = e^v + C$.$exp$),
  ($id$int-f-08$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$easy$diff$, $prompt$Calcula: $\int \sin x\,dx$$prompt$, $json$[{"latex":"-\\cos x + C","correct":true},{"latex":"\\cos x + C","correct":false},{"latex":"\\sin x + C","correct":false},{"latex":"-\\sin x + C","correct":false}]$json$::jsonb, $exp$Fórmula (8): la integral del seno es menos coseno.$exp$),
  ($id$int-f-09$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$easy$diff$, $prompt$Calcula: $\int \cos x\,dx$$prompt$, $json$[{"latex":"\\sin x + C","correct":true},{"latex":"-\\sin x + C","correct":false},{"latex":"\\cos x + C","correct":false},{"latex":"-\\cos x + C","correct":false}]$json$::jsonb, $exp$Fórmula (9): la integral del coseno es el seno.$exp$),
  ($id$int-f-10$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$easy$diff$, $prompt$Calcula: $\int \sec^2 x\,dx$$prompt$, $json$[{"latex":"\\tan x + C","correct":true},{"latex":"\\sec x + C","correct":false},{"latex":"-\\cot x + C","correct":false},{"latex":"\\sec^2 x + C","correct":false}]$json$::jsonb, $exp$Fórmula (10): $\int \sec^2 v\,dv = \tan v + C$.$exp$),
  ($id$int-f-11$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$easy$diff$, $prompt$Calcula: $\int \csc^2 x\,dx$$prompt$, $json$[{"latex":"-\\cot x + C","correct":true},{"latex":"\\cot x + C","correct":false},{"latex":"-\\csc x + C","correct":false},{"latex":"\\tan x + C","correct":false}]$json$::jsonb, $exp$Fórmula (11): $\int \csc^2 v\,dv = -\cot v + C$.$exp$),
  ($id$int-f-12$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$easy$diff$, $prompt$Calcula: $\int \sec x \tan x\,dx$$prompt$, $json$[{"latex":"\\sec x + C","correct":true},{"latex":"\\tan x + C","correct":false},{"latex":"-\\sec x + C","correct":false},{"latex":"\\csc x + C","correct":false}]$json$::jsonb, $exp$Fórmula (12): $\int \sec v \tan v\,dv = \sec v + C$.$exp$),
  ($id$int-f-13$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$easy$diff$, $prompt$Calcula: $\int \csc x \cot x\,dx$$prompt$, $json$[{"latex":"-\\csc x + C","correct":true},{"latex":"\\csc x + C","correct":false},{"latex":"-\\cot x + C","correct":false},{"latex":"\\cot x + C","correct":false}]$json$::jsonb, $exp$Fórmula (13): $\int \csc v \cot v\,dv = -\csc v + C$.$exp$),
  ($id$int-f-14$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$easy$diff$, $prompt$Calcula: $\int 2^x\,dx$$prompt$, $json$[{"latex":"\\frac{2^x}{\\ln 2} + C","correct":true},{"latex":"2^x + C","correct":false},{"latex":"x\\,2^{x-1} + C","correct":false},{"latex":"2^x \\ln 2 + C","correct":false}]$json$::jsonb, $exp$Fórmula (6): $\int a^v\,dv = \frac{a^v}{\ln a} + C$.$exp$),
  ($id$int-f-15$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$easy$diff$, $prompt$¿Qué fórmula (1–23) usas para $\int x^5\,dx$?$prompt$, $json$[{"latex":"\\text{(4) Potencia } \\int v^n\\,dv","correct":true},{"latex":"\\text{(5) Recíproco } \\int \\frac{dv}{v}","correct":false},{"latex":"\\text{(7) Exponencial } \\int e^v\\,dv","correct":false},{"latex":"\\text{(8) Seno } \\int \\sin v\\,dv","correct":false}]$json$::jsonb, $exp$Es una potencia de $x$: aplica la fórmula (4) con $n = 5$.$exp$),
  ($id$int-f-16$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$easy$diff$, $prompt$¿Qué fórmula (1–23) usas para $\int \frac{1}{x}\,dx$?$prompt$, $json$[{"latex":"\\text{(5) Recíproco } \\int \\frac{dv}{v}","correct":true},{"latex":"\\text{(4) Potencia } \\int v^n\\,dv","correct":false},{"latex":"\\text{(3) } \\int dx","correct":false},{"latex":"\\text{(6) Exponencial base } a","correct":false}]$json$::jsonb, $exp$$\frac{1}{x}$ es el recíproco de la variable: fórmula (5), $\ln|x| + C$.$exp$),
  ($id$int-f-17$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$easy$diff$, $prompt$¿Qué fórmula (1–23) usas para $\int \cos x\,dx$?$prompt$, $json$[{"latex":"\\text{(9) Coseno } \\int \\cos v\\,dv","correct":true},{"latex":"\\text{(8) Seno } \\int \\sin v\\,dv","correct":false},{"latex":"\\text{(10) } \\int \\sec^2 v\\,dv","correct":false},{"latex":"\\text{(14) } \\int \\tan v\\,dv","correct":false}]$json$::jsonb, $exp$La integral directa del coseno es la fórmula (9): $\sin x + C$.$exp$),
  ($id$int-f-18$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$easy$diff$, $prompt$Calcula: $\int (x^2 + x)\,dx$$prompt$, $json$[{"latex":"\\frac{x^3}{3} + \\frac{x^2}{2} + C","correct":true},{"latex":"x^3 + x^2 + C","correct":false},{"latex":"2x + 1 + C","correct":false},{"latex":"\\frac{x^3}{3} + x + C","correct":false}]$json$::jsonb, $exp$Fórmula (1): se integra término a término.$exp$),
  ($id$int-f-19$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$easy$diff$, $prompt$Calcula: $\int (\sin x + \cos x)\,dx$$prompt$, $json$[{"latex":"-\\cos x + \\sin x + C","correct":true},{"latex":"\\cos x + \\sin x + C","correct":false},{"latex":"-\\cos x - \\sin x + C","correct":false},{"latex":"\\cos x - \\sin x + C","correct":false}]$json$::jsonb, $exp$Fórmulas (1), (8) y (9): $-\cos x + \sin x + C$.$exp$),
  ($id$int-f-20$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$easy$diff$, $prompt$Calcula: $\int 7x^6\,dx$$prompt$, $json$[{"latex":"x^7 + C","correct":true},{"latex":"7x^7 + C","correct":false},{"latex":"\\frac{7x^7}{6} + C","correct":false},{"latex":"42x^5 + C","correct":false}]$json$::jsonb, $exp$Fórmulas (2) y (4): $7 \cdot \frac{x^7}{7} = x^7 + C$.$exp$),
  ($id$int-f-21$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$easy$diff$, $prompt$¿Cuál es la fórmula de la potencia (4)?$prompt$, $json$[{"latex":"\\int v^n\\,dv = \\frac{v^{n+1}}{n+1} + C","correct":true},{"latex":"\\int v^n\\,dv = n v^{n-1} + C","correct":false},{"latex":"\\int v^n\\,dv = \\frac{v^{n}}{n} + C","correct":false},{"latex":"\\int v^n\\,dv = v^{n} + C","correct":false}]$json$::jsonb, $exp$Se suma 1 al exponente y se divide entre el nuevo exponente.$exp$),
  ($id$int-f-22$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$easy$diff$, $prompt$Calcula: $\int dx$$prompt$, $json$[{"latex":"x + C","correct":true},{"latex":"1 + C","correct":false},{"latex":"x^2 + C","correct":false},{"latex":"\\frac{x^2}{2} + C","correct":false}]$json$::jsonb, $exp$Fórmula (3): $\int dx = x + C$.$exp$),
  ($id$int-f-23$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$easy$diff$, $prompt$Calcula: $\int 4x^3\,dx$$prompt$, $json$[{"latex":"x^4 + C","correct":true},{"latex":"4x^4 + C","correct":false},{"latex":"12x^2 + C","correct":false},{"latex":"\\frac{4x^4}{3} + C","correct":false}]$json$::jsonb, $exp$Fórmulas (2) y (4): $4 \cdot \frac{x^4}{4} = x^4 + C$.$exp$),
  ($id$int-f-24$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$easy$diff$, $prompt$¿Qué fórmula (1–23) usas para $\int \tan x\,dx$?$prompt$, $json$[{"latex":"\\text{(14) } \\int \\tan v\\,dv","correct":true},{"latex":"\\text{(10) } \\int \\sec^2 v\\,dv","correct":false},{"latex":"\\text{(12) } \\int \\sec v \\tan v\\,dv","correct":false},{"latex":"\\text{(15) } \\int \\cot v\\,dv","correct":false}]$json$::jsonb, $exp$La tangente no es directa: se usa la fórmula (14), $-\ln|\cos v| + C$.$exp$),
  ($id$int-f-25$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$easy$diff$, $prompt$Calcula: $\int \cot x\,dx$$prompt$, $json$[{"latex":"\\ln|\\sin x| + C","correct":true},{"latex":"-\\ln|\\cos x| + C","correct":false},{"latex":"\\ln|\\cos x| + C","correct":false},{"latex":"-\\ln|\\sin x| + C","correct":false}]$json$::jsonb, $exp$Fórmula (15): $\int \cot v\,dv = \ln|\sin v| + C$.$exp$),
  ($id$int-f-26$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$easy$diff$, $prompt$Calcula: $\int \sec x\,dx$$prompt$, $json$[{"latex":"\\ln|\\sec x + \\tan x| + C","correct":true},{"latex":"\\sec x \\tan x + C","correct":false},{"latex":"\\ln|\\sec x| + C","correct":false},{"latex":"-\\ln|\\sec x - \\tan x| + C","correct":false}]$json$::jsonb, $exp$Fórmula (16): $\int \sec v\,dv = \ln|\sec v + \tan v| + C$.$exp$),
  ($id$int-f-27$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$easy$diff$, $prompt$Calcula: $\int \csc x\,dx$$prompt$, $json$[{"latex":"\\ln|\\csc x - \\cot x| + C","correct":true},{"latex":"\\ln|\\csc x + \\cot x| + C","correct":false},{"latex":"-\\csc x + C","correct":false},{"latex":"\\ln|\\csc x| + C","correct":false}]$json$::jsonb, $exp$Fórmula (17): $\int \csc v\,dv = \ln|\csc v - \cot v| + C$.$exp$),
  ($id$int-f-28$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$easy$diff$, $prompt$¿Qué fórmula (1–23) usas para $\int \frac{dx}{x^2 + 1}$?$prompt$, $json$[{"latex":"\\text{(18) } \\int \\frac{dv}{v^2 + a^2}","correct":true},{"latex":"\\text{(19) } \\int \\frac{dv}{v^2 - a^2}","correct":false},{"latex":"\\text{(20) } \\int \\frac{dv}{\\sqrt{a^2 - v^2}}","correct":false},{"latex":"\\text{(21) } \\int \\frac{dv}{\\sqrt{v^2 \\pm a^2}}","correct":false}]$json$::jsonb, $exp$Tiene la forma $v^2 + a^2$ con $v = x$ y $a = 1$: fórmula (18).$exp$),
  ($id$int-f-29$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$easy$diff$, $prompt$Calcula: $\int \frac{dx}{x^2 + 1}$$prompt$, $json$[{"latex":"\\arctan x + C","correct":true},{"latex":"\\ln(x^2 + 1) + C","correct":false},{"latex":"\\arcsin x + C","correct":false},{"latex":"-\\frac{1}{x} + C","correct":false}]$json$::jsonb, $exp$Fórmula (18) con $a = 1$: $\frac{1}{1}\arctan\frac{x}{1} + C$.$exp$),
  ($id$int-f-30$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$easy$diff$, $prompt$Calcula: $\int \frac{dx}{\sqrt{1 - x^2}}$$prompt$, $json$[{"latex":"\\arcsin x + C","correct":true},{"latex":"\\arccos x + C","correct":false},{"latex":"\\ln|x + \\sqrt{1-x^2}| + C","correct":false},{"latex":"\\arctan x + C","correct":false}]$json$::jsonb, $exp$Fórmula (20) con $a = 1$: $\arcsin\frac{x}{1} + C$.$exp$),
  ($id$int-m-01$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$medium$diff$, $prompt$Calcula: $\int 5x^4\,dx$$prompt$, $json$[{"latex":"x^5 + C","correct":true},{"latex":"5x^5 + C","correct":false},{"latex":"20x^3 + C","correct":false},{"latex":"\\frac{5x^5}{4} + C","correct":false}]$json$::jsonb, $exp$Fórmulas (2) y (4): $5 \cdot \frac{x^5}{5} = x^5 + C$.$exp$),
  ($id$int-m-02$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$medium$diff$, $prompt$¿Qué sustitución $u$ resuelve $\int 2x\,e^{x^2}\,dx$?$prompt$, $json$[{"latex":"u = x^2","correct":true},{"latex":"u = e^{x^2}","correct":false},{"latex":"u = 2x","correct":false},{"latex":"u = x","correct":false}]$json$::jsonb, $exp$Si $u = x^2$, entonces $du = 2x\,dx$, que coincide con el factor presente.$exp$),
  ($id$int-m-03$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$medium$diff$, $prompt$Calcula: $\int (x^2 + 1)^5 \cdot 2x\,dx$$prompt$, $json$[{"latex":"\\frac{(x^2 + 1)^6}{6} + C","correct":true},{"latex":"\\frac{(x^2 + 1)^6}{2} + C","correct":false},{"latex":"(x^2 + 1)^6 + C","correct":false},{"latex":"10(x^2 + 1)^4 + C","correct":false}]$json$::jsonb, $exp$Con $u = x^2 + 1$, $du = 2x\,dx$: fórmula (4), $\frac{u^6}{6} + C$.$exp$),
  ($id$int-m-04$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$medium$diff$, $prompt$Calcula: $\int 2x\,e^{x^2}\,dx$$prompt$, $json$[{"latex":"e^{x^2} + C","correct":true},{"latex":"e^{x^2} + x e^{x^2} + C","correct":false},{"latex":"x^2 e^{x^2} + C","correct":false},{"latex":"2 e^{x^2} + C","correct":false}]$json$::jsonb, $exp$Con $u = x^2$, $du = 2x\,dx$: $\int e^u\,du = e^{x^2} + C$ (fórmula 7).$exp$),
  ($id$int-m-05$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$medium$diff$, $prompt$Calcula: $\int x\,e^{x^2}\,dx$$prompt$, $json$[{"latex":"\\frac{1}{2}e^{x^2} + C","correct":true},{"latex":"e^{x^2} + C","correct":false},{"latex":"x e^{x^2} + C","correct":false},{"latex":"\\frac{1}{2}x e^{x^2} + C","correct":false}]$json$::jsonb, $exp$Con $u = x^2$, $du = 2x\,dx$, falta un $2$: $\frac{1}{2}\int e^u\,du = \frac{1}{2}e^{x^2} + C$.$exp$),
  ($id$int-m-06$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$medium$diff$, $prompt$Calcula: $\int \frac{dx}{3x}$$prompt$, $json$[{"latex":"\\frac{1}{3}\\ln|x| + C","correct":true},{"latex":"\\ln|x| + C","correct":false},{"latex":"3\\ln|x| + C","correct":false},{"latex":"\\ln|3x| + C","correct":false}]$json$::jsonb, $exp$Fórmula (2) y (5): $\frac{1}{3}\int\frac{dx}{x} = \frac{1}{3}\ln|x| + C$.$exp$),
  ($id$int-m-07$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$medium$diff$, $prompt$Calcula: $\int \frac{2x}{x^2 + 1}\,dx$$prompt$, $json$[{"latex":"\\ln(x^2 + 1) + C","correct":true},{"latex":"\\ln|x| + C","correct":false},{"latex":"\\frac{1}{x^2+1} + C","correct":false},{"latex":"2\\ln(x^2+1) + C","correct":false}]$json$::jsonb, $exp$Con $u = x^2 + 1$, $du = 2x\,dx$: $\int\frac{du}{u} = \ln|u| + C$ (fórmula 5).$exp$),
  ($id$int-m-08$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$medium$diff$, $prompt$Calcula: $\int x\,\sin(x^2)\,dx$$prompt$, $json$[{"latex":"-\\frac{1}{2}\\cos(x^2) + C","correct":true},{"latex":"\\frac{1}{2}\\cos(x^2) + C","correct":false},{"latex":"-\\cos(x^2) + C","correct":false},{"latex":"\\cos(x^2) + C","correct":false}]$json$::jsonb, $exp$Con $u = x^2$, $du = 2x\,dx$: $\frac{1}{2}\int\sin u\,du = -\frac{1}{2}\cos(x^2) + C$.$exp$),
  ($id$int-m-09$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$medium$diff$, $prompt$¿La integral $\int (x^2 + 1)^2\,dx$ se resuelve directamente con la fórmula (4)?$prompt$, $json$[{"latex":"\\text{No: falta el factor } \\frac{d}{dx}(x^2+1) = 2x","correct":true},{"latex":"\\text{Sí, directamente con } n = 2","correct":false},{"latex":"\\text{Sí, con } n = 1","correct":false},{"latex":"\\text{No existe tal integral}","correct":false}]$json$::jsonb, $exp$La fórmula (4) requiere la forma $v^n\,dv$; aquí $dv = 2x\,dx$ no aparece. Habría que expandir.$exp$),
  ($id$int-m-10$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$medium$diff$, $prompt$¿Qué fórmula y sustitución usas para $\int x\,\cos(x^2)\,dx$?$prompt$, $json$[{"latex":"\\text{(9) con } v = x^2","correct":true},{"latex":"\\text{(9) con } v = x","correct":false},{"latex":"\\text{(8) con } v = x^2","correct":false},{"latex":"\\text{(4) con } v = x^2","correct":false}]$json$::jsonb, $exp$Con $v = x^2$, $dv = 2x\,dx$: $\frac{1}{2}\int\cos v\,dv$ → fórmula (9).$exp$),
  ($id$int-m-11$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$medium$diff$, $prompt$Calcula: $\int \tan x\,dx$$prompt$, $json$[{"latex":"-\\ln|\\cos x| + C","correct":true},{"latex":"\\ln|\\sin x| + C","correct":false},{"latex":"\\sec^2 x + C","correct":false},{"latex":"-\\ln|\\sin x| + C","correct":false}]$json$::jsonb, $exp$Fórmula (14): $\int \tan v\,dv = -\ln|\cos v| + C$.$exp$),
  ($id$int-m-12$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$medium$diff$, $prompt$Calcula: $\int \frac{dx}{x^2 + 4}$$prompt$, $json$[{"latex":"\\frac{1}{2}\\arctan\\frac{x}{2} + C","correct":true},{"latex":"\\arctan\\frac{x}{2} + C","correct":false},{"latex":"\\frac{1}{4}\\arctan x + C","correct":false},{"latex":"\\ln(x^2 + 4) + C","correct":false}]$json$::jsonb, $exp$Fórmula (18) con $a = 2$: $\frac{1}{2}\arctan\frac{x}{2} + C$.$exp$),
  ($id$int-m-13$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$medium$diff$, $prompt$Calcula: $\int \frac{dx}{x^2 + 9}$$prompt$, $json$[{"latex":"\\frac{1}{3}\\arctan\\frac{x}{3} + C","correct":true},{"latex":"\\frac{1}{9}\\arctan x + C","correct":false},{"latex":"\\arctan\\frac{x}{3} + C","correct":false},{"latex":"\\ln(x^2 + 9) + C","correct":false}]$json$::jsonb, $exp$Fórmula (18) con $a = 3$: $\frac{1}{3}\arctan\frac{x}{3} + C$.$exp$),
  ($id$int-m-14$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$medium$diff$, $prompt$Calcula: $\int \frac{dx}{\sqrt{4 - x^2}}$$prompt$, $json$[{"latex":"\\arcsin\\frac{x}{2} + C","correct":true},{"latex":"\\arcsin x + C","correct":false},{"latex":"\\frac{1}{2}\\arcsin x + C","correct":false},{"latex":"\\arccos\\frac{x}{2} + C","correct":false}]$json$::jsonb, $exp$Fórmula (20) con $a = 2$: $\arcsin\frac{x}{2} + C$.$exp$),
  ($id$int-m-15$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$medium$diff$, $prompt$Calcula: $\int \frac{dx}{x^2 - 1}$$prompt$, $json$[{"latex":"\\frac{1}{2}\\ln\\left|\\frac{x-1}{x+1}\\right| + C","correct":true},{"latex":"\\ln\\left|\\frac{x-1}{x+1}\\right| + C","correct":false},{"latex":"\\arctan x + C","correct":false},{"latex":"\\frac{1}{2}\\ln\\left|\\frac{x+1}{x-1}\\right| + C","correct":false}]$json$::jsonb, $exp$Fórmula (19) con $a = 1$: $\frac{1}{2}\ln\left|\frac{x-1}{x+1}\right| + C$.$exp$),
  ($id$int-m-16$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$medium$diff$, $prompt$Calcula: $\int \frac{dx}{1 - x^2}$$prompt$, $json$[{"latex":"\\frac{1}{2}\\ln\\left|\\frac{1+x}{1-x}\\right| + C","correct":true},{"latex":"\\frac{1}{2}\\ln\\left|\\frac{1-x}{1+x}\\right| + C","correct":false},{"latex":"\\arcsin x + C","correct":false},{"latex":"\\arctan x + C","correct":false}]$json$::jsonb, $exp$Fórmula (19a) con $a = 1$: $\frac{1}{2}\ln\left|\frac{1+x}{1-x}\right| + C$.$exp$),
  ($id$int-m-17$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$medium$diff$, $prompt$Calcula: $\int 3^x\,dx$$prompt$, $json$[{"latex":"\\frac{3^x}{\\ln 3} + C","correct":true},{"latex":"3^x \\ln 3 + C","correct":false},{"latex":"\\frac{x\\,3^x}{\\ln 3} + C","correct":false},{"latex":"3^x + C","correct":false}]$json$::jsonb, $exp$Fórmula (6): $\int a^v\,dv = \frac{a^v}{\ln a} + C$.$exp$),
  ($id$int-m-18$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$medium$diff$, $prompt$¿Qué fórmula (1–23) usas para $\int \frac{dx}{x^2 - 4}$?$prompt$, $json$[{"latex":"\\text{(19) } \\int \\frac{dv}{v^2 - a^2}","correct":true},{"latex":"\\text{(18) } \\int \\frac{dv}{v^2 + a^2}","correct":false},{"latex":"\\text{(19a) } \\int \\frac{dv}{a^2 - v^2}","correct":false},{"latex":"\\text{(5) } \\int \\frac{dv}{v}","correct":false}]$json$::jsonb, $exp$Es $v^2 - a^2$ con $a = 2$: fórmula (19).$exp$),
  ($id$int-m-19$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$medium$diff$, $prompt$¿Qué fórmula (1–23) usas para $\int \frac{dx}{\sqrt{x^2 + 4}}$?$prompt$, $json$[{"latex":"\\text{(21) } \\int \\frac{dv}{\\sqrt{v^2 \\pm a^2}}","correct":true},{"latex":"\\text{(20) } \\int \\frac{dv}{\\sqrt{a^2 - v^2}}","correct":false},{"latex":"\\text{(22) } \\int \\sqrt{a^2 - v^2}\\,dv","correct":false},{"latex":"\\text{(23) } \\int \\sqrt{v^2 \\pm a^2}\\,dv","correct":false}]$json$::jsonb, $exp$Raíz de $v^2 + a^2$ en el denominador: fórmula (21).$exp$),
  ($id$int-m-20$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$medium$diff$, $prompt$Calcula: $\int e^{3x}\,dx$$prompt$, $json$[{"latex":"\\frac{1}{3}e^{3x} + C","correct":true},{"latex":"3e^{3x} + C","correct":false},{"latex":"e^{3x} + C","correct":false},{"latex":"\\frac{e^{3x}}{\\ln 3} + C","correct":false}]$json$::jsonb, $exp$Con $u = 3x$, $du = 3\,dx$: $\frac{1}{3}\int e^u\,du = \frac{1}{3}e^{3x} + C$.$exp$)
ON CONFLICT (id) DO UPDATE SET
  section_id  = EXCLUDED.section_id,
  subtema_id  = EXCLUDED.subtema_id,
  law_id      = EXCLUDED.law_id,
  difficulty  = EXCLUDED.difficulty,
  prompt      = EXCLUDED.prompt,
  options     = EXCLUDED.options,
  explanation = EXCLUDED.explanation,
  updated_at  = now();

-- Lote 2 (50 preguntas)
INSERT INTO public.questions (id, section_id, subtema_id, law_id, difficulty, prompt, options, explanation)
VALUES
  ($id$int-m-21$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$medium$diff$, $prompt$Calcula: $\int \sin(2x)\,dx$$prompt$, $json$[{"latex":"-\\frac{1}{2}\\cos(2x) + C","correct":true},{"latex":"-\\cos(2x) + C","correct":false},{"latex":"\\frac{1}{2}\\cos(2x) + C","correct":false},{"latex":"-2\\cos(2x) + C","correct":false}]$json$::jsonb, $exp$Con $u = 2x$, $du = 2\,dx$: $-\frac{1}{2}\cos(2x) + C$.$exp$),
  ($id$int-m-22$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$medium$diff$, $prompt$Calcula: $\int (4x^3 - 6x^2 + 2)\,dx$$prompt$, $json$[{"latex":"x^4 - 2x^3 + 2x + C","correct":true},{"latex":"x^4 - 2x^3 + C","correct":false},{"latex":"12x^2 - 12x + C","correct":false},{"latex":"x^4 - 6x^3 + 2x + C","correct":false}]$json$::jsonb, $exp$Fórmula (1) término a término: $x^4 - 2x^3 + 2x + C$.$exp$),
  ($id$int-m-23$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$medium$diff$, $prompt$Calcula: $\int \sec^2(3x)\,dx$$prompt$, $json$[{"latex":"\\frac{1}{3}\\tan(3x) + C","correct":true},{"latex":"\\tan(3x) + C","correct":false},{"latex":"3\\tan(3x) + C","correct":false},{"latex":"\\sec(3x) + C","correct":false}]$json$::jsonb, $exp$Con $u = 3x$, $du = 3\,dx$: $\frac{1}{3}\int\sec^2 u\,du = \frac{1}{3}\tan(3x) + C$.$exp$),
  ($id$int-m-24$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$medium$diff$, $prompt$Calcula: $\int \frac{x}{x^2 + 1}\,dx$$prompt$, $json$[{"latex":"\\frac{1}{2}\\ln(x^2 + 1) + C","correct":true},{"latex":"\\ln(x^2 + 1) + C","correct":false},{"latex":"\\frac{1}{2}\\ln|x| + C","correct":false},{"latex":"\\arctan x + C","correct":false}]$json$::jsonb, $exp$Con $u = x^2 + 1$, $du = 2x\,dx$: $\frac{1}{2}\int\frac{du}{u} = \frac{1}{2}\ln|u| + C$.$exp$),
  ($id$int-m-25$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$medium$diff$, $prompt$Calcula: $\int \cos(3x)\,dx$$prompt$, $json$[{"latex":"\\frac{1}{3}\\sin(3x) + C","correct":true},{"latex":"\\sin(3x) + C","correct":false},{"latex":"-\\frac{1}{3}\\sin(3x) + C","correct":false},{"latex":"3\\sin(3x) + C","correct":false}]$json$::jsonb, $exp$Con $u = 3x$, $du = 3\,dx$: $\frac{1}{3}\int\cos u\,du = \frac{1}{3}\sin(3x) + C$.$exp$),
  ($id$int-m-26$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$medium$diff$, $prompt$¿Qué fórmula (1–23) usas para $\int \sec x\,dx$?$prompt$, $json$[{"latex":"\\text{(16) } \\int \\sec v\\,dv","correct":true},{"latex":"\\text{(12) } \\int \\sec v \\tan v\\,dv","correct":false},{"latex":"\\text{(10) } \\int \\sec^2 v\\,dv","correct":false},{"latex":"\\text{(17) } \\int \\csc v\\,dv","correct":false}]$json$::jsonb, $exp$La secante sola es la fórmula (16), que da un logaritmo.$exp$),
  ($id$int-m-27$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$medium$diff$, $prompt$Calcula: $\int \frac{x^3}{x^4 + 1}\,dx$$prompt$, $json$[{"latex":"\\frac{1}{4}\\ln(x^4 + 1) + C","correct":true},{"latex":"\\ln(x^4 + 1) + C","correct":false},{"latex":"\\frac{1}{4}\\arctan x^4 + C","correct":false},{"latex":"\\frac{x^4}{4} + C","correct":false}]$json$::jsonb, $exp$Con $u = x^4 + 1$, $du = 4x^3\,dx$: $\frac{1}{4}\int\frac{du}{u} = \frac{1}{4}\ln|u| + C$.$exp$),
  ($id$int-m-28$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$medium$diff$, $prompt$Calcula: $\int \frac{dx}{x^2 + 16}$$prompt$, $json$[{"latex":"\\frac{1}{4}\\arctan\\frac{x}{4} + C","correct":true},{"latex":"\\frac{1}{16}\\arctan x + C","correct":false},{"latex":"\\arctan\\frac{x}{4} + C","correct":false},{"latex":"\\ln(x^2 + 16) + C","correct":false}]$json$::jsonb, $exp$Fórmula (18) con $a = 4$: $\frac{1}{4}\arctan\frac{x}{4} + C$.$exp$),
  ($id$int-m-29$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$medium$diff$, $prompt$¿La integral $\int x\,\ln x\,dx$ se resuelve con una fórmula directa (1–23)?$prompt$, $json$[{"latex":"\\text{No: requiere integración por partes}","correct":true},{"latex":"\\text{Sí, con la fórmula (5)}","correct":false},{"latex":"\\text{Sí, con la fórmula (4)}","correct":false},{"latex":"\\text{Sí, con la fórmula (14)}","correct":false}]$json$::jsonb, $exp$Es un producto de dos funciones de $x$ sin factor $dv$ directo: se usa integración por partes.$exp$),
  ($id$int-m-30$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$medium$diff$, $prompt$¿Qué sustitución $u$ resuelve $\int \sin(x^2)\cdot 2x\,dx$?$prompt$, $json$[{"latex":"u = x^2","correct":true},{"latex":"u = \\sin(x^2)","correct":false},{"latex":"u = 2x","correct":false},{"latex":"u = x","correct":false}]$json$::jsonb, $exp$Si $u = x^2$, $du = 2x\,dx$: la integral queda $\int\sin u\,du$.$exp$),
  ($id$int-h-01$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$hard$diff$, $prompt$Calcula: $\int \frac{dx}{x^2 + 6x + 10}$$prompt$, $json$[{"latex":"\\arctan(x + 3) + C","correct":true},{"latex":"\\frac{1}{3}\\arctan\\frac{x+3}{3} + C","correct":false},{"latex":"\\ln(x^2 + 6x + 10) + C","correct":false},{"latex":"\\arctan(x + 6) + C","correct":false}]$json$::jsonb, $exp$Completando el cuadrado: $x^2 + 6x + 10 = (x+3)^2 + 1$. Fórmula (18) con $a = 1$ y $v = x + 3$.$exp$),
  ($id$int-h-02$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$hard$diff$, $prompt$Calcula: $\int \frac{dx}{x^2 - 6x + 5}$$prompt$, $json$[{"latex":"\\frac{1}{4}\\ln\\left|\\frac{x-5}{x-1}\\right| + C","correct":true},{"latex":"\\frac{1}{4}\\ln\\left|\\frac{x-1}{x-5}\\right| + C","correct":false},{"latex":"\\frac{1}{2}\\ln\\left|\\frac{x-5}{x-1}\\right| + C","correct":false},{"latex":"\\arctan(x-3) + C","correct":false}]$json$::jsonb, $exp$Completando: $x^2 - 6x + 5 = (x-3)^2 - 4$. Fórmula (19) con $a = 2$, $v = x - 3$.$exp$),
  ($id$int-h-03$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$hard$diff$, $prompt$Calcula: $\int x\,\sec^2(x^2)\,dx$$prompt$, $json$[{"latex":"\\frac{1}{2}\\tan(x^2) + C","correct":true},{"latex":"\\tan(x^2) + C","correct":false},{"latex":"\\frac{1}{2}\\sec(x^2) + C","correct":false},{"latex":"\\sec^2(x^2) + C","correct":false}]$json$::jsonb, $exp$Con $u = x^2$, $du = 2x\,dx$: $\frac{1}{2}\int\sec^2 u\,du = \frac{1}{2}\tan(x^2) + C$.$exp$),
  ($id$int-h-04$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$hard$diff$, $prompt$Calcula: $\int e^{\sin x}\cos x\,dx$$prompt$, $json$[{"latex":"e^{\\sin x} + C","correct":true},{"latex":"e^{\\cos x} + C","correct":false},{"latex":"\\sin x\\,e^{\\sin x} + C","correct":false},{"latex":"\\cos x\\,e^{\\sin x} + C","correct":false}]$json$::jsonb, $exp$Con $u = \sin x$, $du = \cos x\,dx$: $\int e^u\,du = e^{\sin x} + C$ (fórmula 7).$exp$),
  ($id$int-h-05$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$hard$diff$, $prompt$Calcula: $\int \cos x\,\sin^2 x\,dx$$prompt$, $json$[{"latex":"\\frac{\\sin^3 x}{3} + C","correct":true},{"latex":"\\frac{\\cos^3 x}{3} + C","correct":false},{"latex":"\\sin^3 x + C","correct":false},{"latex":"-\\frac{\\cos^3 x}{3} + C","correct":false}]$json$::jsonb, $exp$Con $u = \sin x$, $du = \cos x\,dx$: $\int u^2\,du = \frac{\sin^3 x}{3} + C$ (fórmula 4).$exp$),
  ($id$int-h-06$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$hard$diff$, $prompt$Calcula: $\int \frac{dx}{\sqrt{x^2 + 4}}$$prompt$, $json$[{"latex":"\\ln\\left|x + \\sqrt{x^2 + 4}\\right| + C","correct":true},{"latex":"\\arcsin\\frac{x}{2} + C","correct":false},{"latex":"\\frac{1}{2}\\ln|x + \\sqrt{x^2+4}| + C","correct":false},{"latex":"\\sqrt{x^2 + 4} + C","correct":false}]$json$::jsonb, $exp$Fórmula (21) con $a = 2$: $\ln|v + \sqrt{v^2 + a^2}| + C$.$exp$),
  ($id$int-h-07$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$hard$diff$, $prompt$Calcula: $\int \frac{dx}{\sqrt{x^2 - 9}}$$prompt$, $json$[{"latex":"\\ln\\left|x + \\sqrt{x^2 - 9}\\right| + C","correct":true},{"latex":"\\arcsin\\frac{x}{3} + C","correct":false},{"latex":"\\frac{1}{3}\\ln|x + \\sqrt{x^2-9}| + C","correct":false},{"latex":"\\sqrt{x^2 - 9} + C","correct":false}]$json$::jsonb, $exp$Fórmula (21) con $a = 3$: $\ln|v + \sqrt{v^2 - a^2}| + C$.$exp$),
  ($id$int-h-08$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$hard$diff$, $prompt$Calcula: $\int \sqrt{x^2 + 4}\,dx$$prompt$, $json$[{"latex":"\\frac{x}{2}\\sqrt{x^2+4} + 2\\ln\\left|x + \\sqrt{x^2+4}\\right| + C","correct":true},{"latex":"\\frac{x}{2}\\sqrt{x^2+4} + \\ln\\left|x + \\sqrt{x^2+4}\\right| + C","correct":false},{"latex":"\\frac{x}{2}\\sqrt{x^2+4} + C","correct":false},{"latex":"\\frac{x}{2}\\sqrt{x^2+4} - 2\\ln\\left|x + \\sqrt{x^2+4}\\right| + C","correct":false}]$json$::jsonb, $exp$Fórmula (23) con $a = 2$: $\frac{x}{2}\sqrt{x^2+4} + \frac{4}{2}\ln|x + \sqrt{x^2+4}| + C$.$exp$),
  ($id$int-h-09$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$hard$diff$, $prompt$Calcula: $\int \sqrt{4 - x^2}\,dx$$prompt$, $json$[{"latex":"\\frac{x}{2}\\sqrt{4-x^2} + 2\\arcsin\\frac{x}{2} + C","correct":true},{"latex":"\\frac{x}{2}\\sqrt{4-x^2} + \\arcsin\\frac{x}{2} + C","correct":false},{"latex":"\\frac{x}{2}\\sqrt{4-x^2} + C","correct":false},{"latex":"\\arcsin\\frac{x}{2} + C","correct":false}]$json$::jsonb, $exp$Fórmula (22) con $a = 2$: $\frac{x}{2}\sqrt{4-x^2} + \frac{4}{2}\arcsin\frac{x}{2} + C$.$exp$),
  ($id$int-h-10$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$hard$diff$, $prompt$Calcula: $\int \frac{dx}{x^2 + 4x + 8}$$prompt$, $json$[{"latex":"\\frac{1}{2}\\arctan\\frac{x+2}{2} + C","correct":true},{"latex":"\\frac{1}{2}\\arctan\\frac{x+4}{2} + C","correct":false},{"latex":"\\arctan\\frac{x+2}{2} + C","correct":false},{"latex":"\\ln(x^2 + 4x + 8) + C","correct":false}]$json$::jsonb, $exp$Completando: $x^2 + 4x + 8 = (x+2)^2 + 4$. Fórmula (18) con $a = 2$, $v = x+2$.$exp$),
  ($id$int-h-11$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$hard$diff$, $prompt$Calcula: $\int x\,\cos(x^2 + 1)\,dx$$prompt$, $json$[{"latex":"\\frac{1}{2}\\sin(x^2 + 1) + C","correct":true},{"latex":"\\sin(x^2 + 1) + C","correct":false},{"latex":"-\\frac{1}{2}\\sin(x^2 + 1) + C","correct":false},{"latex":"\\frac{1}{2}\\cos(x^2 + 1) + C","correct":false}]$json$::jsonb, $exp$Con $u = x^2 + 1$, $du = 2x\,dx$: $\frac{1}{2}\int\cos u\,du = \frac{1}{2}\sin(x^2+1) + C$.$exp$),
  ($id$int-h-12$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$hard$diff$, $prompt$Calcula: $\int x^2\,e^{x^3}\,dx$$prompt$, $json$[{"latex":"\\frac{1}{3}e^{x^3} + C","correct":true},{"latex":"e^{x^3} + C","correct":false},{"latex":"3e^{x^3} + C","correct":false},{"latex":"x^3 e^{x^3} + C","correct":false}]$json$::jsonb, $exp$Con $u = x^3$, $du = 3x^2\,dx$: $\frac{1}{3}\int e^u\,du = \frac{1}{3}e^{x^3} + C$.$exp$),
  ($id$int-h-13$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$hard$diff$, $prompt$Calcula: $\int x\,\tan(x^2)\,dx$$prompt$, $json$[{"latex":"-\\frac{1}{2}\\ln|\\cos(x^2)| + C","correct":true},{"latex":"\\frac{1}{2}\\ln|\\cos(x^2)| + C","correct":false},{"latex":"\\ln|\\cos(x^2)| + C","correct":false},{"latex":"-\\ln|\\cos(x^2)| + C","correct":false}]$json$::jsonb, $exp$Con $u = x^2$, $du = 2x\,dx$: $\frac{1}{2}\int\tan u\,du = -\frac{1}{2}\ln|\cos u| + C$ (fórmula 14).$exp$),
  ($id$int-h-14$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$hard$diff$, $prompt$Calcula: $\int \frac{dx}{x^2 - 2x + 5}$$prompt$, $json$[{"latex":"\\frac{1}{2}\\arctan\\frac{x-1}{2} + C","correct":true},{"latex":"\\frac{1}{2}\\arctan\\frac{x-2}{2} + C","correct":false},{"latex":"\\arctan\\frac{x-1}{2} + C","correct":false},{"latex":"\\ln(x^2 - 2x + 5) + C","correct":false}]$json$::jsonb, $exp$Completando: $x^2 - 2x + 5 = (x-1)^2 + 4$. Fórmula (18) con $a = 2$, $v = x-1$.$exp$),
  ($id$int-h-15$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$hard$diff$, $prompt$Calcula: $\int \frac{dx}{9x^2 + 4}$$prompt$, $json$[{"latex":"\\frac{1}{6}\\arctan\\frac{3x}{2} + C","correct":true},{"latex":"\\frac{1}{2}\\arctan\\frac{3x}{2} + C","correct":false},{"latex":"\\frac{1}{6}\\arctan(3x) + C","correct":false},{"latex":"\\frac{1}{4}\\arctan(3x) + C","correct":false}]$json$::jsonb, $exp$$9x^2 + 4 = (3x)^2 + 4$. Con $u = 3x$, $du = 3\,dx$: $\frac{1}{3}\cdot\frac{1}{2}\arctan\frac{3x}{2} = \frac{1}{6}\arctan\frac{3x}{2} + C$.$exp$),
  ($id$int-h-16$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$hard$diff$, $prompt$Calcula: $\int \sin x\,\cos^3 x\,dx$$prompt$, $json$[{"latex":"-\\frac{\\cos^4 x}{4} + C","correct":true},{"latex":"\\frac{\\cos^4 x}{4} + C","correct":false},{"latex":"\\frac{\\sin^4 x}{4} + C","correct":false},{"latex":"-\\frac{\\sin^4 x}{4} + C","correct":false}]$json$::jsonb, $exp$Con $u = \cos x$, $du = -\sin x\,dx$: $-\int u^3\,du = -\frac{\cos^4 x}{4} + C$.$exp$),
  ($id$int-h-17$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$hard$diff$, $prompt$Calcula: $\int \frac{dx}{x^2 - 4x + 13}$$prompt$, $json$[{"latex":"\\frac{1}{3}\\arctan\\frac{x-2}{3} + C","correct":true},{"latex":"\\frac{1}{3}\\arctan\\frac{x-4}{3} + C","correct":false},{"latex":"\\arctan\\frac{x-2}{3} + C","correct":false},{"latex":"\\ln(x^2 - 4x + 13) + C","correct":false}]$json$::jsonb, $exp$Completando: $x^2 - 4x + 13 = (x-2)^2 + 9$. Fórmula (18) con $a = 3$, $v = x-2$.$exp$),
  ($id$int-h-18$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$hard$diff$, $prompt$¿Qué fórmula y transformación usas para $\int \frac{dx}{x^2 + 2x + 5}$?$prompt$, $json$[{"latex":"\\text{(18), completando el cuadrado: } (x+1)^2 + 4","correct":true},{"latex":"\\text{(19) directamente}","correct":false},{"latex":"\\text{(5) con } v = x^2 + 2x + 5","correct":false},{"latex":"\\text{(20), completando el cuadrado}","correct":false}]$json$::jsonb, $exp$El denominador es $(x+1)^2 + 4$, forma $v^2 + a^2$: aplica la fórmula (18).$exp$),
  ($id$int-h-19$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$hard$diff$, $prompt$Calcula: $\int \frac{dx}{\sqrt{x^2 - 2x + 5}}$$prompt$, $json$[{"latex":"\\ln\\left|(x-1) + \\sqrt{x^2 - 2x + 5}\\right| + C","correct":true},{"latex":"\\arcsin\\frac{x-1}{2} + C","correct":false},{"latex":"\\frac{1}{2}\\ln|x-1 + \\sqrt{x^2-2x+5}| + C","correct":false},{"latex":"\\sqrt{x^2 - 2x + 5} + C","correct":false}]$json$::jsonb, $exp$Completando: $x^2 - 2x + 5 = (x-1)^2 + 4$. Fórmula (21) con $v = x-1$, $a = 2$.$exp$),
  ($id$int-h-20$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$hard$diff$, $prompt$Calcula: $\int \frac{2x + 4}{x^2 + 4x + 5}\,dx$$prompt$, $json$[{"latex":"\\ln(x^2 + 4x + 5) + C","correct":true},{"latex":"\\frac{1}{2}\\ln(x^2 + 4x + 5) + C","correct":false},{"latex":"\\arctan(x+2) + C","correct":false},{"latex":"\\frac{1}{2}\\arctan(x+2) + C","correct":false}]$json$::jsonb, $exp$El numerador es la derivada del denominador: $\int\frac{du}{u} = \ln|u| + C$ (fórmula 5).$exp$),
  ($id$int-h-21$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$hard$diff$, $prompt$¿Cuál integral se resuelve con la fórmula (20)?$prompt$, $json$[{"latex":"\\int \\frac{dx}{\\sqrt{1 - x^2}}","correct":true},{"latex":"\\int \\frac{dx}{\\sqrt{x^2 + 1}}","correct":false},{"latex":"\\int \\frac{dx}{x^2 + 1}","correct":false},{"latex":"\\int \\sqrt{1 - x^2}\\,dx","correct":false}]$json$::jsonb, $exp$La fórmula (20) es $\int\frac{dv}{\sqrt{a^2 - v^2}} = \arcsin\frac{v}{a} + C$.$exp$),
  ($id$int-h-22$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$hard$diff$, $prompt$Calcula: $\int \sin^5 x\,\cos x\,dx$$prompt$, $json$[{"latex":"\\frac{\\sin^6 x}{6} + C","correct":true},{"latex":"\\frac{\\cos^6 x}{6} + C","correct":false},{"latex":"\\sin^6 x + C","correct":false},{"latex":"-\\frac{\\cos^6 x}{6} + C","correct":false}]$json$::jsonb, $exp$Con $u = \sin x$, $du = \cos x\,dx$: $\int u^5\,du = \frac{\sin^6 x}{6} + C$.$exp$),
  ($id$int-h-23$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$hard$diff$, $prompt$Calcula: $\int \frac{dx}{x^2 - 9}$$prompt$, $json$[{"latex":"\\frac{1}{6}\\ln\\left|\\frac{x-3}{x+3}\\right| + C","correct":true},{"latex":"\\frac{1}{3}\\ln\\left|\\frac{x-3}{x+3}\\right| + C","correct":false},{"latex":"\\frac{1}{6}\\ln\\left|\\frac{x+3}{x-3}\\right| + C","correct":false},{"latex":"\\frac{1}{3}\\arctan\\frac{x}{3} + C","correct":false}]$json$::jsonb, $exp$Fórmula (19) con $a = 3$: $\frac{1}{2\cdot 3}\ln\left|\frac{x-3}{x+3}\right| + C$.$exp$),
  ($id$int-h-24$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$hard$diff$, $prompt$Calcula: $\int x\sqrt{x^2 + 1}\,dx$$prompt$, $json$[{"latex":"\\frac{1}{3}(x^2 + 1)^{3/2} + C","correct":true},{"latex":"(x^2 + 1)^{3/2} + C","correct":false},{"latex":"\\frac{1}{2}(x^2 + 1)^{3/2} + C","correct":false},{"latex":"\\frac{2}{3}(x^2 + 1)^{3/2} + C","correct":false}]$json$::jsonb, $exp$Con $u = x^2 + 1$, $du = 2x\,dx$: $\frac{1}{2}\int u^{1/2}\,du = \frac{1}{3}(x^2+1)^{3/2} + C$.$exp$),
  ($id$int-h-25$id$, $sec$calculo-integral$sec$, $sub$inmediatas$sub$, $law$inmediatas$law$, $diff$hard$diff$, $prompt$¿Qué cambio de variable resuelve $\int \frac{dx}{\sqrt{9 - 4x^2}}$?$prompt$, $json$[{"latex":"v = 2x, \\ a = 3 \\text{ (fórmula 20)}","correct":true},{"latex":"v = 3x, \\ a = 2","correct":false},{"latex":"v = x, \\ a = 3","correct":false},{"latex":"\\text{Fórmula (21)}","correct":false}]$json$::jsonb, $exp$$9 - 4x^2 = 3^2 - (2x)^2$. Con $v = 2x$, $dv = 2\,dx$: $\frac{1}{2}\arcsin\frac{2x}{3} + C$.$exp$),
  ($id$par-f-01$id$, $sec$calculo-integral$sec$, $sub$partes$sub$, $law$partes$law$, $diff$easy$diff$, $prompt$¿Cuál es la fórmula de integración por partes?$prompt$, $json$[{"latex":"\\int u\\,dv = uv - \\int v\\,du","correct":true},{"latex":"\\int u\\,dv = uv + \\int v\\,du","correct":false},{"latex":"\\int u\\,dv = \\frac{du}{dx}\\cdot\\frac{dv}{dx}","correct":false},{"latex":"\\int u\\,dv = \\int u\\,dx \\cdot \\int v\\,dx","correct":false}]$json$::jsonb, $exp$Fórmula de integración por partes: $\int u\,dv = uv - \int v\,du$.$exp$),
  ($id$par-f-02$id$, $sec$calculo-integral$sec$, $sub$partes$sub$, $law$partes$law$, $diff$easy$diff$, $prompt$Para $\int x\,e^x\,dx$, ¿cuál es la elección correcta de $u$?$prompt$, $json$[{"latex":"u = x","correct":true},{"latex":"u = e^x","correct":false},{"latex":"u = x e^x","correct":false},{"latex":"u = dx","correct":false}]$json$::jsonb, $exp$Por LIATE, la algebraica $x$ se elige como $u$; $dv = e^x\,dx$.$exp$),
  ($id$par-f-03$id$, $sec$calculo-integral$sec$, $sub$partes$sub$, $law$partes$law$, $diff$easy$diff$, $prompt$Para $\int x\,e^x\,dx$ con $u = x$, ¿cuál es $dv$?$prompt$, $json$[{"latex":"dv = e^x\\,dx","correct":true},{"latex":"dv = x\\,dx","correct":false},{"latex":"dv = e^x","correct":false},{"latex":"dv = dx","correct":false}]$json$::jsonb, $exp$Con $u = x$, el resto del integrando es $dv = e^x\,dx$, luego $v = e^x$.$exp$),
  ($id$par-f-04$id$, $sec$calculo-integral$sec$, $sub$partes$sub$, $law$partes$law$, $diff$easy$diff$, $prompt$Calcula: $\int x\,e^x\,dx$$prompt$, $json$[{"latex":"x e^x - e^x + C","correct":true},{"latex":"x e^x + e^x + C","correct":false},{"latex":"x e^x + C","correct":false},{"latex":"e^x + C","correct":false}]$json$::jsonb, $exp$$u = x$, $dv = e^x dx$: $x e^x - \int e^x\,dx = x e^x - e^x + C$.$exp$),
  ($id$par-f-05$id$, $sec$calculo-integral$sec$, $sub$partes$sub$, $law$partes$law$, $diff$easy$diff$, $prompt$Para $\int x\,\cos x\,dx$, ¿cuál es la elección correcta de $u$?$prompt$, $json$[{"latex":"u = x","correct":true},{"latex":"u = \\cos x","correct":false},{"latex":"u = x \\cos x","correct":false},{"latex":"u = \\sin x","correct":false}]$json$::jsonb, $exp$Por LIATE, $u = x$ (algebraica) y $dv = \cos x\,dx$.$exp$),
  ($id$par-f-06$id$, $sec$calculo-integral$sec$, $sub$partes$sub$, $law$partes$law$, $diff$easy$diff$, $prompt$¿Cuándo conviene usar integración por partes?$prompt$, $json$[{"latex":"\\text{Cuando hay producto de funciones sin fórmula directa}","correct":true},{"latex":"\\text{Siempre que aparezca una potencia}","correct":false},{"latex":"\\text{Solo con funciones exponenciales}","correct":false},{"latex":"\\text{Cuando hay una suma de funciones}","correct":false}]$json$::jsonb, $exp$Se usa para productos (o logaritmos/inversas solas) que no se resuelven por fórmula inmediata.$exp$),
  ($id$par-f-07$id$, $sec$calculo-integral$sec$, $sub$partes$sub$, $law$partes$law$, $diff$easy$diff$, $prompt$Para $\int \ln x\,dx$, ¿cuál es la elección correcta de $u$?$prompt$, $json$[{"latex":"u = \\ln x","correct":true},{"latex":"u = x","correct":false},{"latex":"u = \\frac{1}{x}","correct":false},{"latex":"u = 1","correct":false}]$json$::jsonb, $exp$El logaritmo no se integra fácil: se elige $u = \ln x$ y $dv = dx$.$exp$),
  ($id$par-f-08$id$, $sec$calculo-integral$sec$, $sub$partes$sub$, $law$partes$law$, $diff$easy$diff$, $prompt$Calcula: $\int x\,\sin x\,dx$$prompt$, $json$[{"latex":"-x\\cos x + \\sin x + C","correct":true},{"latex":"x\\cos x + \\sin x + C","correct":false},{"latex":"-x\\cos x - \\sin x + C","correct":false},{"latex":"x\\cos x - \\sin x + C","correct":false}]$json$::jsonb, $exp$$u = x$, $dv = \sin x\,dx$: $-x\cos x - \int(-\cos x)\,dx = -x\cos x + \sin x + C$.$exp$),
  ($id$par-m-01$id$, $sec$calculo-integral$sec$, $sub$partes$sub$, $law$partes$law$, $diff$medium$diff$, $prompt$Calcula: $\int x\,\cos x\,dx$$prompt$, $json$[{"latex":"x\\sin x + \\cos x + C","correct":true},{"latex":"x\\sin x - \\cos x + C","correct":false},{"latex":"\\sin x + C","correct":false},{"latex":"-x\\sin x + \\cos x + C","correct":false}]$json$::jsonb, $exp$$u = x$, $dv = \cos x\,dx$: $x\sin x - \int\sin x\,dx = x\sin x + \cos x + C$.$exp$),
  ($id$par-m-02$id$, $sec$calculo-integral$sec$, $sub$partes$sub$, $law$partes$law$, $diff$medium$diff$, $prompt$Calcula: $\int x\,\ln x\,dx$$prompt$, $json$[{"latex":"\\frac{x^2}{2}\\ln x - \\frac{x^2}{4} + C","correct":true},{"latex":"\\frac{x^2}{2}\\ln x + \\frac{x^2}{4} + C","correct":false},{"latex":"\\frac{x^2}{2}\\ln x + C","correct":false},{"latex":"x\\ln x - x + C","correct":false}]$json$::jsonb, $exp$$u = \ln x$, $dv = x\,dx$: $\frac{x^2}{2}\ln x - \int\frac{x}{2}\,dx = \frac{x^2}{2}\ln x - \frac{x^2}{4} + C$.$exp$),
  ($id$par-m-03$id$, $sec$calculo-integral$sec$, $sub$partes$sub$, $law$partes$law$, $diff$medium$diff$, $prompt$Calcula: $\int x^2\,e^x\,dx$$prompt$, $json$[{"latex":"x^2 e^x - 2x e^x + 2e^x + C","correct":true},{"latex":"x^2 e^x - 2x e^x + C","correct":false},{"latex":"x^2 e^x + C","correct":false},{"latex":"2x e^x + C","correct":false}]$json$::jsonb, $exp$Dos pasadas de partes (o tabla): $x^2 e^x - 2x e^x + 2e^x + C$.$exp$),
  ($id$par-m-04$id$, $sec$calculo-integral$sec$, $sub$partes$sub$, $law$partes$law$, $diff$medium$diff$, $prompt$Calcula: $\int \ln x\,dx$$prompt$, $json$[{"latex":"x\\ln x - x + C","correct":true},{"latex":"x\\ln x + x + C","correct":false},{"latex":"\\ln x + C","correct":false},{"latex":"x\\ln x + C","correct":false}]$json$::jsonb, $exp$$u = \ln x$, $dv = dx$: $x\ln x - \int x\cdot\frac{1}{x}\,dx = x\ln x - x + C$.$exp$),
  ($id$par-m-05$id$, $sec$calculo-integral$sec$, $sub$partes$sub$, $law$partes$law$, $diff$medium$diff$, $prompt$Calcula: $\int \arctan x\,dx$$prompt$, $json$[{"latex":"x\\arctan x - \\frac{1}{2}\\ln(1 + x^2) + C","correct":true},{"latex":"x\\arctan x + \\frac{1}{2}\\ln(1 + x^2) + C","correct":false},{"latex":"x\\arctan x + C","correct":false},{"latex":"\\frac{x}{1 + x^2} + C","correct":false}]$json$::jsonb, $exp$$u = \arctan x$, $dv = dx$: $x\arctan x - \int\frac{x}{1+x^2}\,dx$.$exp$),
  ($id$par-m-06$id$, $sec$calculo-integral$sec$, $sub$partes$sub$, $law$partes$law$, $diff$medium$diff$, $prompt$Según LIATE, ¿qué eliges como $u$ en $\int x^2\,\sin x\,dx$?$prompt$, $json$[{"latex":"u = x^2","correct":true},{"latex":"u = \\sin x","correct":false},{"latex":"u = \\cos x","correct":false},{"latex":"u = x","correct":false}]$json$::jsonb, $exp$Algebraica ($x^2$) va antes que trigonométrica en LIATE: $u = x^2$.$exp$),
  ($id$par-m-07$id$, $sec$calculo-integral$sec$, $sub$partes$sub$, $law$partes$law$, $diff$medium$diff$, $prompt$Calcula: $\int x\,e^{2x}\,dx$$prompt$, $json$[{"latex":"\\frac{x}{2}e^{2x} - \\frac{1}{4}e^{2x} + C","correct":true},{"latex":"\\frac{x}{2}e^{2x} + \\frac{1}{4}e^{2x} + C","correct":false},{"latex":"x e^{2x} - e^{2x} + C","correct":false},{"latex":"\\frac{x}{2}e^{2x} + C","correct":false}]$json$::jsonb, $exp$$u = x$, $dv = e^{2x}dx$: $\frac{x}{2}e^{2x} - \int\frac{1}{2}e^{2x}\,dx = \frac{x}{2}e^{2x} - \frac{1}{4}e^{2x} + C$.$exp$)
ON CONFLICT (id) DO UPDATE SET
  section_id  = EXCLUDED.section_id,
  subtema_id  = EXCLUDED.subtema_id,
  law_id      = EXCLUDED.law_id,
  difficulty  = EXCLUDED.difficulty,
  prompt      = EXCLUDED.prompt,
  options     = EXCLUDED.options,
  explanation = EXCLUDED.explanation,
  updated_at  = now();

-- Lote 3 (50 preguntas)
INSERT INTO public.questions (id, section_id, subtema_id, law_id, difficulty, prompt, options, explanation)
VALUES
  ($id$par-m-08$id$, $sec$calculo-integral$sec$, $sub$partes$sub$, $law$partes$law$, $diff$medium$diff$, $prompt$En $\int x\,\cos x\,dx$ con $u = x$, ¿cuál es $dv$?$prompt$, $json$[{"latex":"dv = \\cos x\\,dx","correct":true},{"latex":"dv = \\sin x\\,dx","correct":false},{"latex":"dv = x\\,dx","correct":false},{"latex":"dv = \\cos x","correct":false}]$json$::jsonb, $exp$Con $u = x$, el resto es $dv = \cos x\,dx$, luego $v = \sin x$.$exp$),
  ($id$par-m-09$id$, $sec$calculo-integral$sec$, $sub$partes$sub$, $law$partes$law$, $diff$medium$diff$, $prompt$Calcula: $\int x\,\sec^2 x\,dx$$prompt$, $json$[{"latex":"x\\tan x + \\ln|\\cos x| + C","correct":true},{"latex":"x\\tan x - \\ln|\\cos x| + C","correct":false},{"latex":"x\\tan x + C","correct":false},{"latex":"\\frac{x^2}{2}\\tan x + C","correct":false}]$json$::jsonb, $exp$$u = x$, $dv = \sec^2 x\,dx$: $x\tan x - \int\tan x\,dx = x\tan x + \ln|\cos x| + C$.$exp$),
  ($id$par-m-10$id$, $sec$calculo-integral$sec$, $sub$partes$sub$, $law$partes$law$, $diff$medium$diff$, $prompt$Para $\int e^x\,\sin x\,dx$, ¿cuántas veces se aplica integración por partes?$prompt$, $json$[{"latex":"\\text{Dos veces (caso cíclico)}","correct":true},{"latex":"\\text{Una sola vez}","correct":false},{"latex":"\\text{Tres veces}","correct":false},{"latex":"\\text{No se puede aplicar}","correct":false}]$json$::jsonb, $exp$Tras dos pasadas reaparece la integral original y se despeja.$exp$),
  ($id$par-h-01$id$, $sec$calculo-integral$sec$, $sub$partes$sub$, $law$partes$law$, $diff$hard$diff$, $prompt$Calcula: $\int e^x\,\sin x\,dx$$prompt$, $json$[{"latex":"\\frac{e^x}{2}(\\sin x - \\cos x) + C","correct":true},{"latex":"\\frac{e^x}{2}(\\sin x + \\cos x) + C","correct":false},{"latex":"e^x(\\sin x - \\cos x) + C","correct":false},{"latex":"\\frac{e^x}{2}\\sin x + C","correct":false}]$json$::jsonb, $exp$Caso cíclico: $I = e^x\sin x - e^x\cos x - I$, luego $I = \frac{e^x}{2}(\sin x - \cos x) + C$.$exp$),
  ($id$par-h-02$id$, $sec$calculo-integral$sec$, $sub$partes$sub$, $law$partes$law$, $diff$hard$diff$, $prompt$Calcula: $\int x^2\,\sin x\,dx$$prompt$, $json$[{"latex":"-x^2\\cos x + 2x\\sin x + 2\\cos x + C","correct":true},{"latex":"-x^2\\cos x + 2x\\sin x + C","correct":false},{"latex":"x^2\\cos x - 2x\\sin x + C","correct":false},{"latex":"-x^2\\cos x - 2x\\sin x + C","correct":false}]$json$::jsonb, $exp$$u = x^2$, luego $\int x\sin x\,dx$: $-x^2\cos x + 2x\sin x + 2\cos x + C$.$exp$),
  ($id$par-h-03$id$, $sec$calculo-integral$sec$, $sub$partes$sub$, $law$partes$law$, $diff$hard$diff$, $prompt$Calcula: $\int e^x\,\cos x\,dx$$prompt$, $json$[{"latex":"\\frac{e^x}{2}(\\sin x + \\cos x) + C","correct":true},{"latex":"\\frac{e^x}{2}(\\sin x - \\cos x) + C","correct":false},{"latex":"e^x\\cos x + C","correct":false},{"latex":"\\frac{e^x}{2}\\cos x + C","correct":false}]$json$::jsonb, $exp$Caso cíclico: $I = e^x\cos x + e^x\sin x - I$, luego $I = \frac{e^x}{2}(\sin x + \cos x) + C$.$exp$),
  ($id$par-h-04$id$, $sec$calculo-integral$sec$, $sub$partes$sub$, $law$partes$law$, $diff$hard$diff$, $prompt$Calcula: $\int (\ln x)^2\,dx$$prompt$, $json$[{"latex":"x(\\ln x)^2 - 2x\\ln x + 2x + C","correct":true},{"latex":"x(\\ln x)^2 - 2x\\ln x + C","correct":false},{"latex":"x(\\ln x)^2 + C","correct":false},{"latex":"\\frac{(\\ln x)^3}{3} + C","correct":false}]$json$::jsonb, $exp$$u = (\ln x)^2$: $x(\ln x)^2 - 2\int\ln x\,dx = x(\ln x)^2 - 2x\ln x + 2x + C$.$exp$),
  ($id$par-h-05$id$, $sec$calculo-integral$sec$, $sub$partes$sub$, $law$partes$law$, $diff$hard$diff$, $prompt$Calcula: $\int x^3\,\ln x\,dx$$prompt$, $json$[{"latex":"\\frac{x^4}{4}\\ln x - \\frac{x^4}{16} + C","correct":true},{"latex":"\\frac{x^4}{4}\\ln x + \\frac{x^4}{16} + C","correct":false},{"latex":"\\frac{x^4}{4}\\ln x + C","correct":false},{"latex":"\\frac{x^3}{3}\\ln x - \\frac{x^3}{9} + C","correct":false}]$json$::jsonb, $exp$$u = \ln x$, $dv = x^3 dx$: $\frac{x^4}{4}\ln x - \int\frac{x^3}{4}\,dx = \frac{x^4}{4}\ln x - \frac{x^4}{16} + C$.$exp$),
  ($id$par-h-06$id$, $sec$calculo-integral$sec$, $sub$partes$sub$, $law$partes$law$, $diff$hard$diff$, $prompt$Calcula: $\int x\,e^{-x}\,dx$$prompt$, $json$[{"latex":"-x e^{-x} - e^{-x} + C","correct":true},{"latex":"-x e^{-x} + e^{-x} + C","correct":false},{"latex":"x e^{-x} - e^{-x} + C","correct":false},{"latex":"-x e^{-x} + C","correct":false}]$json$::jsonb, $exp$$u = x$, $dv = e^{-x}dx$: $-x e^{-x} - \int(-e^{-x})\,dx = -x e^{-x} - e^{-x} + C$.$exp$),
  ($id$par-h-07$id$, $sec$calculo-integral$sec$, $sub$partes$sub$, $law$partes$law$, $diff$hard$diff$, $prompt$Calcula: $\int x^2\,\cos x\,dx$$prompt$, $json$[{"latex":"x^2\\sin x + 2x\\cos x - 2\\sin x + C","correct":true},{"latex":"x^2\\sin x - 2x\\cos x + C","correct":false},{"latex":"-x^2\\sin x + 2x\\cos x + C","correct":false},{"latex":"x^2\\sin x + 2x\\cos x + C","correct":false}]$json$::jsonb, $exp$$u = x^2$: $x^2\sin x - 2\int x\sin x\,dx = x^2\sin x + 2x\cos x - 2\sin x + C$.$exp$),
  ($id$fra-f-01$id$, $sec$calculo-integral$sec$, $sub$fracciones-parciales$sub$, $law$fracciones-parciales$law$, $diff$easy$diff$, $prompt$¿Qué descomposición corresponde a $\frac{1}{(x+1)(x+2)}$?$prompt$, $json$[{"latex":"\\frac{A}{x+1} + \\frac{B}{x+2}","correct":true},{"latex":"\\frac{Ax + B}{(x+1)(x+2)}","correct":false},{"latex":"\\frac{A}{(x+1)^2} + \\frac{B}{(x+2)^2}","correct":false},{"latex":"\\frac{A}{x+1}\\cdot\\frac{B}{x+2}","correct":false}]$json$::jsonb, $exp$Factores lineales distintos: un término simple por cada factor.$exp$),
  ($id$fra-f-02$id$, $sec$calculo-integral$sec$, $sub$fracciones-parciales$sub$, $law$fracciones-parciales$law$, $diff$easy$diff$, $prompt$¿Qué descomposición corresponde a $\frac{1}{(x+1)^2}$?$prompt$, $json$[{"latex":"\\frac{A}{x+1} + \\frac{B}{(x+1)^2}","correct":true},{"latex":"\\frac{A}{(x+1)^2}","correct":false},{"latex":"\\frac{A}{x+1} + \\frac{B}{x+1}","correct":false},{"latex":"\\frac{Ax + B}{(x+1)^2}","correct":false}]$json$::jsonb, $exp$Factor lineal repetido: un término por cada potencia hasta la del factor.$exp$),
  ($id$fra-f-03$id$, $sec$calculo-integral$sec$, $sub$fracciones-parciales$sub$, $law$fracciones-parciales$law$, $diff$easy$diff$, $prompt$¿Qué descomposición corresponde a $\frac{1}{x^2 + 1}$?$prompt$, $json$[{"latex":"\\frac{Ax + B}{x^2 + 1}","correct":true},{"latex":"\\frac{A}{x^2 + 1}","correct":false},{"latex":"\\frac{A}{x} + \\frac{B}{x + 1}","correct":false},{"latex":"\\frac{A}{x^2} + \\frac{B}{1}","correct":false}]$json$::jsonb, $exp$Factor cuadrático irreducible: numerador lineal $Ax + B$.$exp$),
  ($id$fra-f-04$id$, $sec$calculo-integral$sec$, $sub$fracciones-parciales$sub$, $law$fracciones-parciales$law$, $diff$easy$diff$, $prompt$¿Cuál es el primer paso para integrar $\frac{P(x)}{Q(x)}$?$prompt$, $json$[{"latex":"\\text{Verificar que grado de } P < \\text{ grado de } Q","correct":true},{"latex":"\\text{Integrar directamente el numerador}","correct":false},{"latex":"\\text{Derivar el denominador}","correct":false},{"latex":"\\text{Multiplicar por } Q(x)","correct":false}]$json$::jsonb, $exp$Si el grado del numerador es mayor o igual, primero se hace división larga.$exp$),
  ($id$fra-f-05$id$, $sec$calculo-integral$sec$, $sub$fracciones-parciales$sub$, $law$fracciones-parciales$law$, $diff$easy$diff$, $prompt$¿Cuál es la forma de fracciones parciales de $\frac{1}{x(x+1)}$?$prompt$, $json$[{"latex":"\\frac{A}{x} + \\frac{B}{x+1}","correct":true},{"latex":"\\frac{A}{x(x+1)}","correct":false},{"latex":"\\frac{Ax + B}{x(x+1)}","correct":false},{"latex":"\\frac{A}{x} + \\frac{B}{x}","correct":false}]$json$::jsonb, $exp$Dos factores lineales distintos ($x$ y $x+1$): $\frac{A}{x} + \frac{B}{x+1}$.$exp$),
  ($id$fra-f-06$id$, $sec$calculo-integral$sec$, $sub$fracciones-parciales$sub$, $law$fracciones-parciales$law$, $diff$easy$diff$, $prompt$¿Qué fórmula se usa para integrar un término $\frac{A}{x+a}$?$prompt$, $json$[{"latex":"A\\ln|x + a| + C","correct":true},{"latex":"\\frac{A}{(x+a)^2} + C","correct":false},{"latex":"A\\arctan(x + a) + C","correct":false},{"latex":"A(x + a) + C","correct":false}]$json$::jsonb, $exp$Es la fórmula (5) del formulario: $\int\frac{dv}{v} = \ln|v| + C$.$exp$),
  ($id$fra-f-07$id$, $sec$calculo-integral$sec$, $sub$fracciones-parciales$sub$, $law$fracciones-parciales$law$, $diff$easy$diff$, $prompt$En la descomposición, ¿qué representan $A$, $B$, $C$?$prompt$, $json$[{"latex":"\\text{Constantes a determinar}","correct":true},{"latex":"\\text{Variables de integración}","correct":false},{"latex":"\\text{Los factores del denominador}","correct":false},{"latex":"\\text{Las raíces del numerador}","correct":false}]$json$::jsonb, $exp$Son constantes que se hallan evaluando raíces o igualando coeficientes.$exp$),
  ($id$fra-f-08$id$, $sec$calculo-integral$sec$, $sub$fracciones-parciales$sub$, $law$fracciones-parciales$law$, $diff$easy$diff$, $prompt$¿Se puede factorizar $x^2 - 1$?$prompt$, $json$[{"latex":"\\text{Sí: } (x-1)(x+1)","correct":true},{"latex":"\\text{No, es irreducible}","correct":false},{"latex":"\\text{Sí: } (x-1)^2","correct":false},{"latex":"\\text{Sí: } x(x-1)","correct":false}]$json$::jsonb, $exp$Diferencia de cuadrados: $x^2 - 1 = (x-1)(x+1)$.$exp$),
  ($id$fra-f-09$id$, $sec$calculo-integral$sec$, $sub$fracciones-parciales$sub$, $law$fracciones-parciales$law$, $diff$easy$diff$, $prompt$¿Qué tipo de factor es $(x - 3)$ en un denominador?$prompt$, $json$[{"latex":"\\text{Factor lineal simple}","correct":true},{"latex":"\\text{Factor lineal repetido}","correct":false},{"latex":"\\text{Factor cuadrático irreducible}","correct":false},{"latex":"\\text{No se puede descomponer}","correct":false}]$json$::jsonb, $exp$Es lineal y de multiplicidad 1: aporta un término $\frac{A}{x-3}$.$exp$),
  ($id$fra-f-10$id$, $sec$calculo-integral$sec$, $sub$fracciones-parciales$sub$, $law$fracciones-parciales$law$, $diff$easy$diff$, $prompt$Calcula: $\int \frac{dx}{x + 1}$$prompt$, $json$[{"latex":"\\ln|x + 1| + C","correct":true},{"latex":"\\frac{1}{(x+1)^2} + C","correct":false},{"latex":"\\arctan(x + 1) + C","correct":false},{"latex":"x + 1 + C","correct":false}]$json$::jsonb, $exp$Fórmula (5) con $v = x + 1$: $\ln|x+1| + C$.$exp$),
  ($id$fra-m-01$id$, $sec$calculo-integral$sec$, $sub$fracciones-parciales$sub$, $law$fracciones-parciales$law$, $diff$medium$diff$, $prompt$Calcula: $\int \frac{dx}{(x+1)(x+2)}$$prompt$, $json$[{"latex":"\\ln\\left|\\frac{x+1}{x+2}\\right| + C","correct":true},{"latex":"\\ln\\left|\\frac{x+2}{x+1}\\right| + C","correct":false},{"latex":"\\ln|(x+1)(x+2)| + C","correct":false},{"latex":"\\arctan(x+1) + C","correct":false}]$json$::jsonb, $exp$Con $A=1$, $B=-1$: $\ln|x+1| - \ln|x+2| = \ln\left|\frac{x+1}{x+2}\right| + C$.$exp$),
  ($id$fra-m-02$id$, $sec$calculo-integral$sec$, $sub$fracciones-parciales$sub$, $law$fracciones-parciales$law$, $diff$medium$diff$, $prompt$Calcula: $\int \frac{dx}{x^2 - 1}$$prompt$, $json$[{"latex":"\\frac{1}{2}\\ln\\left|\\frac{x-1}{x+1}\\right| + C","correct":true},{"latex":"\\frac{1}{2}\\ln\\left|\\frac{x+1}{x-1}\\right| + C","correct":false},{"latex":"\\ln|x^2 - 1| + C","correct":false},{"latex":"\\arctan x + C","correct":false}]$json$::jsonb, $exp$$A=\frac{1}{2}$, $B=-\frac{1}{2}$: $\frac{1}{2}\ln|x-1| - \frac{1}{2}\ln|x+1| + C$.$exp$),
  ($id$fra-m-03$id$, $sec$calculo-integral$sec$, $sub$fracciones-parciales$sub$, $law$fracciones-parciales$law$, $diff$medium$diff$, $prompt$Calcula: $\int \frac{dx}{x(x+1)}$$prompt$, $json$[{"latex":"\\ln\\left|\\frac{x}{x+1}\\right| + C","correct":true},{"latex":"\\ln\\left|\\frac{x+1}{x}\\right| + C","correct":false},{"latex":"\\ln|x| + \\ln|x+1| + C","correct":false},{"latex":"\\frac{1}{2}\\ln\\left|\\frac{x}{x+1}\\right| + C","correct":false}]$json$::jsonb, $exp$Con $A=1$, $B=-1$: $\ln|x| - \ln|x+1| = \ln\left|\frac{x}{x+1}\right| + C$.$exp$),
  ($id$fra-m-04$id$, $sec$calculo-integral$sec$, $sub$fracciones-parciales$sub$, $law$fracciones-parciales$law$, $diff$medium$diff$, $prompt$En $\frac{1}{(x+1)(x+2)} = \frac{A}{x+1} + \frac{B}{x+2}$, ¿cuánto vale $A$?$prompt$, $json$[{"latex":"A = 1","correct":true},{"latex":"A = -1","correct":false},{"latex":"A = \\frac{1}{2}","correct":false},{"latex":"A = 2","correct":false}]$json$::jsonb, $exp$Evaluando $x = -1$: $1 = A(1)$, luego $A = 1$.$exp$),
  ($id$fra-m-05$id$, $sec$calculo-integral$sec$, $sub$fracciones-parciales$sub$, $law$fracciones-parciales$law$, $diff$medium$diff$, $prompt$Calcula: $\int \frac{dx}{x^2 - x}$$prompt$, $json$[{"latex":"\\ln\\left|\\frac{x-1}{x}\\right| + C","correct":true},{"latex":"\\ln\\left|\\frac{x}{x-1}\\right| + C","correct":false},{"latex":"\\ln|x(x-1)| + C","correct":false},{"latex":"\\frac{1}{2}\\ln\\left|\\frac{x-1}{x}\\right| + C","correct":false}]$json$::jsonb, $exp$$x^2 - x = x(x-1)$. Con $A=-1$, $B=1$: $\ln|x-1| - \ln|x| + C$.$exp$),
  ($id$fra-m-06$id$, $sec$calculo-integral$sec$, $sub$fracciones-parciales$sub$, $law$fracciones-parciales$law$, $diff$medium$diff$, $prompt$¿Cuál es la descomposición de $\frac{1}{x^2 - 4}$?$prompt$, $json$[{"latex":"\\frac{A}{x-2} + \\frac{B}{x+2}","correct":true},{"latex":"\\frac{A}{x^2} + \\frac{B}{4}","correct":false},{"latex":"\\frac{Ax+B}{x^2-4}","correct":false},{"latex":"\\frac{A}{x-2} + \\frac{B}{x-2}","correct":false}]$json$::jsonb, $exp$$x^2 - 4 = (x-2)(x+2)$: dos factores lineales distintos.$exp$),
  ($id$fra-m-07$id$, $sec$calculo-integral$sec$, $sub$fracciones-parciales$sub$, $law$fracciones-parciales$law$, $diff$medium$diff$, $prompt$¿Cuál es la descomposición de $\frac{1}{x(x+1)^2}$?$prompt$, $json$[{"latex":"\\frac{A}{x} + \\frac{B}{x+1} + \\frac{C}{(x+1)^2}","correct":true},{"latex":"\\frac{A}{x} + \\frac{B}{(x+1)^2}","correct":false},{"latex":"\\frac{A}{x} + \\frac{B}{x+1}","correct":false},{"latex":"\\frac{Ax+B}{x(x+1)^2}","correct":false}]$json$::jsonb, $exp$Un lineal simple ($x$) y uno repetido ($(x+1)^2$): tres términos.$exp$),
  ($id$fra-m-08$id$, $sec$calculo-integral$sec$, $sub$fracciones-parciales$sub$, $law$fracciones-parciales$law$, $diff$medium$diff$, $prompt$Calcula: $\int \frac{dx}{x^2 + 2x}$$prompt$, $json$[{"latex":"\\frac{1}{2}\\ln\\left|\\frac{x}{x+2}\\right| + C","correct":true},{"latex":"\\ln\\left|\\frac{x}{x+2}\\right| + C","correct":false},{"latex":"\\frac{1}{2}\\ln|x(x+2)| + C","correct":false},{"latex":"\\ln|x(x+2)| + C","correct":false}]$json$::jsonb, $exp$$x^2 + 2x = x(x+2)$. Con $A=\frac{1}{2}$, $B=-\frac{1}{2}$: $\frac{1}{2}\ln|x| - \frac{1}{2}\ln|x+2| + C$.$exp$),
  ($id$fra-m-09$id$, $sec$calculo-integral$sec$, $sub$fracciones-parciales$sub$, $law$fracciones-parciales$law$, $diff$medium$diff$, $prompt$En $\frac{1}{x^2 - 4} = \frac{A}{x-2} + \frac{B}{x+2}$, ¿cuánto vale $B$?$prompt$, $json$[{"latex":"B = -\\frac{1}{4}","correct":true},{"latex":"B = \\frac{1}{4}","correct":false},{"latex":"B = -\\frac{1}{2}","correct":false},{"latex":"B = \\frac{1}{2}","correct":false}]$json$::jsonb, $exp$Evaluando $x = -2$: $1 = B(-4)$, luego $B = -\frac{1}{4}$.$exp$),
  ($id$fra-m-10$id$, $sec$calculo-integral$sec$, $sub$fracciones-parciales$sub$, $law$fracciones-parciales$law$, $diff$medium$diff$, $prompt$¿Qué haces si el grado del numerador es mayor o igual que el del denominador?$prompt$, $json$[{"latex":"\\text{División larga de polinomios}","correct":true},{"latex":"\\text{Integrar directamente}","correct":false},{"latex":"\\text{Multiplicar por el conjugado}","correct":false},{"latex":"\\text{Cambiar el signo del denominador}","correct":false}]$json$::jsonb, $exp$Primero se divide para dejar una fracción propia más un polinomio.$exp$),
  ($id$fra-m-11$id$, $sec$calculo-integral$sec$, $sub$fracciones-parciales$sub$, $law$fracciones-parciales$law$, $diff$medium$diff$, $prompt$¿Cómo se factoriza $x^2 + x - 2$?$prompt$, $json$[{"latex":"(x + 2)(x - 1)","correct":true},{"latex":"(x - 2)(x + 1)","correct":false},{"latex":"(x + 2)(x + 1)","correct":false},{"latex":"(x - 2)(x - 1)","correct":false}]$json$::jsonb, $exp$Buscamos dos números que sumen 1 y multipliquen $-2$: son $2$ y $-1$.$exp$),
  ($id$fra-m-12$id$, $sec$calculo-integral$sec$, $sub$fracciones-parciales$sub$, $law$fracciones-parciales$law$, $diff$medium$diff$, $prompt$Calcula: $\int \frac{dx}{x(x-3)}$$prompt$, $json$[{"latex":"\\frac{1}{3}\\ln\\left|\\frac{x-3}{x}\\right| + C","correct":true},{"latex":"\\frac{1}{3}\\ln\\left|\\frac{x}{x-3}\\right| + C","correct":false},{"latex":"\\ln\\left|\\frac{x-3}{x}\\right| + C","correct":false},{"latex":"\\frac{1}{3}\\ln|x(x-3)| + C","correct":false}]$json$::jsonb, $exp$Con $A=-\frac{1}{3}$, $B=\frac{1}{3}$: $\frac{1}{3}\ln|x-3| - \frac{1}{3}\ln|x| + C$.$exp$),
  ($id$fra-h-01$id$, $sec$calculo-integral$sec$, $sub$fracciones-parciales$sub$, $law$fracciones-parciales$law$, $diff$hard$diff$, $prompt$Calcula: $\int \frac{dx}{x^2 - 4x + 3}$$prompt$, $json$[{"latex":"\\frac{1}{2}\\ln\\left|\\frac{x-3}{x-1}\\right| + C","correct":true},{"latex":"\\frac{1}{2}\\ln\\left|\\frac{x-1}{x-3}\\right| + C","correct":false},{"latex":"\\ln|x^2 - 4x + 3| + C","correct":false},{"latex":"\\arctan(x-2) + C","correct":false}]$json$::jsonb, $exp$Factoriza $(x-1)(x-3)$. Con $A=-\frac{1}{2}$, $B=\frac{1}{2}$: $\frac{1}{2}\ln\left|\frac{x-3}{x-1}\right| + C$.$exp$),
  ($id$fra-h-02$id$, $sec$calculo-integral$sec$, $sub$fracciones-parciales$sub$, $law$fracciones-parciales$law$, $diff$hard$diff$, $prompt$Calcula: $\int \frac{x}{x^2 - 1}\,dx$$prompt$, $json$[{"latex":"\\frac{1}{2}\\ln|x^2 - 1| + C","correct":true},{"latex":"\\frac{1}{2}\\ln\\left|\\frac{x-1}{x+1}\\right| + C","correct":false},{"latex":"\\ln|x^2 - 1| + C","correct":false},{"latex":"\\arctan x + C","correct":false}]$json$::jsonb, $exp$El numerador es $\frac{1}{2}$ veces la derivada del denominador: $\frac{1}{2}\ln|x^2-1| + C$.$exp$),
  ($id$fra-h-03$id$, $sec$calculo-integral$sec$, $sub$fracciones-parciales$sub$, $law$fracciones-parciales$law$, $diff$hard$diff$, $prompt$¿Cuál es la descomposición de $\frac{1}{x(x-1)^2}$?$prompt$, $json$[{"latex":"\\frac{A}{x} + \\frac{B}{x-1} + \\frac{C}{(x-1)^2}","correct":true},{"latex":"\\frac{A}{x} + \\frac{B}{(x-1)^2}","correct":false},{"latex":"\\frac{A}{x} + \\frac{B}{x-1}","correct":false},{"latex":"\\frac{Ax + B}{x(x-1)^2}","correct":false}]$json$::jsonb, $exp$Lineal simple $x$ + lineal repetido $(x-1)^2$: tres términos.$exp$),
  ($id$fra-h-04$id$, $sec$calculo-integral$sec$, $sub$fracciones-parciales$sub$, $law$fracciones-parciales$law$, $diff$hard$diff$, $prompt$Calcula: $\int \frac{dx}{x^2 + 2x + 2}$$prompt$, $json$[{"latex":"\\arctan(x + 1) + C","correct":true},{"latex":"\\frac{1}{2}\\arctan\\frac{x+1}{2} + C","correct":false},{"latex":"\\ln(x^2 + 2x + 2) + C","correct":false},{"latex":"\\arctan(x + 2) + C","correct":false}]$json$::jsonb, $exp$El denominador es irreducible: $(x+1)^2 + 1$. Fórmula (18) con $a=1$.$exp$),
  ($id$fra-h-05$id$, $sec$calculo-integral$sec$, $sub$fracciones-parciales$sub$, $law$fracciones-parciales$law$, $diff$hard$diff$, $prompt$En $\frac{x}{x^2 - 1} = \frac{A}{x-1} + \frac{B}{x+1}$, ¿cuánto valen $A$ y $B$?$prompt$, $json$[{"latex":"A = \\frac{1}{2},\\ B = \\frac{1}{2}","correct":true},{"latex":"A = \\frac{1}{2},\\ B = -\\frac{1}{2}","correct":false},{"latex":"A = 1,\\ B = -1","correct":false},{"latex":"A = -\\frac{1}{2},\\ B = \\frac{1}{2}","correct":false}]$json$::jsonb, $exp$$x = A(x+1) + B(x-1)$: en $x=1$ da $A=\frac{1}{2}$; en $x=-1$ da $B=\frac{1}{2}$.$exp$),
  ($id$fra-h-06$id$, $sec$calculo-integral$sec$, $sub$fracciones-parciales$sub$, $law$fracciones-parciales$law$, $diff$hard$diff$, $prompt$¿Cómo se factoriza $x^3 - x$?$prompt$, $json$[{"latex":"x(x - 1)(x + 1)","correct":true},{"latex":"x(x^2 - 1)","correct":false},{"latex":"(x^2 - 1)(x + 1)","correct":false},{"latex":"x(x - 1)^2","correct":false}]$json$::jsonb, $exp$$x^3 - x = x(x^2 - 1) = x(x-1)(x+1)$, tres lineales distintos.$exp$),
  ($id$fra-h-07$id$, $sec$calculo-integral$sec$, $sub$fracciones-parciales$sub$, $law$fracciones-parciales$law$, $diff$hard$diff$, $prompt$Calcula: $\int \frac{dx}{x^2(x+1)}$$prompt$, $json$[{"latex":"\\frac{A}{x} + \\frac{B}{x^2} + \\frac{C}{x+1} \\text{ (descomponer)}","correct":true},{"latex":"\\frac{A}{x^2} + \\frac{B}{x+1}","correct":false},{"latex":"\\frac{A}{x} + \\frac{B}{x+1}","correct":false},{"latex":"\\frac{Ax+B}{x^2(x+1)}","correct":false}]$json$::jsonb, $exp$Lineal repetido $x^2$ (dos términos) + lineal simple $x+1$: $\frac{A}{x} + \frac{B}{x^2} + \frac{C}{x+1}$.$exp$),
  ($id$fra-h-08$id$, $sec$calculo-integral$sec$, $sub$fracciones-parciales$sub$, $law$fracciones-parciales$law$, $diff$hard$diff$, $prompt$¿Cuál integral se resuelve con fracciones parciales?$prompt$, $json$[{"latex":"\\int \\frac{dx}{x^2 - 5x + 6}","correct":true},{"latex":"\\int \\frac{dx}{\\sqrt{x^2 + 1}}","correct":false},{"latex":"\\int x\\,e^x\\,dx","correct":false},{"latex":"\\int \\cos x\\,dx","correct":false}]$json$::jsonb, $exp$$x^2 - 5x + 6 = (x-2)(x-3)$: cociente de polinomios factorizable, ideal para fracciones parciales.$exp$),
  ($id$sust-f-01$id$, $sec$calculo-integral$sec$, $sub$sustitucion-trigonometrica$sub$, $law$sustitucion-trigonometrica$law$, $diff$easy$diff$, $prompt$¿Qué sustitución usas para una integral con $\sqrt{a^2 - x^2}$?$prompt$, $json$[{"latex":"x = a\\sin\\theta","correct":true},{"latex":"x = a\\tan\\theta","correct":false},{"latex":"x = a\\sec\\theta","correct":false},{"latex":"x = a\\cos^2\\theta","correct":false}]$json$::jsonb, $exp$Para $\sqrt{a^2 - x^2}$ se usa $x = a\sin\theta$, pues $a^2 - a^2\sin^2\theta = a^2\cos^2\theta$.$exp$),
  ($id$sust-f-02$id$, $sec$calculo-integral$sec$, $sub$sustitucion-trigonometrica$sub$, $law$sustitucion-trigonometrica$law$, $diff$easy$diff$, $prompt$¿Qué sustitución usas para una integral con $\sqrt{a^2 + x^2}$?$prompt$, $json$[{"latex":"x = a\\tan\\theta","correct":true},{"latex":"x = a\\sin\\theta","correct":false},{"latex":"x = a\\sec\\theta","correct":false},{"latex":"x = a\\csc\\theta","correct":false}]$json$::jsonb, $exp$Para $\sqrt{a^2 + x^2}$ se usa $x = a\tan\theta$: $a^2 + a^2\tan^2\theta = a^2\sec^2\theta$.$exp$),
  ($id$sust-f-03$id$, $sec$calculo-integral$sec$, $sub$sustitucion-trigonometrica$sub$, $law$sustitucion-trigonometrica$law$, $diff$easy$diff$, $prompt$¿Qué sustitución usas para una integral con $\sqrt{x^2 - a^2}$?$prompt$, $json$[{"latex":"x = a\\sec\\theta","correct":true},{"latex":"x = a\\tan\\theta","correct":false},{"latex":"x = a\\sin\\theta","correct":false},{"latex":"x = a\\cos\\theta","correct":false}]$json$::jsonb, $exp$Para $\sqrt{x^2 - a^2}$ se usa $x = a\sec\theta$: $a^2\sec^2\theta - a^2 = a^2\tan^2\theta$.$exp$),
  ($id$sust-f-04$id$, $sec$calculo-integral$sec$, $sub$sustitucion-trigonometrica$sub$, $law$sustitucion-trigonometrica$law$, $diff$easy$diff$, $prompt$Para $\int \frac{dx}{\sqrt{4 - x^2}}$, ¿qué sustitución usas?$prompt$, $json$[{"latex":"x = 2\\sin\\theta","correct":true},{"latex":"x = 2\\tan\\theta","correct":false},{"latex":"x = 2\\sec\\theta","correct":false},{"latex":"x = \\sin\\theta","correct":false}]$json$::jsonb, $exp$$a^2 = 4$, así que $a = 2$ y $x = 2\sin\theta$.$exp$),
  ($id$sust-f-05$id$, $sec$calculo-integral$sec$, $sub$sustitucion-trigonometrica$sub$, $law$sustitucion-trigonometrica$law$, $diff$easy$diff$, $prompt$Para $\int \frac{dx}{\sqrt{9 + x^2}}$, ¿qué sustitución usas?$prompt$, $json$[{"latex":"x = 3\\tan\\theta","correct":true},{"latex":"x = 3\\sin\\theta","correct":false},{"latex":"x = 3\\sec\\theta","correct":false},{"latex":"x = 9\\tan\\theta","correct":false}]$json$::jsonb, $exp$$a^2 = 9$, así que $a = 3$ y $x = 3\tan\theta$.$exp$),
  ($id$sust-m-01$id$, $sec$calculo-integral$sec$, $sub$sustitucion-trigonometrica$sub$, $law$sustitucion-trigonometrica$law$, $diff$medium$diff$, $prompt$¿Qué identidad pitagórica se usa con la sustitución $x = a\sin\theta$?$prompt$, $json$[{"latex":"1 - \\sin^2\\theta = \\cos^2\\theta","correct":true},{"latex":"1 + \\tan^2\\theta = \\sec^2\\theta","correct":false},{"latex":"\\sec^2\\theta - 1 = \\tan^2\\theta","correct":false},{"latex":"\\sin^2\\theta + \\cos^2\\theta = 0","correct":false}]$json$::jsonb, $exp$$a^2 - a^2\sin^2\theta = a^2(1 - \sin^2\theta) = a^2\cos^2\theta$.$exp$),
  ($id$sust-m-02$id$, $sec$calculo-integral$sec$, $sub$sustitucion-trigonometrica$sub$, $law$sustitucion-trigonometrica$law$, $diff$medium$diff$, $prompt$¿Qué identidad pitagórica se usa con la sustitución $x = a\tan\theta$?$prompt$, $json$[{"latex":"1 + \\tan^2\\theta = \\sec^2\\theta","correct":true},{"latex":"1 - \\sin^2\\theta = \\cos^2\\theta","correct":false},{"latex":"\\sec^2\\theta - 1 = \\tan^2\\theta","correct":false},{"latex":"\\tan^2\\theta = \\sin^2\\theta","correct":false}]$json$::jsonb, $exp$$a^2 + a^2\tan^2\theta = a^2(1 + \tan^2\theta) = a^2\sec^2\theta$.$exp$),
  ($id$sust-m-03$id$, $sec$calculo-integral$sec$, $sub$sustitucion-trigonometrica$sub$, $law$sustitucion-trigonometrica$law$, $diff$medium$diff$, $prompt$¿Qué identidad pitagórica se usa con la sustitución $x = a\sec\theta$?$prompt$, $json$[{"latex":"\\sec^2\\theta - 1 = \\tan^2\\theta","correct":true},{"latex":"1 - \\sin^2\\theta = \\cos^2\\theta","correct":false},{"latex":"1 + \\tan^2\\theta = \\sec^2\\theta","correct":false},{"latex":"\\sec^2\\theta + 1 = \\tan^2\\theta","correct":false}]$json$::jsonb, $exp$$a^2\sec^2\theta - a^2 = a^2(\sec^2\theta - 1) = a^2\tan^2\theta$.$exp$),
  ($id$sust-m-04$id$, $sec$calculo-integral$sec$, $sub$sustitucion-trigonometrica$sub$, $law$sustitucion-trigonometrica$law$, $diff$medium$diff$, $prompt$Con $x = 2\sec\theta$, ¿cuánto vale $dx$?$prompt$, $json$[{"latex":"dx = 2\\sec\\theta\\tan\\theta\\,d\\theta","correct":true},{"latex":"dx = 2\\sec^2\\theta\\,d\\theta","correct":false},{"latex":"dx = 2\\tan\\theta\\,d\\theta","correct":false},{"latex":"dx = 2\\cos\\theta\\,d\\theta","correct":false}]$json$::jsonb, $exp$La derivada de $\sec\theta$ es $\sec\theta\tan\theta$.$exp$),
  ($id$sust-m-05$id$, $sec$calculo-integral$sec$, $sub$sustitucion-trigonometrica$sub$, $law$sustitucion-trigonometrica$law$, $diff$medium$diff$, $prompt$En $x = 3\sin\theta$, ¿a qué equivale $\sqrt{9 - x^2}$?$prompt$, $json$[{"latex":"3\\cos\\theta","correct":true},{"latex":"3\\sin\\theta","correct":false},{"latex":"\\cos\\theta","correct":false},{"latex":"9\\cos\\theta","correct":false}]$json$::jsonb, $exp$$\sqrt{9 - 9\sin^2\theta} = \sqrt{9\cos^2\theta} = 3\cos\theta$ (con $\cos\theta \geq 0$).$exp$)
ON CONFLICT (id) DO UPDATE SET
  section_id  = EXCLUDED.section_id,
  subtema_id  = EXCLUDED.subtema_id,
  law_id      = EXCLUDED.law_id,
  difficulty  = EXCLUDED.difficulty,
  prompt      = EXCLUDED.prompt,
  options     = EXCLUDED.options,
  explanation = EXCLUDED.explanation,
  updated_at  = now();

-- Lote 4 (5 preguntas)
INSERT INTO public.questions (id, section_id, subtema_id, law_id, difficulty, prompt, options, explanation)
VALUES
  ($id$sust-m-06$id$, $sec$calculo-integral$sec$, $sub$sustitucion-trigonometrica$sub$, $law$sustitucion-trigonometrica$law$, $diff$medium$diff$, $prompt$¿Qué sustitución transforma $\frac{dx}{x^2 + 4}$ en una integral trigonométrica?$prompt$, $json$[{"latex":"x = 2\\tan\\theta","correct":true},{"latex":"x = 2\\sin\\theta","correct":false},{"latex":"x = 2\\sec\\theta","correct":false},{"latex":"x = 4\\tan\\theta","correct":false}]$json$::jsonb, $exp$El denominador es $x^2 + 4 = x^2 + a^2$, con $a = 2$: $x = 2\tan\theta$.$exp$),
  ($id$sust-h-01$id$, $sec$calculo-integral$sec$, $sub$sustitucion-trigonometrica$sub$, $law$sustitucion-trigonometrica$law$, $diff$hard$diff$, $prompt$Calcula $\int \frac{dx}{x^2 + 4}$ usando $x = 2\tan\theta$.$prompt$, $json$[{"latex":"\\frac{1}{2}\\arctan\\frac{x}{2} + C","correct":true},{"latex":"\\arctan\\frac{x}{2} + C","correct":false},{"latex":"\\frac{1}{4}\\arctan x + C","correct":false},{"latex":"\\ln(x^2 + 4) + C","correct":false}]$json$::jsonb, $exp$$dx = 2\sec^2\theta\,d\theta$; la integral da $\frac{1}{2}\theta + C = \frac{1}{2}\arctan\frac{x}{2} + C$.$exp$),
  ($id$sust-h-02$id$, $sec$calculo-integral$sec$, $sub$sustitucion-trigonometrica$sub$, $law$sustitucion-trigonometrica$law$, $diff$hard$diff$, $prompt$Calcula $\int \frac{dx}{\sqrt{9 - x^2}}$ usando $x = 3\sin\theta$.$prompt$, $json$[{"latex":"\\arcsin\\frac{x}{3} + C","correct":true},{"latex":"\\arcsin\\frac{x}{9} + C","correct":false},{"latex":"\\frac{1}{3}\\arcsin x + C","correct":false},{"latex":"\\arccos\\frac{x}{3} + C","correct":false}]$json$::jsonb, $exp$$\int d\theta = \theta + C = \arcsin\frac{x}{3} + C$.$exp$),
  ($id$sust-h-03$id$, $sec$calculo-integral$sec$, $sub$sustitucion-trigonometrica$sub$, $law$sustitucion-trigonometrica$law$, $diff$hard$diff$, $prompt$Calcula $\int \frac{dx}{x\sqrt{x^2 - 9}}$ usando $x = 3\sec\theta$.$prompt$, $json$[{"latex":"\\frac{1}{3}\\operatorname{arcsec}\\frac{x}{3} + C","correct":true},{"latex":"\\operatorname{arcsec}\\frac{x}{3} + C","correct":false},{"latex":"\\frac{1}{3}\\arctan\\frac{x}{3} + C","correct":false},{"latex":"\\frac{1}{3}\\ln\\left|x + \\sqrt{x^2-9}\\right| + C","correct":false}]$json$::jsonb, $exp$Simplifica a $\int\frac{1}{3}\,d\theta = \frac{1}{3}\theta + C = \frac{1}{3}\operatorname{arcsec}\frac{x}{3} + C$.$exp$),
  ($id$sust-h-04$id$, $sec$calculo-integral$sec$, $sub$sustitucion-trigonometrica$sub$, $law$sustitucion-trigonometrica$law$, $diff$hard$diff$, $prompt$¿Para qué se usa principalmente la sustitución trigonométrica?$prompt$, $json$[{"latex":"\\text{Eliminar raíces cuadradas usando identidades pitagóricas}","correct":true},{"latex":"\\text{Convertir logaritmos en potencias}","correct":false},{"latex":"\\text{Derivar funciones compuestas}","correct":false},{"latex":"\\text{Resolver ecuaciones diferenciales lineales}","correct":false}]$json$::jsonb, $exp$Convierte $\sqrt{a^2 \pm x^2}$ o $\sqrt{x^2 - a^2}$ en expresiones trigonométricas sin raíz.$exp$)
ON CONFLICT (id) DO UPDATE SET
  section_id  = EXCLUDED.section_id,
  subtema_id  = EXCLUDED.subtema_id,
  law_id      = EXCLUDED.law_id,
  difficulty  = EXCLUDED.difficulty,
  prompt      = EXCLUDED.prompt,
  options     = EXCLUDED.options,
  explanation = EXCLUDED.explanation,
  updated_at  = now();

-- Limpieza de filas de prueba
DELETE FROM public.questions WHERE id = 'test-debug';
